### ISSUE TITLE
Category filtering

### ISSUE THREAD

**Issue by eric-bohanon** [magento/graphql-ce#10]
The category query should include a filter argument, similar to the products query. It should achieve parity with the REST API's search criteria functionality on category entities.

AC
- User is able to filter categories by
   - id
   - name
   - description
   - isAnchor: return only categories that are isAnchor=yes or isAnchor=no
   - level: return only categories that are on the specified level in the tree
   - parentId: return only direct children of the specified parent category
- Endpoint accepts new filter criteria, and returns an array of matching CategoryTree objects

References:
* See [\Magento\CatalogGraphQl\Model\Resolver\Products::resolve](https://github.com/magento/magento2/blob/fb5eccfc7179d9180178bc5e648fd0ad07ea3cf6/app/code/Magento/CatalogGraphQl/Model/Resolver/Products.php#L82) as an example to generate search criteria with existing framework mechanisms

### Expected result
1. It is possible to filter categories based on filterable attributes in a category query.
2. Functionality is covered by automated api-functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.

**Comment by nuzil** [comment]
WebApi category search has no searchCriteria. Can you provide small info about usecase for filtering categories tree?

**Comment by misha-kotov** [comment]
A use case could be displaying "related" categories. For example, I'm on the category "Men's Ties", showing a list of products. My parent category is "Men's Dress Attire". At the bottom of my page I could display a list of related categories by filtering categories for name `contains` "ties" and display "Tie Clips", "Tie Bars", "Bow Ties". You could also filter for categories by the common parent to find "sibling" categories and display those.

**Comment by mhaack** [comment]
Can I extend the category filter requirement by adding:
* User is able to filter categories by url_key
* User is able to filter categories by url_path

The use case is building nice, SEO friendly URLs to address category pages like `http://mysite.com/men/shoes` requires a way to retrieve category details and products within that category by `url_path`. Currently that is only possible via the category id.

**Comment by naydav** [comment]
Closed due to
https://github.com/magento/graphql-ce/issues/567
