### ISSUE TITLE
Category tree depth calculation issue

### ISSUE THREAD

**Issue by dmytro-ch** [magento/graphql-ce#100]
The maximum level value is being calculated incorrectly.

### Preconditions
The result response does not contain the last child item (specified on the deepest level according to the request).
Looks like the issue appears due to the incorrect maximum depth level calculation in ``\Magento\CatalogGraphQl\Model\Resolver\Products\DataProvider`` (line 100).

### Expected result
<img width="955" alt="screen shot 2018-06-30 at 12 26 38 pm" src="https://user-images.githubusercontent.com/11693779/42123848-8cb003a2-7c61-11e8-9ae9-d131802229d0.png">

### Actual result
<img width="949" alt="screen shot 2018-06-30 at 12 27 25 pm" src="https://user-images.githubusercontent.com/11693779/42123850-9197a230-7c61-11e8-922d-6c9a651c907e.png">

**Comment by erikkubica** [comment]
@dmytro-ch as i see for your the category children is working, for some reason for me it´s not i have posted a issue here https://github.com/magento/graphql-ce/issues/123 can you see please anything work with my query?

**Comment by naydav** [comment]
@erikkubica 
Hi, I will check https://github.com/magento/graphql-ce/issues/123 issue

**Comment by naydav** [comment]
Merged with
https://github.com/magento/graphql-ce/pull/102

**Comment by naydav** [comment]
One more PR
https://github.com/magento/graphql-ce/pull/121
