### ISSUE TITLE
Docs: Create topic for addDownloadableProductsToCart mutation

### ISSUE THREAD

**Issue by keharper** [magento/graphql-ce#1003]
### Summary (*)

Related issue: #146 
Related PR: #412 

The `addDownloadableProductsToCart`mutation needs to be documented on Devdocs

### Proposed solution

Create a PR on devdocs that meet the following requirements

1. Create the PR against the `develop` branch.

2. Place the documentation in `guides/v2.3/graphql/mutations/add-downloadable-products.md`

3. Update the left navigation by adding a link to this topic at `_data/toc/graphql.yml`

Do not update the tutorial at this point.

**Comment by atwixfirster** [comment]
Pull request: https://github.com/magento/devdocs/pull/5672
