### ISSUE TITLE
Docs: Create topic for customerDownloadableProducts query

### ISSUE THREAD

**Issue by keharper** [magento/graphql-ce#1004]
### Summary (*)

Related issue: #685 
Related PR: #802  

The `customerDownloadableProducts` query needs to be documented on [Devdocs](https://github.com/magento/devdocs).

### Proposed solution

Create a [PR on devdocs](https://github.com/magento/devdocs) that meet the following requirements

1. Create the PR against the `develop` branch.

2. Place the documentation in `guides/v2.3/graphql/queries/customer-downloadable-products.md`

3. Update the left navigation by adding a link to this topic at `_data/toc/graphql.yml`

**Comment by atwixfirster** [comment]
Documentation for this issue has been already added by @keharper !

I've added minor changes and added `Errors` section - https://github.com/magento/devdocs/pull/5714

Thank you!
