### ISSUE TITLE
`id` in Region is unnecessary

### ISSUE THREAD

**Issue by buskamuza** [magento/graphql-ce#1018]
`region_id` is deprecated in all places. Thus `id` in `Region` is unnecessary. Any logic should rely on `Region.code`.

AC:
- `Region.id` is deprecated

**Comment by fooman** [comment]
Isn't this direction opposite to what the PWA team is looking for here https://github.com/magento/graphql-ce/issues/930 ?

**Comment by buskamuza** [comment]
Closing this one in favor of generic approach with having ids in entities that can be cached - https://github.com/magento/devdocs/pull/5872
Not sure if region needs to be cached, but potentially it's possible. So let's keep the functionality if it's already there.
