### ISSUE TITLE
Bundle can be added to Cart without Required option defined

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#1039]
### Preconditions (*)

1. Create a Bundle product, containing two Required Options. One Multiple Select containing two products. The other, Checkbox, containing two products
![67855560-53cad000-fb1b-11e9-8d94-4431fb7a301a](https://user-images.githubusercontent.com/11827230/67963294-062b9180-fc07-11e9-8e10-2515d1846651.png)

### Steps to reproduce (*)

1. Perform GraphQL mutation trying to add Bundle to Cart. The mutation contains empty value Required Multiple Select and a valid value in Checkbox
```graphql
mutation {
  addBundleProductsToCart(
    input: {
      cart_id: "12345678912345678912345678912345"
      cart_items: {
        data: {
          quantity: 1
          sku: "Bundle" #sku of the parent bundle 
        }
        bundle_options: [
          {
            id: 5 #multiple select Input Type id
            quantity: 1
            value: [
              "" #options id             
            ]
          }
          {
            id: 7 #checkbox Input Type id
            quantity: 1
            value: [
              "16" #options id
            ]
          }
        ]
      }
    }
  ) {
    cart {
      items {
        id
        quantity
        product {
          sku
          stock_status
        }
        ... on SimpleCartItem {
          customizable_options {
            id
            label
            values {
              id
              label
              value
            }
          }
        }
      }
    }
  }
}
```
To check the Options Id's on your instance, perform GraphQL query
```graphql
{
  products(
    filter: {
      sku: {
        eq: "Bundle"
      }
    }
  ) {
    items {
      sku
      ... on BundleProduct {
        price_view
        items {
          option_id #input type id
          title
          type
          options {
            id #options id
            label
            position
            price_type
            product {
              id
              sku
            }
            quantity
          }
        }
      }
    }
  }
}
```

### Expected result (*)

1. The product is not added to Cart, because one of the required options has not been defined.
![67857836-71e6ff00-fb20-11e9-939b-b5359266136b](https://user-images.githubusercontent.com/11827230/67963345-19d6f800-fc07-11e9-837e-5e06e33e0423.png)

### Actual result (*)

1. The Product is added to Cart with one option selected
![67858084-02bdda80-fb21-11e9-8188-90498efdc850](https://user-images.githubusercontent.com/11827230/67963482-56a2ef00-fc07-11e9-8c0a-d844fe3fcc34.png)

**Comment by lenaorobei** [comment]
Closed in favor of https://github.com/magento/magento2/issues/25676
