### ISSUE TITLE
[Documentation] addConfigurableProductsToCart mutation

### ISSUE THREAD

**Issue by lenaorobei** [magento/graphql-ce#1048]
`addConfigurableProductsToCart` mutation should be documented in the corresponding section.
https://devdocs.magento.com/guides/v2.3/graphql/mutations/

**Comment by atwixfirster** [comment]
@lenaorobei , already documented - https://devdocs.magento.com/guides/v2.3/graphql/mutations/add-configurable-products.html

**Comment by lenaorobei** [comment]
@atwixfirster by bad, I didn't noticed that. Thanks.

**Comment by atwixfirster** [comment]
> @atwixfirster by bad, I didn't noticed that. Thanks.

always welcome :)
