### ISSUE TITLE
Emails validation works differently

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#1054]
### Preconditions (*)

1. No

### Steps to reproduce (*)

1. Create Customer Account
```graphql
mutation {
  createCustomer(
    input: {
      firstname: "Fernanda"
      lastname: "Hernández"
      email: "t@rioe.d5"
      password: "123123qA"
    }
  ) {
    customer {
      addresses {
        city
        region {
          region
          region_code
        }
        country_id
      }
    }
  }
}
```

### Expected result (*)

1. "message": "Please enter a valid email address (Ex: johndoe@domain.com)."

### Actual result (*)

1. Successfully saved

**Comment by vasylmalanka** [comment]
@magento give me 2.3-develop instance
