### ISSUE TITLE
2.3-develop - graphql fetching issue for phtml file called in product/category descriptions

### ISSUE THREAD

**Issue by mtbottens** [magento/graphql-ce#1057]
Note: Assumption is that this happens for category description as well, but I have not confirmed that one.

### Preconditions (*)

1. 2.3-develop
2. Configure a cms block with any content
![image](https://user-images.githubusercontent.com/3620915/68691569-f6cf1100-0541-11ea-9526-e770c15b48e5.png)
3. Configure a product description attribute with a widget directive: `{{widget type="Magento\Cms\Block\Widget\Block" template="widget/static_block/default.phtml" block_id="1" type_name="CMS Static Block"}}`
![image](https://user-images.githubusercontent.com/3620915/68691596-ffbfe280-0541-11ea-8ec6-20e95d43e4d1.png)

### Steps to reproduce (*)

1. Navigate to the product with the configured description containing a widget directive. (Frontend)
2. Observe that the static block is rendered.
![image](https://user-images.githubusercontent.com/3620915/68691631-0e0dfe80-0542-11ea-8297-7e1c702f7e44.png)
3. Request the product with graphql:
```
{
  products(filter: { sku: { eq: "Test"} }) {
    items {
      description{
        html
      }
    }
  }
}
```
4. Observe that the static block content is not included in the graphql response.
![image](https://user-images.githubusercontent.com/3620915/68691660-19612a00-0542-11ea-990a-2a327bbd1469.png)

### Expected result (*)

1. Graphql response should contain the same content that is rendered on the frontend.

### Actual result (*)

1. Graphql response does not match content that is rendered on the frontend.

**Comment by magento-engcom-team** [comment]
Hi @mtbottens. Thank you for your report. 
The issue has been fixed in magento/graphql-ce#1058 by @mtbottens in 2.3-develop branch
Related commit(s):
 - [8216835579c8c9ed9f954016a6fed90eb98916fa](https://github.com/magento/graphql-ce/commit/8216835579c8c9ed9f954016a6fed90eb98916fa)

The fix will be available with the upcoming  release.
