### ISSUE TITLE
[Test Coverage] Cover exception in QuoteGraphQl/Model/Resolver/RemoveItemFromCart.php

### ISSUE THREAD

**Issue by chalov-anton** [magento/graphql-ce#1069]
### Description:
Cover exception with API-functional test
https://github.com/magento/graphql-ce/blob/765f3804e919e5f06f4941eb4a227258befe2995/app/code/Magento/QuoteGraphQl/Model/Resolver/RemoveItemFromCart.php#L70

### Examples:
https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Customer

https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer

### Guide:
https://devdocs.magento.com/guides/v2.3/graphql/functional-testing.htm

**Comment by atwixfirster** [comment]
Look like we should cover [The item couldn't be removed from the quote.](https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/Quote/Model/Quote/Item/Repository.php#L128) exception here. 

However, it's almost impossible to simulate this exception via fixtures.

CC: @lenaorobei
