### ISSUE TITLE
Alphabetize Schema Fields

### ISSUE THREAD

**Issue by eric-bohanon** [magento/graphql-ce#11]
The GraphQL fields should be alphabetized so that it's easier to find a specific field. 
Currently fields are not sorted so it's harder to find one on the list.

### Expected result

1. Schema fields are sorted, in the Docs panel and autocomplete list.
2. Alphabetization should be verified by api-functional automated test.

**Comment by astyczen** [comment]
@eric-bohanon do u think it should be sorted after the query is mage or on the schema level?

**Comment by eric-bohanon** [comment]
Hi @astyczen,

This would need to be sorted on the schema level.

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/104
