### ISSUE TITLE
Partial Response With NULL value

### ISSUE THREAD

**Issue by roma-glushko** [magento/graphql-ce#110]
### Preconditions
1. Magento 2 Open Source
2. GraphQL modules

### Steps to reproduce
1. Execute GraphQL request that should return partial response 

### Expected result
1. Response should contain errors and data keys.
2. If item can be retrieved via GraphQL a new item to errors array is added, **no** NULL value is also added to data key

### Actual result
1. Response should contain errors and data keys.
2. If item can be retrieved via GraphQL a new item to errors array is added, but null value is also added to data key

<img width="1328" alt="screen shot 2018-06-30 at 6 00 25 pm" src="https://user-images.githubusercontent.com/9402690/42126371-2cb64e50-7c90-11e8-9ecb-3401a0a472af.png">

Looks like this is a default GraphQL behaviour defined in vendor/webonyx/graphql-php/src/Executor/Executor.php:769 class. However, it's needed to consider if we can improve this point.

**Comment by naydav** [comment]
Fixed in https://github.com/magento/graphql-ce/pull/221#issuecomment-441033473
