### ISSUE TITLE
[Commerce] CMS block coverage

### ISSUE THREAD

**Issue by roma-glushko** [magento/graphql-ce#111]
### Preconditions
1. Magento 2 Commerce 
2. GraphQL modules (Especially Magento_CmsGraphQl from #32)

### Description

There is need to support retrieving Commerce specific information on cmsPage GraphQL API:
- rendered content (with no Magento-specific directives) 
- use `\Magento\Widget\Model\Template\Filter::filter`

Related ticked: #32

**Comment by melnikovi** [comment]
Hi @roma-glushko. Please use the following API to parse directives in the content `\Magento\Widget\Model\Template\Filter::filter`. Let me know if you have any questions.

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/109

**Comment by paliarush** [comment]
@naydav this issue is not merged, looks like it was closed by mistake instead of https://github.com/magento/graphql-ce/issues/32

Reopening

**Comment by roma-glushko** [comment]
Hi @melnikovi 

Can I use \Magento\Widget\Model\Template\FilterEmulate instead? 

There is an issue with using Magento\Widget\Model\Template\Filter in graphql area. Widget are not rendered because of expecting to fetch their templates from frontend area on Magento Open Source.

Looks like FilterEmulate was created to be used from non-frontend areas like in our case.

Please let me know your thoughts on this matter.

Thanks,
Roman.

**Comment by melnikovi** [comment]
Hi @roma-glushko. Yes, I think we can use `\Magento\Widget\Model\Template\FilterEmulate` instead.

**Comment by roma-glushko** [comment]
@paliarush just would like to let you kwow changes have been applied in task #31 (PR #105 ). It will be possible to return rendered content of CMS entities. Thank you!
