### ISSUE TITLE
Media collection array order and "position" parameters do not match or reflect admin entry

### ISSUE THREAD

**Issue by zetlen** [magento/graphql-ce#113]
When querying for product media, the JSON response returns `media_gallery_entries` as an array. Arrays are ordered, but the objects also sometimes have a `position` parameter.

Neither the array order or the position parameter appears to reflect the data entered by the user. Ideally, the array order would be the desired position order; sorting on the client is a performance problem. But currently, neither the array ordering nor the position parameter are accurate.

### Preconditions

1. An M2.3 alpha store provisioned with Luma sample data
2. GraphiQl or anything that can run GQL queries

Magento version: 2.2.0-rc3.0-12043-g6c69054457c
HEAD: 6c69054457c
PHP: 7.1.19
MySQL: 5.7.22

### Steps to reproduce

1. Run the following GraphQL query:
    ```graphql
    {
       products(filter: { url_key: { eq: "strive-shoulder-pack" } }) {
            items {
                media_gallery_entries {
                    label
                    position
                    disabled
                    file
                }
            }
        }
    }
    ```
2. Admin Login > Catalog > Strive Shoulder Pack > Edit > Images and Videos
3. Upload a new image with the filename `test.png`. Click the image. Add alt text "test text" and select the "Base", "Small", and "Thumbnail" roles. Close the image editor drawer.
4. Using the drag handle, drag the new image between the two existing images to reorder it.
5. Save the product. Flush cache and reindex.
6. Run the query from Step 1 again.

### Expected result

First query result:
```
{
  "data": {
    "products": {
      "items": [
        {
          "media_gallery_entries": [
            {
              "label": "Image",
              "position": 1,
              "disabled": false,
              "file": "/m/b/mb04-black-0.jpg"
            },
            {
              "label": "Image",
              "position": 2,
              "disabled": false,
              "file": "/m/b/mb04-black-0_alt1.jpg"
            }
          ]
        }
      ]
    }
  }
}
```

Second query result:

```diff
{
  "data": {
    "products": {
      "items": [
        {
          "media_gallery_entries": [
            {
              "label": "Image",
              "position": 1,
              "disabled": false,
              "file": "/m/b/mb04-black-0.jpg"
            },
+           {
+             "label": "test text",
+             "position": 2,
+             "disabled": false,
+             "file": "/path/to/test.png"
+           },
            {
              "label": "Image",
-             "position": 2,
+             "position": 3,
              "disabled": false,
              "file": "/m/b/mb04-black-0_alt1.jpg"
            }
          ]
        }
      ]
    }
  }
}
```
### Actual result

Second query result:
```diff
{
  "data": {
    "products": {
      "items": [
        {
          "media_gallery_entries": [
+           {
+             "label": null,
+             "position": null,
+             "disabled": null,
+             "file": "/page/to/test.png"
+           },
            {
              "label": "Image",
              "position": 1,
              "disabled": false,
              "file": "/m/b/mb04-black-0.jpg"
            },
            {
              "label": "Image",
              "position": 2,
              "disabled": false,
              "file": "/m/b/mb04-black-0_alt1.jpg"
            }
          ]
        }
      ]
    }
  }
}
```

**Comment by paliarush** [comment]
Cannot reproduce the issue, getting the following response:
```
{
  "data": {
    "products": {
      "items": [
        {
          "media_gallery_entries": [
            {
              "label": "Image",
              "position": 0,
              "disabled": false,
              "file": "/m/b/mb04-black-0.jpg"
            },
            {
              "label": "Test Alt",
              "position": 1,
              "disabled": false,
              "file": "/s/c/screen_shot_2018-07-24_at_2.30.29_pm.png"
            },
            {
              "label": "Image",
              "position": 2,
              "disabled": false,
              "file": "/m/b/mb04-black-0_alt1.jpg"
            }
          ]
        }
      ]
    }
  }
}
```

I know that @rogyar was also having troubles reproducing it.

@zetlen please try the same scenario again on the latest mainline and provide additional details which might help us to reproduce the issue.

**Comment by rogyar** [comment]
Same here. The values are the same as in the database and the array items are always sorted by position. So, can't reproduce this one.

**Comment by zetlen** [comment]
It may have been an artifact of the Luma sample data or the store I was using. I will attempt to reproduce in a clean environment.

**Comment by naydav** [comment]
@zetlen 
Looks we cannot reproduce the issue

Please, reopen the ticket if you will forced with this bug again.
