### ISSUE TITLE
[Cart Operations] Create Empty Cart

### ISSUE THREAD

**Issue by paliarush** [magento/graphql-ce#118]
Implement mutation for empty cart creation by the guest/customer user.

Cart ID is expected in the response. For the guest it should be hashed. 

**AC**:
- `createEmptyCart` mutation is declared. Should accept no arguments and return cart ID of type `String`. See example of [mutation declaration](https://github.com/magento/graphql-ce/blob/db3f2c73416c19f9cc13b1cbc48d504e843dc476/dev/tests/api-functional/_files/Magento/TestModuleGraphQlQuery/etc/schema.graphqls#L9)
- For guest (no token provided via `Authorization` header), the following service should be used `\Magento\Quote\Api\GuestCartManagementInterface::createEmptyCart`
- For customer (valid customer token is provided via `Authorization` header), the followigng service should be used `\Magento\Quote\Api\CartManagementInterface::createEmptyCartForCustomer`
- Changes are covered with web API functional tests. See [\Magento\GraphQl\TestModule\GraphQlMutationTest::testMutation](https://github.com/magento/graphql-ce/blob/db3f2c73416c19f9cc13b1cbc48d504e843dc476/dev/tests/api-functional/testsuite/Magento/GraphQl/TestModule/GraphQlMutationTest.php#L15) as an example.

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/166
