### ISSUE TITLE
GraphQL - Category query - children field returning empty [CategoryTree]

### ISSUE THREAD

**Issue by erikkubica** [magento/graphql-ce#123]
### Preconditions

1. Magento 2.3-dev
2. MYSQL 5.6
3. PHP 7.1.X
4. Ubuntu 16

### Summary of the issue
"children" field of "category" query is not populated in GraphQL result.

### Steps to reproduce
1. Get the latest zip of magento 2.3-dev from github
2. Install magento using standard next next finish process
3. Add a product
4. Add one or more subcategories into default category
5. Check if categories and products are working correctly on the front-end
6. Create a GraphQL Query

```
query ($categoryId: Int!) {
  menu: category(id: $categoryId) {
    id
    name
    children_count
    children {
      name
    }
  }
}
```

### Expected result
```
{
  "data": {
    "menu": {
      "id": 2,
      "name": "Default Category",
      "children_count": "2",
      "children": [populated array of category names]
    }
  }
}
```

### Actual result
```
{
  "data": {
    "menu": {
      "id": 2,
      "name": "Default Category",
      "children_count": "2",
      "children": []
    }
  }
}
```

### Maybe issue
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/CatalogGraphQl/Model/Category/Hydrator.php

$categoryData['children'] = []; 

I am not expert, but I think here should be some thing else then empty array.

If anyone knows where the issue is, or how I can fetch list of categories using GraphQL in M2.3 let me know please.

Thank You for you hard work, 2.3 looks really amazing

### Other information
- Version is 2.3-develop https://github.com/magento/magento2/tree/2.3-develop
- It's clean vanilla magento instance, no third party modules or themes (http://m23sandbox.netlime.eu)
- I confirm that here: http://m23sandbox.netlime.eu/graphql the issue can be reproduced with the following query

```
query ($categoryId: Int!) {
  menu: category(id: $categoryId) {
    id
    name
    children_count
    children {
      name
    }
  }
}
```

and with following query variables

```
{
  "categoryId": 2
}
```

**Comment by paliarush** [comment]
@erikkubica thank you for reporting the issue. Please confirm that it has been resolved after https://github.com/magento/graphql-ce/issues/100 was merged to mainline 4 days ago. 

Please close current issue if confirmed to be a duplicate of https://github.com/magento/graphql-ce/issues/100

**Comment by erikkubica** [comment]
@paliarush I have downloaded and redeployed the GraphQL module, issue is not fixed. If you compare the expected result and the result of my issue and issue in #100 then you can see it's not totally the same, even if it looks like.

I will keep the VPS running here http://m23sandbox.netlime.eu/graphql all origins are allowed so you can spam it with remote queries (sample data is installed). Also if needed tell me how I can PM you and I can give you ssh/sftp access to the VPS.

**Comment by paliarush** [comment]
I can confirm that getting the same results as @erikkubica on the latest `mainline/2.3-develop` branch. It looks like the fix in #100 didn't resolve the issue for all use cases.

**Comment by rogyar** [comment]
I've tried different scenarios but can't reproduce it on the current `2.3-develop` installation and sample data from `2.3-develop` branch installed. Here is an attempt for the default category:

**Request**
```
query ($categoryId: Int!) {
  menu: category(id: $categoryId) {
    id
    name
    children_count
    children {
      name
    }
  }
}
```

**Query params**
```
{
  "categoryId": 2
}
```

**Response**
```
{
  "data": {
    "menu": {
      "id": 2,
      "name": "Default Category",
      "children_count": "-8",
      "children": [
        {
          "name": "Gear"
        },
        {
          "name": "Collections"
        },
        {
          "name": "Training"
        },
        {
          "name": "Men"
        },
        {
          "name": "Women"
        },
        {
          "name": "Promotions"
        },
        {
          "name": "Sale"
        },
        {
          "name": "What's New"
        }
      ]
    }
  }
}
```

Children also appear in other categories. Also tested with no sample data installed, works fine for me. Perhaps, we have it already fixed and it's a good idea to check out the situation in the mainline branch together once again. 
The only weird thing I noticed is the negative `children_count` for most of the cases. Going to check it deeply

**Comment by paliarush** [comment]
@erikkubica you liked @rogyar 's comment, does it mean that you cannot reproduce the issue anymore?

**Comment by erikkubica** [comment]
@paliarush Yet I did not get time to do a clean install 2.3-baseline to test it one more time. On the original instance with updated GraphQL module it's still buggy. My like was just a expression that I have seen his comment and I thank to everyone trying to solve this problem

**Comment by paliarush** [comment]
@erikkubica thank you for clarification

**Comment by erikkubica** [comment]
@paliarush @rogyar I can confirm that after fresh installing the 2.3-baseline the bug is no longer present. Sorry for the long waiting, I had no time to play around with it. I am closing the issue for now. Thank you for all your time and work.
