### ISSUE TITLE
Extend GraphQL store config implementation

### ISSUE THREAD

**Issue by nuzil** [magento/graphql-ce#128]
For PWA frontend implementation we need to extend list of parameters which we need to ability to receive from Magento Configuration.

Base implementation: https://github.com/magento/graphql-ce/pull/126
PWA Requirements: https://github.com/magento-research/pwa-studio/issues/115

At this moment values we need are: 

### Content -> Design -> Configuration:
* HTML head Section
* Header Section
* Footer section
* Others are not really required at this moment.

### Stores -> Configuration
* Web -> Default Pages (current blocker, cause we need to know correct pages ID. Otherwise we have to hardcode them).

Catalog | Catalog -> Search Engine Optimization: Category URL Suffix

### Implementation

Will be nice to have possibility to define list of config parameters that user can request via GraphQL by using graphql/di.xml file. So developer could extend this list easily

### Result

By Using GraphQL query we can receive parameters described on this issue, list of variables will be based on di.xml configuration file

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/182
