### ISSUE TITLE
Retrieve Customer token

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#129]
As a Magento developer, I want to retrieve the customer token in GraphQL by providing customer email/password combination so that I can effectively authorize a customer and can grab account data. 

This should be similar to the `POST   /V1/integration/customer/token` REST endpoint and implemented in GraphQL.

Acceptance Criteria
- User can successfully retrieve a customer token entirely in GraphQL by providing a correct email/password combination
- In the case of incorrect credentials, an error message is displayed:
   - `The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.`
- Return type should be `String`
- Two arguments should be required: `email`: `String!` and `password`: `String!`
- mutation should be called `generateCustomerToken`

**Comment by naydav** [comment]
Merged with
https://github.com/magento/graphql-ce/pull/180
https://github.com/magento/graphql-ce/pull/184
