### ISSUE TITLE
GraphQL API returns rendered content for product

### ISSUE THREAD

**Issue by melnikovi** [magento/graphql-ce#134]
### Preconditions
1. Magento 2 Commerce 
2. GraphQL modules

### Description
There is a need to support retrieving rendered content for the fields that may contain WYSIWYG content via GraphQL API:
- rendered content (without Magento directives) 
- use `\Magento\Widget\Model\Template\Filter::filter`

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/140
