### ISSUE TITLE
Incorrect descriptions for two Customer attributes

### ISSUE THREAD

**Issue by keharper** [magento/graphql-ce#136]
In `app/code/Magento/CustomerGraphQl/etc/schema.graphqls`, the descriptions for `is_subscribed` and `addresses` are switched. 

### Preconditions

No

### Steps to reproduce

1. Navigate to `app/code/Magento/CustomerGraphQl/etc/schema.graphqls` and look at lines 22 and 23.

### Expected result

`is_subscribed` should have this description: "Indicates whether the customer is subscribed to the company's newsletter"

`addresses` should have this description: "An array containing the customer's shipping and billing addresses"

### Actual result

The descriptions are incorrect

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/138
