### ISSUE TITLE
[Cart Operations] Add simple product to Cart

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#141]
As a Magento developer, I need to manipulate the shopping cart via GraphQL so that I can build basic ecommerce experiences for shoppers on the front-end using only GraphQL.

GraphQL needs to provide sufficient mutations (ways to create/update/delete data) for a developer to build out the storefront checkout experience for a shopper.

**Use cases:**
- Both guest and registered shoppers can add simple products to cart

**Acceptance criteria:**
- Cart operations should be useable in both standard Cart and mini-cart
- GraphQL provides the following mutations:
  - `addCartItems`
- All product types are supported in a modular way (e.g. configurable-related schema and resolvers must be declared in `ConfigurableProductGraphQl` module and the rest of the system should still work if this module is disabled)
- Depending on token in `Authorization` header (if any), customer or guest service contract should be used
- Changes are covered with web API functional tests. See [\Magento\GraphQl\TestModule\GraphQlMutationTest::testMutation](https://github.com/magento/graphql-ce/blob/db3f2c73416c19f9cc13b1cbc48d504e843dc476/dev/tests/api-functional/testsuite/Magento/GraphQl/TestModule/GraphQlMutationTest.php#L15) as an example.

[**Proposed schema**](https://github.com/magento/architecture/pull/15/files)

Example of `typeResolver`: https://github.com/magento/graphql-ce/blob/34ed6d16576c8360af62218f50f4b91fb03338c5/app/code/Magento/CatalogGraphQl/etc/schema.graphqls#L247

**My Account area impacted:** 
- Cart
- Minicart

**Comment by roma-glushko** [comment]
Hi @paliarush @naydav , 
can you please take a look at my changes? I had to decouple resolvers cause they were not passed Travis complexity checking. However, I afraid it might contain design solutions now you probably don't want to see merged. 

Let me know if you any concerning about the current changes. I will change everything as soon as I can.
Thanks,
Roma.

**Comment by naydav** [comment]
Example of request:
```
mutation {
  addSimpleProductsToCart(
    input: {
      cart_id: "b96566a020b8797b7d806a948174275e", 
      cartItems: [
        {
          data: {
            sku: "product_dynamic_24494", 
            qty: 1
          }, 
          customizable_options: [
            {id: 5, value: "test"},
            {id: 6, value: "5"}
          ]
        }
      ]
    }
  ) {
    
    cart {
      items {
        id
        qty
        ... on SimpleCartItem {
          customizable_options {
            id
            label
            type
            is_required
            values {
              id
              label
              value
              price {
                type
                units
                value
              }
            }
          }
        }
        product {
          sku
          name
          image
          url_key
          categories {
            id
            name
          } 
          updated_at
          websites {
            name
          }
        }
      }
    }    
  }
}
```

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/170

**Comment by prabhakaran777** [comment]
![Screenshot from 2019-12-13 12-23-08](https://user-images.githubusercontent.com/49685489/70777370-9253db80-1da5-11ea-8118-af7cdf97ea00.png)
```
mutation {
  addSimpleProductsToCart(
    input: {
      cart_id: "XvbSgHh6RbXgElGAhLhGDeIFHu8rAXCZ"
      cart_items: [
        {
          data: {
            quantity: 1
            sku: "Product option values"
         
          }
          
          customizable_options:[
          {
            id:1
            value_string:"Second"	
            
          }
        ]
        }
      ]
    }
  ) {
    cart {
      items {
        id
        product {
          sku
          stock_status
        }
        ... on SimpleCartItem{
          id
        customizable_options{
        id
         values{
          value
          price{
            value
          }
        }
        }
                
        
         
      
        }
        quantity
      }
    }
  }
}
```


i had tried this way but error


```

{
  "errors": [
    {
      "message": "Could not add the product with SKU Product option values to the shopping cart: Some of the selected options are not currently available.",
      "category": "graphql-input",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addSimpleProductsToCart"
      ]
    }
  ],
  "data": {
    "addSimpleProductsToCart": null
  }
}
```


any one could help me plz...
