### ISSUE TITLE
[Checkout] Add grouped product to Cart

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#144]
As a Magento developer, I need to manipulate the shopping cart via GraphQL so that I can build basic ecommerce experiences for shoppers on the front-end using only GraphQL.

GraphQL needs to provide sufficient mutations (ways to create/update/delete data) for a developer to build out the storefront checkout experience for a shopper.

**Use cases:**
- Both guest and registered shoppers can add grouped product to cart

**Acceptance criteria:**
- Cart operations should be useable in both standard Cart and mini-cart
- GraphQL provides the following mutations:
  - `addCartItems`
- All product types are supported in a modular way (e.g. configurable-related schema and resolvers must be declared in `ConfigurableProductGraphQl` module and the rest of the system should still work if this module is disabled)
- Depending on token in `Authorization` header (if any), customer or guest service contract should be used
- Changes are covered with web API functional tests. See [\Magento\GraphQl\TestModule\GraphQlMutationTest::testMutation](https://github.com/magento/graphql-ce/blob/db3f2c73416c19f9cc13b1cbc48d504e843dc476/dev/tests/api-functional/testsuite/Magento/GraphQl/TestModule/GraphQlMutationTest.php#L15) as an example.

[**Proposed schema**](https://github.com/magento/architecture/pull/15/files)

**My Account area impacted:** 
- Cart
- Minicart

**Comment by lenaorobei** [comment]
As per additional investigation and conversation with PO it was decided that adding grouped product to cart scenarios can be covered using addSimpleProductsToCart mutation mutation.

DevDocs will be updated in order to reflect this data.
