### ISSUE TITLE
[Checkout] Add downloadable product to Cart

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#146]
As a Magento developer, I need to manipulate the shopping cart via GraphQL so that I can build basic ecommerce experiences for shoppers on the front-end using only GraphQL.

GraphQL needs to provide sufficient mutations (ways to create/update/delete data) for a developer to build out the storefront checkout experience for a shopper.

**Use cases:**
- Both guest and registered shoppers can add downloadable products to cart

**Acceptance criteria:**
- Cart operations should be useable in both standard Cart and mini-cart
- GraphQL provides the following mutations:
  - `addCartItems`
- All product types are supported in a modular way (e.g. configurable-related schema and resolvers must be declared in `ConfigurableProductGraphQl` module and the rest of the system should still work if this module is disabled)
- Depending on token in `Authorization` header (if any), customer or guest service contract should be used
- Changes are covered with web API functional tests. See [\Magento\GraphQl\TestModule\GraphQlMutationTest::testMutation](https://github.com/magento/graphql-ce/blob/db3f2c73416c19f9cc13b1cbc48d504e843dc476/dev/tests/api-functional/testsuite/Magento/GraphQl/TestModule/GraphQlMutationTest.php#L15) as an example.

[**Proposed schema**](https://github.com/magento/architecture/pull/15/files)

**My Account area impacted:** 
- Cart
- Minicart

**Comment by Neos2007** [comment]
@naydav, @nuzil  
Started working on this issue and have few questions (need advice). 
Already implemented logic for adding to cart simple products in module DownloadableGraphQl contain almost all needed logic which will fit for adding to cart downloadable products too except handling "links" parameters.

So I decided to reuse some existed graphql schema types and inputs and resolver with dependent  classes from QuoteGraphQL. 

I reuse `Magento\QuoteGraphQl\Model\Resolver\AddSimpleProductsToCart` and `Magento\QuoteGraphQl\Model\Cart\AddProductsToCart` classes using di virtual types.

So di.xml will look like this:

```<virtualType name="AddDownloadableProductsToCart" type="Magento\QuoteGraphQl\Model\Resolver\AddSimpleProductsToCart">
        <arguments>
            <argument name="addProductsToCart" xsi:type="object">Magento\DownloadableGraphQL\Model\Cart\AddProductsToCart</argument>
        </arguments>
    </virtualType>
    <virtualType name="Magento\DownloadableGraphQL\Model\Cart\AddProductsToCart" type="Magento\QuoteGraphQl\Model\Cart\AddProductsToCart">
        <arguments>
            <argument name="addProductToCart" xsi:type="object">Magento\DownloadableGraphQL\Model\Cart\AddDownloadableProductToCart</argument>
        </arguments>
    </virtualType>
```

One class which I plan to extend and customize is `Magento\QuoteGraphQl\Model\Cart\AddSimpleProductToCart` class which will be extended by  
`Magento\DownloadableGraphQL\Model\Cart\AddDownloadableProductToCart` one.

I plan to rewrite "execute" method.
But  `Magento\QuoteGraphQl\Model\Cart\AddSimpleProductToCart` contain lot of private methods which must be reused and I see not sense to re-declare them in my extended class.

So my question: Is it reasonable to change those methods type to protected.
Or even better to  modify "execute" method by adding dispatch event logic with `$buyRequest` and `$cartItemData` which will allow to modify `$buyRequest before Quote::addToCart` methods call?

Or maybe I chose bad approach for resolving this issue?

**Comment by naydav** [comment]
@Neos2007 
Generally, inheritance is a bad idea for code reusing
We can replace `AddSimpleProductToCart `  on some registry of processors
So we can extract the corresponding processor from the registry by product type

**Comment by atwixfirster** [comment]
**Pull request:** https://github.com/magento/graphql-ce/pull/412

Thank you!

**Comment by lenaorobei** [comment]
https://github.com/magento/graphql-ce/pull/412
