### ISSUE TITLE
Add support for named fragments

### ISSUE THREAD

**Issue by Serunde** [magento/graphql-ce#147]
The issue was originally reported as a bug in `CategoryTree` resolver, however support for named fragments have not been implemented or tested yet. Inline fragments should work for now and can be used as a workaround, until current issue is resolved.

Steps from the original ticket could be used as requirements for framework improvement:

### Preconditions

Magento 2.3 installed with sample data
Testing using GraphiQL

### Steps to reproduce

1. Create a fragment on `CategoryTree`
2. Reference the fragment in a category query

Query used: 
```
query ($categoryId: Int!) {
  category(id: $categoryId) {
    ...test
  }
}

fragment test on CategoryTree {
  id
  name
}
```

Variables: 
```
{
  "categoryId": 3
}
```
### Expected result
```
{
  "data": {
    "category": {
      "id": 3,
      "name": "Gear"
    }
  }
}
```

### Actual result
```
  "data": {
    "category": null
  }
```
This is preceded by an argument type discrepancy error:
```
{
  "errors": [
    {
      "debugMessage": "Argument 2 passed to Magento\\CatalogGraphQl\\Model\\Resolver\\Products\\DataProvider\\CategoryTree::joinAttributesRecursively() must be an instance of GraphQL\\Language\\AST\\FieldNode, instance of GraphQL\\Language\\AST\\FragmentSpreadNode given, called in /var/www/html/app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/CategoryTree.php on line 150",
```

Equivalent inline fragments will work, which seems to imply that `joinAttributesRecursively()` is only called when a fragment is referenced. Is this intentional or is my syntax incorrect for this scenario (how would I get it to pass a `FieldNode`)?
Additionally, similar basic fragments will resolve in the products schema.

**Comment by naydav** [comment]
@TomashKhamlai 
Please, verify this issue on last mainline

**Comment by TomashKhamlai** [comment]
Issue confirmed. Still reproducible.
```graphql
{
  "errors": [
    {
      "debugMessage": "Argument 2 passed to Magento\\CatalogGraphQl\\Model\\Resolver\\Products\\DataProvider\\CategoryTree::joinAttributesRecursively() must be an instance of GraphQL\\Language\\AST\\FieldNode, instance of GraphQL\\Language\\AST\\FragmentSpreadNode given, called in /var/www/html/graph-sd/app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/CategoryTree.php on line 144",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "category"
      ]
    }
  ],
  "data": {
    "category": null
  }
}
```
