### ISSUE TITLE
Revoke customer token

### ISSUE THREAD

**Issue by paliarush** [magento/graphql-ce#160]
As a Magento developer, I want to revoke the customer token in GraphQL by sending request as Authorized customer.

**Acceptance Criteria**

1. User can successfully revoke his own token entirely in GraphQL by sending request with `Authorization` header.
1. Return type should be `Boolean`
1. No arguments should be required
1. mutation should be called revokeCustomerToken
1. GraphQL tests are optional

**Comment by paliarush** [comment]
Related issue: https://github.com/magento/graphql-ce/issues/129

**Comment by ArturoI** [comment]
I have the issue almost done with funtional test created. It remain to configure my local to run the tests, to be sure that everything is ok. This week will be ready the PR. I will assign this ticket again to me if this is ok for you @naydav

**Comment by naydav** [comment]
I checked and rerun internal builds
All is good
https://github.com/magento/graphql-ce/pull/195
