### ISSUE TITLE
Show only active CMS Blocks

### ISSUE THREAD

**Issue by artKozynets** [magento/graphql-ce#176]
### Preconditions
1. Magento 2.3-develop + sample data (sample data not necessary)
2. Php 7.1
3. MariaDB 10.1.17

### Steps to reproduce
1. Checkout to branch 31-cms-page-graphql-support
Pull request https://github.com/magento/graphql-ce/pull/105
2. Disable some CMS block: MagentoAdmin > Content > Blocks > choose_your_block ->
Enable Block: NO -> Save
3. Run this GraphQL query:
```
{
  cmsBlocks (identifiers: ["disabled_cms_block", "enabled_cms_block"]){
    items{
      title
      identifier
      content
    }
  }
}
```

**disabled_cms_block:** identifier of the disabled cms_block
**enabled_cms_block:** identifier of the enabled cms_block

### Expected result

1. Get only cms_blocks with status: enabled.
```
{
  "data": {
    "cmsBlocks": {
      "items": [
        {
          "title": "Home banner 1"
        }
      ]
    }
  }
}
```

### Actual result

```
{
  "errors": [
    {
      "message": "No such entity.",
      "category": "graphql-no-such-entity",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "cmsBlocks"
      ]
    }
  ],
  "data": {
    "cmsBlocks": null
  }
}
```

**Visualization**

<img width="1124" alt="error" src="https://user-images.githubusercontent.com/22525219/45264989-43522480-b445-11e8-9776-0c66837349ea.png">

**Settings**

<img width="1325" alt="settings" src="https://user-images.githubusercontent.com/22525219/45264982-359c9f00-b445-11e8-94bd-57717b462677.png">

**Test**

With GraphQL query for one cms_block it works in a right way!

<img width="1125" alt="awesome" src="https://user-images.githubusercontent.com/22525219/45265117-e7889b00-b446-11e8-8e21-c3abd9bc454a.png">

<img width="1278" alt="awesome2" src="https://user-images.githubusercontent.com/22525219/45265140-1ef74780-b447-11e8-8961-290da58bb045.png">

**Comment by artKozynets** [comment]
Same behaviour in branch 2.3-develop

**Comment by artKozynets** [comment]
Same with NOT_EXISTING_ IDENTIFIRE

**Comment by naydav** [comment]
Result:

Request
```
{
  cmsBlocks (identifiers: ["disabled_block", "enabled_block"]){
    items{
      title
      identifier
      content
    }
  }
}
```

Response
```
{
  "errors": [
    {
      "message": "The CMS block with the \"disabled_block\" ID doesn't exist.",
      "category": "graphql-no-such-entity",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "cmsBlocks",
        "items",
        0
      ]
    }
  ],
  "data": {
    "cmsBlocks": {
      "items": [
        null,
        {
          "title": "enabled_block",
          "identifier": "enabled_block",
          "content": "<p>enabled_block enabled_block enabled_block</p>"
        }
      ]
    }
  }
}
```
