### ISSUE TITLE
Document client-side caching

### ISSUE THREAD

**Issue by paliarush** [magento/graphql-ce#18]
Examples of client-side caching with 3rd party libraries should be added to [Magento GraphQL dev docs](https://devdocs.magento.com/guides/v2.3/graphql/index.html).

**Comment by cherdman** [comment]
Ticket created for the PWA team to provide PWA client-side caching documentation:

https://app.zenhub.com/workspaces/pwa-studio-5b23bf79d195c635a1a218ce/issues/magento-research/pwa-studio/1137

**Comment by cherdman** [comment]
https://github.com/magento-research/pwa-studio/pull/1152/

**Comment by cherdman** [comment]
Closing this issue as the following have been merged and closed:

https://github.com/magento-research/pwa-studio/issues/1137
https://github.com/magento-research/pwa-studio/pull/1152
