### ISSUE TITLE
Add breadcrumbs support

### ISSUE THREAD

**Issue by paliarush** [magento/graphql-ce#19]
As a Magento developer, I want to access the parent and ancestors of the category object so that I can build breadcrumbs on the product page with one GraphQL request.

**Acceptance criteria:**
 1. Category level must be included with each category
 2. Changes are covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.

**Comment by naydav** [comment]
Merged with
https://github.com/magento/graphql-ce/pull/112
