### ISSUE TITLE
Products: access to related/up-sell/cross-sell product fields

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#198]
### Description
As a Magento developer, I want access to fields of related/up-sell/cross-sell products so I can fetch data for those secondary products in one call and render them on storefront. 

### Benefits
Developer productivity, request efficiency, being able to execute one call instead of several

### Acceptance criteria 
- GraphQL user can request the following fields for related/upsell/cross-sell product from original first-level products: 
   - Name
   - SKU
   - Regular and minimal price (full object)
   - Main image
   - url key
   - canonical url
- *Important*: implementation should make use of deferred field resolution in interest of performance (see media gallery implementation as reference)

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/371
