### ISSUE TITLE
Product Compare

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#200]
### Description
This is a stub feature to implement product compare on storefront using GraphQL

**Comment by AlexandrKozyr** [comment]
Under the issue scope will be done next :
1.Created ProductCompareGraphQl module with required functionality for:
1.1 adding product to compare (mutation)
1.2. removing product to compare (mutation)
1.3. receiving list of products SKUs for compare (query)
1.4. for now query and mutations will return the only list of product SKUs that will be comparing
1.5. adding additional using ProductInterface (final step);
2. Adding automated tests for the functionality above.

**Comment by AlexandrKozyr** [comment]
The issue is still in progress.
Found out that current functionality of the product compare uses the id of the product and not the SKU. So after consultation with @naydav we will use the array of ids for removing or adding mutations.

**Comment by AlexandrKozyr** [comment]
@naydav FYI 
During the working process found out that for identification of the client Magento 2 uses or customer (registered visitor) identification or visitor authentification. in the case of the customer, we can use provided by Customer Module token functionality (mutation generateCustomerToken etc). But for a visitor, there can be problems with identification. Coz for now it uses session mechanism only  (Customer/Model/Visitor.php public function initByRequest($observer)) and if the client system will not be able to provide this mechanism we will not be able to authenticate the person as the particular visitor. In result system will not be able to compare the products coz will not recognize the person.

**Comment by AlexandrKozyr** [comment]
@naydav 
added pull request with functionality (1 query and 2 mutation).
https://github.com/magento/graphql-ce/pull/253
web API tests will be added in another pull request by @NikZh

**Comment by AlexandrKozyr** [comment]
@naydav 
small update. our colleague @kisroman  will help us with this issue to be finished

**Comment by naydav** [comment]
> @naydav FYI
> During the working process found out that for identification of the client Magento 2 uses or customer (registered visitor) identification or visitor authentification. in the case of the customer, we can use provided by Customer Module token functionality (mutation generateCustomerToken etc). But for a visitor, there can be problems with identification. Coz for now it uses session mechanism only (Customer/Model/Visitor.php public function initByRequest($observer)) and if the client system will not be able to provide this mechanism we will not be able to authenticate the person as the particular visitor. In result system will not be able to compare the products coz will not recognize the person.

Need to create mapping between compare list id and some public hash in the same way like it was make for Qoute
