### ISSUE TITLE
Product Ratings and Reviews

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#201]
### Description
This is a stub feature to implement product ratings and reviews on storefront using GraphQL 

Use cases: 
- Query rating for a product (for product detail page, product listings pages, product widgets)
   - Querying all product reviews by the current registered shopper is described in https://github.com/magento/graphql-ce/issues/51
- Mutation to leave a product review by the current user

**Comment by sky-hub** [comment]
Consider this issue assigned to me. I have already implemented https://github.com/magento/graphql-ce/issues/51 and I will continue with this one.

**Comment by naydav** [comment]
Will be implemented in the scope of https://github.com/magento/graphql-ce/issues/201
