### ISSUE TITLE
Products: Email to a Friend

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#202]
### Description
This is a stub feature to implement "email to a friend" functionality for products on Storefront
![image](https://user-images.githubusercontent.com/18131925/46503447-75f6ff00-c7f0-11e8-8318-ec65cccc3e7b.png)
~~ ~~ ~~
![image](https://user-images.githubusercontent.com/18131925/46503424-64adf280-c7f0-11e8-9ffc-da76d7d7d908.png)

### Additional information
We can also think about making the "Share" functionality generic and then having several implementations for various sharing mediums in addition to email: Twitter, Facebook, SMS?, Pinterest, etc

**Comment by maile-it-solutions** [comment]
#squashtoberfest

**Comment by naydav** [comment]
Example of query:
```graphql
mutation {
    sendEmailToFriend(
        input: {
          product_id: 3	
          sender: {
            name: "Name"
            email: "e@mail.com"
           message: "Lorem Ipsum"
        }          
          recipients: [
              {
                  name: "Recipient Name 1"
                  email:"recipient1@mail.com"
               },
              {
                  name: "Recipient Name 2"
                  email:"recipient2@mail.com"
              }
          ]
        } 
    ) {
        sender {
            name
            email
            message
        }
        recipients {
            name
             email
        }
    }
}
```

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/226
