### ISSUE TITLE
Add category children depth parameter

### ISSUE THREAD

**Issue by paliarush** [magento/graphql-ce#21]
As a Magento developer, I want to control the depth of the returned children for the requested category so that my queries can be more performant.

**Acceptance criteria**

1. Depth = 0 returns all children (default)
2. Depth = 1 returns only immediate children
3. Depth = 2 returns only immediate children and their children; and so on
4. Children are returned in a flat list (depth can be determined by "level" field)
2. Changes are covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.

**Comment by dmytro-ch** [comment]
For now, the category children depth is being calculated recursively by ``\Magento\CatalogGraphQl\Model\Category\DepthCalculator``. So the resulting depth value is based on the specified children structure in request.

**Comment by paliarush** [comment]
Current issue becomes irrelevant after changes done in https://github.com/magento/graphql-ce/pull/102
