### ISSUE TITLE
Incorrect returned values of product_count

### ISSUE THREAD

**Issue by Serunde** [magento/graphql-ce#214]
### Preconditions

1. Using Magento 2.3
2. Luma sample data installed

### Steps to reproduce

1. Form a category query including the `product_count` field with a category id of 3 (gear)
2. Include an inner product query with the `total_count` field.

### Expected result

`product_count` matches the total number of items returned from the query. Should be the same number as `total_count` if the inner product query does not have filters.

### Actual result

![productcount](https://user-images.githubusercontent.com/17077852/46960544-a55d0580-d053-11e8-854a-c0850f5a5c2f.png)

### Additional Notes
Worth mentioning that the value of `product_count` here is the same as the highest id in the category, despite the gap of products between id 23 and 36.

**Comment by ronak2ram** [comment]
@Serunde 
I debug this issue and I found.

There is **product_count** show product's count which has a Visibility is **Catalog, Search** or **Not Visible Individually**
There is **total_count** show product's count which has a Visibility is **Catalog, Search**

And, Result items has products which has a Visibility is **Catalog, Search**

Maybe this help to mentor.

**Comment by Serunde** [comment]
@ronak2ram 
Thanks for looking into this! So then this is the intended behavior of `product_count`?

**Comment by misha-kotov** [comment]
@ronak2ram @Serunde 
Both fields should reflect products that have visibility set to `Catalog, Search` OR `Catalog`. Same should be reflected in the result set. 
This is because querying products in this way emulates user browsing products (as opposed to using search) and therefore products that would be reflected on storefront in this case should be returned by GraphQL.

**Comment by ronak2ram** [comment]
@Serunde Yes
@misha-kotov 
We want ***product_count*** and ***total_count*** both should be same which has a Visibility is ***Catalog, Search*** only right?

**Comment by misha-kotov** [comment]
@ronak2ram no, see my answer above. Products that are set to visibility `Catalog` should also be included.

**Comment by naydav** [comment]
@TomashKhamlai 
Please, verify issue

**Comment by TomashKhamlai** [comment]
#### Query:
```graphql
query category(
  $id: Int!
  $currentPage: Int!
  $pageSize: Int!
) {
  category(
    id: $id
  ) {
    name
    product_count
    products(
      currentPage: $currentPage
      pageSize: $pageSize
    ) {
      items {
        id
      }
      total_count
    }
  }
}
```

#### Variables:
```json
{
  "id": 3,
  "currentPage": 6,
  "pageSize": 6
}
```

#### Response:
```graphql
{
  "data": {
    "category": {
      "name": "Gear",
      "product_count": 34,
      "products": {
        "items": [
          {
            "id": 43
          },
          {
            "id": 44
          },
          {
            "id": 45
          },
          {
            "id": 52
          }
        ],
        "total_count": 34
      }
    }
  }
}
```
