### ISSUE TITLE
Total pages field returns null in category query

### ISSUE THREAD

**Issue by Serunde** [magento/graphql-ce#215]
### Preconditions

1. Using Magento 2.3
2. Luma sample data installed

### Steps to reproduce

1. Form a category query with an inner product query using the `page_info` field
2. Include `total_pages`

### Expected result

The returned value of `total_pages` should be equivalent to `Math.ceil([# of products] / [page size])`

### Actual result

![totalpagesnull](https://user-images.githubusercontent.com/17077852/46961402-8bbcbd80-d055-11e8-9bb4-87ef62bab4be.png)

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/219/files
