### ISSUE TITLE
[GraphQL caching] Add support for queries via HTTP GET

### ISSUE THREAD

**Issue by paliarush** [magento/graphql-ce#229]
Based on the [prototype](https://github.com/magento/graphql-ce/issues/17) and this [commit](https://github.com/magento/graphql-ce/commit/c8d33d0d4b7af2f6c4ab3f6913cba375d63b7ee5) specifically, add support for GraphQL queries via HTTP GET. Note that GraphQL mutations must still only be supported via HTTP POST.

Changes must be covered with GraphQL functional tests.
(This requires changes to the testing framework, which only supports post.)

**Comment by pcvonz** [comment]
Small note: Adding the ability to use `GET` would be great for caching client side via the Cache Storage API. 

More info in this [issue](https://github.com/GoogleChrome/workbox/issues/1620) and [this issue](https://github.com/GoogleChrome/workbox/issues/1691#issuecomment-428308595).

I'm currently working on caching for the Venia concept and the lack of this functionality has been one of the hurdles for a smooth implementation.
