### ISSUE TITLE
Return product stock data

### ISSUE THREAD

**Issue by paliarush** [magento/graphql-ce#23]
As a Magento developer, I want to access relevant stock data with products in one query so that I can render related data efficiently and correctly on storefront. 

**Use cases**
- Distinguish between "in-stock" and "out-of-stock" products on storefront (if "display out-of-stock products = Yes)
- Show "Only X Left" or "Low Stock" on PDP or PLP when the product's stock is below the configured threshold (Catalog > Inventory > Stock Options)

**Acceptance criteria**
1. A dedicated field on product that designates if the product is in stock or not
1. A dedicated field on product that designates if it's below the configured threshold and how much stock is left (if configured)
2. Changes are covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/166
