### ISSUE TITLE
GraphQL tools cannot perform "standard introspection query" in production mode

### ISSUE THREAD

**Issue by zetlen** [magento/graphql-ce#232]
### Summary (*)
GraphQL tools for query validation and schema discovery rely on introspection features. While some tools perform many types of introspection query, or add introspection fields to arbitrary queries, the vast majority of tools perform a single, invariant [schema introspection](https://facebook.github.io/graphql/June2018/#sec-Schema-Introspection) query, described in the [reference implementation](https://graphql.org/graphql-js/utilities/#introspectionquery) as sufficient to download the entire type system.

All these tools utilize the [same introspection query](https://github.com/graphql/graphql-js/blob/master/src/utilities/introspectionQuery.js#L21-L111):
 - [GraphiQL](https://github.com/graphql/graphiql/blob/master/src/utility/introspectionQueries.js#L8)
 - [GraphQL Language Service](https://github.com/jimkyndemeyer/js-graphql-language-service/blob/master/src/project.js#L14), used by the PHPStorm / WebStorm GraphQL Plugin
 - [GraphQL Playground](https://github.com/prisma/graphql-playground/blob/master/packages/graphql-playground-react/src/components/Playground/SchemaFetcher.ts#L1), used in the PWA Studio Dev Server

However, Production instances of Magento 2.3 do not allow any introspection, including the standard query. This disables the tools for any user who does not have access to an instance of Magento 2 in developer mode. It's an obstacle to usability by new developers and community developers who are reliant on cloud instances.

### Examples (*)

Most public GraphQL APIs I could find permit the use of this standard introspection query:
- https://graphql.brandfolder.com/
- https://developer.github.com/v4/explorer/ (for logged-in users)
- https://developers.facebook.com/docs/graph-api/explorer/ (for logged-in developers)
- https://help.shopify.com/en/api/custom-storefronts/storefront-api/graphql-explorer

Production instances of Magento 2.3 return an error when running this query.

### Proposed solution
The standard introspection query is invariant, so it should be easy to cache its results. The GraphQL schema can only change when a new module is enabled or disabled, or when a new deploy occurs. That might require an on-demand refresh of the introspection query result, but it's still very safe to cache. Arbitrary introspection can still be disabled in production--but this common, standard query should be supported so that common, popular tools can download the schema and docs.

**Comment by real34** [comment]
This is also an important feature to support to allow remote systems to do schema stitching with Magento’s schema (see introspection query used by GraphQL Tools: https://github.com/apollographql/graphql-tools/blob/dacfd83566b6d8a9bee61ee1b5cda373b2b531a7/src/stitching/introspectSchema.ts#L2).

**Comment by paliarush** [comment]
When we enable introspection by default, there should be an option for system integrator to disable it if not needed to reduce security risks.

If not possible to restrict production introspection to the "standard query" only, it should be ok to disable introspection restrictions completely since we have query complexity and nesting level limiting in place.
