### ISSUE TITLE
Configurable Products counted but not retrieved in GraphQL (works with REST endpoint)

### ISSUE THREAD

**Issue by koen-dev** [magento/graphql-ce#238]
### Preconditions (*)

1. Magento Commerce 2.3.0 beta32
2. Custom instance with custom attributes and attribute sets

**Attributes used:**
* Growth method: Dropdown
* Height: Dropdown

### Steps to reproduce (*)

1. Create Product (Required fields + Categories)
2. Create Configurations for Product
3. Select Custom Attributes for Configurations
4. Select Custom Attributes Values
5. Skipped image uploading
6. Enter price for each configuration
7. Enter quantity for each configuration
8. Generate Products
9. Retrieve Category with products using GraphQL
```
{
  category(id: 5) {
    product_count
    products {
      items {
        name
      }
    }
  }
}
```

### Expected result (*)

1. Category with products as name and product_count
```
{
  "data": {
    "category": {
      "product_count": 1,
      "products": {
        "items": [
          {
            "name": "Buxushaag kant-en-klaar"
          }
        ]
      }
    }
  }
}
```

### Actual result (*)

1. Category with product_count matching Magento admin but without products
```
{
  "data": {
    "category": {
      "product_count": 1,
      "products": {
        "items": []
      }
    }
  }
}
```

### Extra information
This isn't only related to **CategoryTree** it also happens with **Products**.
When retrieving the product using the `REST API` it works as expected.

**Comment by rogyar** [comment]
Please, doublecheck that at least one simple product is in stock and has qty greater than zero. 
This issue appears when the product is out of stock. The products count has a positive value but no products are on the list

**Comment by koen-dev** [comment]
@rogyar I can confirm this has been resolved by adding quantity to everything.

**Comment by rogyar** [comment]
Also, this behavior is not the final one. 
The product count value has been adjusted to reflect the fetched products number in the following PR

https://github.com/magento/graphql-ce/pull/243
