### ISSUE TITLE
[BugFix] Fix resolving of image placeholder for Product without images

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#239]
### Steps to reproduce

1. Create Product without images
2. Perform query
```
{
  products (search: "simple-495") {
    items {
      small_image {
        url
      }
    }
  }
}
```

### Actual result:
```
 "url": "http://graphql.local/static/version1538424577/graphql/_view/en_US/Magento_Catalog/images/product/placeholder/small_image.jpg"
```

### Expected result:
```
 "url": "http://graphql.local/static/version1538424577/frontend/Magento/luma/en_US/Magento_Catalog/images/product/placeholder/small_image.jpg"
```

Problem is related to wrong area
Also, need to finish `\Magento\GraphQl\Catalog\ProductImageTest::testProductWithoutBaseImage`

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/364

**Comment by bchatard** [comment]
@naydav I test the patch in the PR #364 and the issue is still present.

The `Magento\CatalogGraphQl\Model\Resolver\Products\DataProvider\Image\Placeholder\Theme` class is no more used in the merged version, while it is this class that seemed to make the correction
