### ISSUE TITLE
Return resized image paths for products

### ISSUE THREAD

**Issue by paliarush** [magento/graphql-ce#24]
As a Magento developer, I need GraphQL API to return resized image paths so that I can render storefront experiences with correctly sized images.  

**Acceptance Criteria:**
1. GraphQL returns original image paths
1. GraphQL returns resized image paths if the images have been resized
2. Changes are covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.

**Comment by misha-kotov** [comment]
Duplicate of https://github.com/magento/graphql-ce/issues/4
