### ISSUE TITLE
[My Account] Create customer account

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#248]
### Description (*)

As a Magento developer, I need the ability to create customer accounts through GraphQL so that I can create basic ecommerce experiences on my site. 

### Expected behavior (*)

Need a GraphQL mutation that will create a customer account with provided information

**Comment by novikor** [comment]
@misha-kotov, there is a quick question.
What behaviour should be if you try to create a customer which already exists?

**Comment by novikor** [comment]
Hi, @misha-kotov .

I suggest to return something like that:
```
type CreateCustomerOutput {
    status: Bool!
    message: String
}
```
Status and message which is optional (for cases when customer creation failed).

As for me, this idea sounds logically, but I feel there is a way to improve this.
Do you have any ideas?
Thank you for your time

**Comment by novikor** [comment]
Pull request: #254

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/254
