### ISSUE TITLE
Hide product attributes not intended for storefront

### ISSUE THREAD

**Issue by paliarush** [magento/graphql-ce#25]
In Admin, if all of the following product attribute storefront properties are set to No, then it should be filtered out (not exposed by GraphQL): 
- Comparable on Storefront
- Use in Layered Navigation
- Use in Search Results Layered Navigation
- Visible on Catalog Pages on Storefront
- Used in Product Listing
- Used for Sorting in Product Listing

Otherwise (if any of the above are Yes), attribute values and attribute metadata should be accessible in GraphQL

Changes should be covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/103
