### ISSUE TITLE
[BugFix] Configurable Options Label doesn't return the Store View Label

### ISSUE THREAD

**Issue by koen-dev** [magento/graphql-ce#250]
### Preconditions (*)

1. Magento ver. 2.3.0-beta32

### Steps to reproduce (*)

1. Have multiple Store Views (for example: _Dutch_ and _German_)
2. Create an Attribute with a default label (for example: _Growth method_)
3. Enter different labels for your store view under Manage Labels (for example: _Kweekwijze_ and _Züchtungsmethode_)
4. Fetch a Configurable Product that uses the attribute as a configurable option (to get data for a different store view send the header `store` with your store view code)
![image](https://user-images.githubusercontent.com/5583604/48564089-077c8500-e8f6-11e8-9537-4c6491d6477f.png)
![image](https://user-images.githubusercontent.com/5583604/48564107-1105ed00-e8f6-11e8-8ba1-b7b7487c98aa.png)
```gql
{
  products(filter:{
    url_key: {
      eq: "test-configurable"
    }
  }) {
    items {
      __typename
      ...on ConfigurableProduct {
        configurable_options {
          id
          label
        }
      }
    }
  }
}
```

### Expected result (*)

1.
```json
{
  "data": {
    "products": {
      "items": [
        {
          "__typename": "ConfigurableProduct",
          "configurable_options": [
            {
              "id": 3,
              "label": "Kweekwijze"
            }
          ]
        }
      ]
    }
  }
}
```

### Actual result (*)

1.
```json
{
  "data": {
    "products": {
      "items": [
        {
          "__typename": "ConfigurableProduct",
          "configurable_options": [
            {
              "id": 3,
              "label": "Growth method"
            }
          ]
        }
      ]
    }
  }
}
```

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/346
