### ISSUE TITLE
Support for MSI

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#251]
### Description (*)

As a Magento developer, I want to make sure that the product inventory data in GraphQL is coming from MSI and not the legacy CatalogInventory so that my application is future-proof. 

### Expected behavior (*)

Impacted fields: 
- stock_status
- only_x_left_in_stock
- (check for others)

### Benefits

- Not using an old implementation of inventory

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/2124
