### ISSUE TITLE
GraphQL not working with GET

### ISSUE THREAD

**Issue by omiroshnichenko** [magento/graphql-ce#269]
Original issue https://github.com/magento/magento2/issues/19534
### Preconditions (*)
1. Magento 2.3.0
2. Headers (accept + content-type) set to JSON
3. GET request

### Steps to reproduce (*)
1. Visit $url/graphql with GraphiQL or Postman

### Expected result (*)
1. Get Graphql response

### Actual result (*)
1. Internal server error

**Comment by danielrenaud** [comment]
This has been resolved by #229. GraphQl queries can now be sent via HTTP GET. Mutations, must be made via POST.
