### ISSUE TITLE
[My Account] Add support of Customer attributes

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#271]
AC: 
- Validation should be based on attributes(EAV) rules (for details see eav_attribute table)
Now validation of Customer address data is hardcoded in 
`\Magento\CustomerGraphQl\Model\Customer\UpdateCustomerData::execute`
- Support for a case when an attribute is required and value is `0`(zero)
- Only related to Frontend attributes could be loaded/created/updated
- Possibility to update partial data
- Functionality is covered by API-function tests

**Comment by naydav** [comment]
Hello @furseyev 
Are you still working on the task?

**Comment by furseyev** [comment]
Hell @naydav ,

I've done the implementation in the https://github.com/magento/graphql-ce/tree/feature/271-Customer-Attributes-Support branch and needed only to add api functional tests for those. 

However, merging the latest changes from 2.3-develop shows a merge conflict - one of the models I've changed is already removed, so need to figure that out and re-do the solution.

Thanks!

**Comment by furseyev** [comment]
Hello @naydav ,

Any updates on this one? PR was created 11 days ago: https://github.com/magento/graphql-ce/pull/489
This comment is just for bumping task up. Please let me know if some labels/etc are missing.

Thanks!

**Comment by TomashKhamlai** [comment]
@naydav, please check this information and clarify requirements if needed.

Preconditions:
Custom Module that extends Customers attributes
OR
Magento EE (Customer attributes can be configured out of the box)

Steps:
1. Create attribute (Magento EE)
 - **Default Label** and **Attribute Code**: `a_experimental_field`
 - **Input Type**: `Text Field`
 - **Values Required**: `Yes`
 - **Input Validation**: `Length Only`
 - **Minimum Text Length**: `3`
 - **Maximum Text Length**: `65`
 - **Show on Storefront**: `Yes`
 - **Sort Order**: `0`
 - **Forms to Use In**: `Customer Registration` and `Customer Account Edit`
2. Save attribute and verify that attribute was added to specified forms. Perform reindex and flush cache in case you are in production mode and verify again.
3. First try this way:
```graphql
mutation {
  createCustomer(
    input: {
      firstname: "User"
      lastname: "Attributed"
      email: "user@email.com"
      password: "123123qA"
      a_experimental_field: "abcdefghe"
    }
  ) {
    customer {
      firstname
      lastname
      email
    }
  }
}
```

and get this

```graphql
{
  "errors": [
    {
      "message": "Field \"a_experimental_field\" is not defined by type CustomerInput.",
      "category": "graphql",
      "locations": [
        {
          "line": 2,
          "column": 125
        }
      ]
    }
  ]
}
```
4. Then try this way
```graphql
mutation {
  createCustomer(
    input: {
      firstname: "User"
      lastname: "Attributed"
      email: "user@email.com"
      password: "123123qA"
    }
  ) {
    customer {
      firstname
      lastname
      email
    }
  }
}
```

and get next error in **Network** tab of **Electron Dev Tools** (Chrome Dev Tools) 
```html
{"errors":[{"debugMessage":"Argument 2 passed to Magento\\Eav\\Model\\Attribute\\Data\\Text::validateLength() must be of the type string, null given, called in \/shared\/httpd\/graphql-ee\/graphql-ee\/app\/code\/Magento\/Eav\/Model\/Attribute\/Data\/Text.php on line 80","message":"Internal server error","category":"internal","locations":[{"line":2,"column":3}],"path":["createCustomer"]}],"data":{"createCustomer":null}}<br />
<b>Fatal error</b>:  Uncaught Exception: User Error: Some transactions have not been committed or rolled back in /shared/httpd/graphql-ee/graphql-ee/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php on line 3980 in /shared/httpd/graphql-ee/graphql-ee/lib/internal/Magento/Framework/App/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler-&gt;handler(256, 'Some transactio...', '/shared/httpd/g...', 3980, Array)
#1 /shared/httpd/graphql-ee/graphql-ee/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(3980): trigger_error('Some transactio...', 256)
#2 [internal function]: Magento\Framework\DB\Adapter\Pdo\Mysql-&gt;__destruct()
#3 {main}
  thrown in <b>/shared/httpd/graphql-ee/graphql-ee/lib/internal/Magento/Framework/App/ErrorHandler.php</b> on line <b>61</b><br />
```

![image](https://user-images.githubusercontent.com/11827230/58616337-19d47400-82c6-11e9-81d4-a9d824d93864.png)

**Comment by naydav** [comment]
Looks like we need to add attributes dynamically

Example
`<virtualType name="Magento\Framework\GraphQlSchemaStitching\Reader" type="Magento\Framework\GraphQlSchemaStitching\Common\Reader">`

**Comment by naydav** [comment]
My proposal is split functionality in two PR
First (already created by @furseyev) - with attributes which were added during installation
Second - with a possibility to add attributes dynamically via admin panel (example in a comment above)

 @TomashKhamlai please confirm that functionality (first PR) is valid for already existent attributes
Thanks
