### ISSUE TITLE
[UrlResolver] Implement logic of  Category Canonical url resolving 

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#274]
Scheme example:

```
type EntityUrl {
    entity_id: Int @doc(description: "The ID assigned to the object associated with the specified url. This could be a product ID, category ID, or page ID.")
    entity_type: UrlRewriteEntityTypeEnum @doc(description: "One of PRODUCT, CATEGORY, or CMS_PAGE.")
    url: Url @doc(description: "TODO")
}

type Url {
    system: String @doc(description: "Target path.")
    canonical: String @doc(description: "The canonical absolute URL. If the specified  url is a redirect, the query returns the redirected URL, not the original.")
}
```

The same logic is used for generation `<link  rel="canonical" href="{{ some url }}" />` on Category front page

For details of current implementation see:
`\Magento\Catalog\Block\Category\View::_prepareLayout`
`\Magento\Catalog\Model\Category::getUrl`

AC:
- Resolve canonical url by entity `system path`
Request:
```
{
  urlResolver(url:"catalog/category/view/id/28")
  {
    url {
      canonical
      system
    }
  }
}
```
Response:
```
{
  "data": {
    "urlResolver": {
      "url": {
        "canonical": "http://graphql.local/women/bottoms-women/pants-women.html"
        "system": "catalog/category/view/id/28"
      }
    }
  }
}
```
- Resolve canonical url by Url Rewrite `request_path` (see `rl_rewrite` DB table)
Request:
```
{
  urlResolver(url:"pants-women.html")
  {
    url {
      canonical
      system
    }
  }
}
```
Response:
```
{
  "data": {
    "urlResolver": {
      "url": {
        "canonical": "http://graphql.local/women/bottoms-women/pants-women.html"
        "system": "catalog/category/view/id/28"
      }
    }
  }
}
```

- Resolve canonical url by Url Rewrite `request path` if it is redirect to another Url Rewrite `request path` (see `url_rewrite` DB table)
If the specified  url is a redirect, the query returns the redirected URL, not the original.

Given: 
![image](https://user-images.githubusercontent.com/18131925/49902341-49cbb000-fe29-11e8-94c7-a6389849a569.png)

Request:
```
{
  urlResolver(url:"mk.html")
  {
    url {
      canonical
      system
    }
  }
}
```
Response:
```
{
  "data": {
    "urlResolver": {
      "url": {
        "canonical": "http://graphql.local/women/bottoms-women/pants-women.html"
        "system": "catalog/category/view/id/28"
      }
    }
  }
}
```

- Resolve canonical url by Url Rewrite `request path` if Url Rewrite is created for another store (see `url_rewrite` DB table)
```
{
  urlResolver(url:"url-created-for-some-store-view.html")
  {
    url {
      canonical
    }
  }
}
```
Response:
```
{
  "data": {
    "urlResolver": {
      "url": {
        "canonical": "http://graphql.local/index.php/canonical-url-for-current-store-view.html"
      }
    }
  }
}
```
- API functional tests MUST cover all of described cases

**Comment by misha-kotov** [comment]
I updated your examples above. The only one I'm not 100% sure about is the last one. 
We likely need to go through this exercise for products and CMS pages too.
