### ISSUE TITLE
[Shipping methods] Support of UPS shipping method

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#281]
Need to cover `UPS shipping method` functionality with API-functional tests.
Functionality should be fixed if needed.

Query scheme: `app/code/Magento/QuoteGraphQl/etc/schema.graphqls`

Testcases:
```
\Magento\GraphQl\Ups\SetUpsShippingMethodsOnCartTest
```
Don't forget to enable method in a fixture and disable in rollback fixture.

Example: `\Magento\GraphQl\OfflineShipping\SetOfflineShippingMethodsOnCartTest`

**Additionally**: Check do we need additional data or carrier code and method code will be enough

**Comment by atwixfirster** [comment]
**Pull request:** https://github.com/magento/graphql-ce/pull/505

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/505
