### ISSUE TITLE
[Shipping methods] Support of USPS shipping method

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#282]
Need to cover `USPS shipping method` functionality with API-functional tests.
Functionality should be fixed if needed.

Query scheme: `app/code/Magento/QuoteGraphQl/etc/schema.graphqls`

Testcases:
```
\Magento\GraphQl\Usps\SetUspsShippingMethodsOnCartTest
```
Don't forget to enable method in a fixture and disable in rollback fixture.

Example: `\Magento\GraphQl\OfflineShipping\SetOfflineShippingMethodsOnCartTest`

**Additionally**: Check do we need additional data or carrier code and method code will be enough

**Comment by atwixfirster** [comment]
@naydav , could you please assist here?

**USPS module** requires "User ID" and "Password". Does Magento have a test USPS account for such purpose?

Thank you!

CC: @rogyar @sergiy-v

**Comment by atwixfirster** [comment]
**Pull request:** https://github.com/magento/graphql-ce/pull/537

Thank you!
