### ISSUE TITLE
[Shipping methods] Support of DHL shipping method

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#284]
Need to cover `DHL shipping method` functionality with API-functional tests.
Functionality should be fixed if needed.

Query scheme: `app/code/Magento/QuoteGraphQl/etc/schema.graphqls`

Testcases:
```
\Magento\GraphQl\Dhl\SetDhlShippingMethodsOnCartTest
```
Don't forget to enable method in a fixture and disable in rollback fixture.

Example: `\Magento\GraphQl\OfflineShipping\SetOfflineShippingMethodsOnCartTest`

**Additionally**: Check do we need additional data or carrier code and method code will be enough

**Comment by AlexandrKozyr** [comment]
will check this issue out.

**Comment by naydav** [comment]
@AlexandrKozyr 
Pay attention, `@dataProvider` should be used for checking all of the possible methods
like https://github.com/magento/graphql-ce/pull/541/files#diff-b0da28aee0b2765cdc18c67f584b3a2aR173 (PR is not finished)
