### ISSUE TITLE
[Payment methods] Support of "Authorize.net Direct Post" payment method

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#291]
TBD

**Comment by avattam06** [comment]
Directpost was deprecated in magento in 2.3.1 and will be removed from authorize.net for everyone supposedly later this year. https://support.magento.com/hc/en-us/articles/360024368392-Update-Authorize-Net-Direct-Post-from-MD5-to-SHA-512. So changing to Authornize.net with Accept.js and Accept.js module does not cover vault integration
