### ISSUE TITLE
[Payment Methods] Schema proposal for Cart

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#300]
As a Magento developer, I need to create a base schema for managing payment methods on cart. 

Acceptance criteria
- Schema supports user adding a payment method to cart
- Schema supports user replacing the previously set payment method on cart

Assumptions
- User cannot remove a payment method from cart once it is set (can only set a different one)

**Comment by naydav** [comment]
Result is
https://github.com/magento/graphql-ce/wiki/Checkout-workflow
