### ISSUE TITLE
[Checkout] Checkout Agreements

### ISSUE THREAD

**Issue by gil--** [magento/graphql-ce#309]
### Description (*)
CheckoutAgreementsGraphQl module for [CheckoutAgreements](https://github.com/magento/graphql-ce/tree/2.3-develop/app/code/Magento/CheckoutAgreements)

### Expected behavior (*)
Should be able to query checkout agreements and return appropriate fields.

### Benefits
Will allow checkout experiences that depend on agreements functionality to be built.

### Additional information
Tests should be similar to https://github.com/magento/magento2/tree/2.3-develop/dev/tests/integration/testsuite/Magento/CheckoutAgreements/_files

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/504
