### ISSUE TITLE
Handle overlap in GraphQL query name

### ISSUE THREAD

**Issue by brendanfalkowski** [magento/graphql-ce#316]
### Summary

I created two Magento modules with GraphQL schemas that were identical, and tried to query to see what happened.

### Outcome

The PWA build found both schemas to be valid.

The module that came alphabetically last is the one that responded to my query.

### Proposed solution

The PWA build could warn if multiple registered module provide a GraphQL query of the same name.

This might be intentional so modules can override one another (I'm a frontend developer) but I expected a warning from the system.

I'm not sure what the mechanism is for defining priority.

**Comment by naydav** [comment]
Hello @brendanfalkowski,
For specifying an order of module loading you should use directive `<sequence>` in `module.xml`

`modules can override one another`
The main idea is providing a possibility to extend or override scheme(or any config) of one module in another

More details you can find in the documentation
https://devdocs.magento.com/guides/v2.3/extension-dev-guide/build/module-load-order.html

Feel free to re-open if you will have additional questions (or ask in #graphql Slack channel for quicker feedback).

Thanks
