### ISSUE TITLE
[ThemeGraphql] Getting values from StoreConfig is not possible

### ISSUE THREAD

**Issue by vasilii-b** [magento/graphql-ce#317]
### Preconditions (*)
1. Magento 2.3-develop
2. Filled in fields for `Html Head`, `Header` and `Footer` sections under `Content -> Design -> Configuration ->` *one selected row as per your wish*
![image](https://user-images.githubusercontent.com/13456702/51521675-f721e280-1e2f-11e9-94a1-0ce02798b7d6.png)

### Steps to reproduce (*)
1. Open GraphiQL or any other tool to make queries to Magento store
2. Create a query to get some store configuration information (available from `app/code/Magento/ThemeGraphQl/etc/schema.graphqls`). The following is an example:

```gql
{
  storeConfig {
    head_shortcut_icon,
    default_title,
    title_prefix,
    title_suffix,
    default_description,
    default_keywords,
    head_includes,
    demonotice,
    header_logo_src,
    logo_width,
    logo_height,
    logo_alt,
    welcome,
    absolute_footer,
    copyright
  }
}
```

### Expected result (*)
Returned values reflect values added in the admin area.
![image](https://user-images.githubusercontent.com/13456702/51521833-70213a00-1e30-11e9-82e9-ee01064c3565.png)

### Actual result (*)
For requested fields, you've got `null`s as response:
![image](https://user-images.githubusercontent.com/13456702/51522030-eb82eb80-1e30-11e9-994e-bfcd872b0541.png)

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/318
