### ISSUE TITLE
Unable to pass enum value as argument in GraphQL query

### ISSUE THREAD

**Issue by kouma** [magento/graphql-ce#325]
Hello there, 

When you pass enum values as argument in your GraphQL queries, the validation fails. To reproduce this bug, let's use the super simple `SortEnum` that contains only 2 attributes, `ASC` and `DESC` :

```text
enum SortEnum @doc(description: "This enumeration indicates whether to return results in ascending or descending order") {
    ASC
    DESC
}
```
We'll use it on the `products` query to sort the paginated result.

### Preconditions (*)

1. Magento 2.3
2. graphql-php 0.13.0

### Steps to reproduce (*)

1. Install GraphiQL extension for Chrome [here](https://chrome.google.com/webstore/detail/chromeiql/fkkiamalmpiidkljmicmjfbieiclmeij)
2. Set the endpoint with your site uri  : `https://yoursite.com/graphql`
3. In the left column, type this query :

```text
query Products(
  $price: String,
  $sort: SortEnum = DESC
) {
    products (
        filter: {
          price: {
            gt: $price
          }
        },
        sort: {
          name: $sort
        }
    ) {
      items {
        id
        name
      }
    }
  }
```
Type these variables in the "Query Variables" block on the bottom left :
```json
{
  "sort": "ASC",
  "price": "1"
}
```
...and hit the big upper button to perform the request.

### Expected result (*)

1. Normally in GraphQL, you are able to pass enum types as variables. The result should be a paginated list of products sorted by name ASC. 

### Actual result (*)

1. The request doesn't perform well : 

![enum_issue](https://user-images.githubusercontent.com/1068013/51687453-d05fd980-1ff2-11e9-874e-d8e028e8e70e.png)

```json
{
  "errors": [
    {
      "message": "Variable \"$sort\" of type \"SortEnum\" used in position expecting type \"SortEnum\".",
      "category": "graphql",
      "locations": [
        {
          "line": 3,
          "column": 3
        },
        {
          "line": 12,
          "column": 17
        }
      ]
    }
  ]
}
```
I don't know if it's a Magento or a graphql-php related error. The error seems to be caused by the graphql-php validation process, the class `GraphQL\Validator\Rules\VariablesInAllowedPosition` is causing the error. 

I tested with custom enums and the issue is the same. The only way to succeed is to change the type `SortEnum` to `String` and pass value as a string, but it's not a proper solution at all.
Actually this is very annoying because you can't use enum types as arguments for queries.

**Comment by naydav** [comment]
Fixed and merged in
https://github.com/magento/graphql-ce/pull/259

**Comment by kouma** [comment]
Hey thank you for your time !
