### ISSUE TITLE
When trying to add Configurable product to Cart the message "Product \"configurable\" type is not supported" received

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#348]
### Preconditions (*)

1. #224 is merged or #142 is fixed (if not need to work create a  new branch based on `142_Add_configurable_product_to_Cart`, not `2.3-develop`)

### Steps to reproduce (*)

1. Create Configurable Product with
Name & SKU: conf
Weight: 1
Price: 1
Variations:
- sku: conf-white, qty: 12, price: 10
- sku: conf-black, qty: 12, price: 10
2. Perform GraphQL query:
```
mutation {
  addConfigurableProductsToCart(
    input: {
      cart_id: "gbK3g1pcEiyd39h2clKomLU6qsyFLAVT"
      cartItems: [
        {
          variant_sku: "conf-black"
          data: {
            qty: 1
            sku: "conf-black"
          }
        }
        {
          variant_sku: "conf-white"
          data: {
            qty: 1
            sku: "conf-white"
          }
        }
      ]
    }
  ) {
    cart {
      items {
        id
        qty
        product {
          name
          sku
        }
        ... on ConfigurableCartItem {
          configurable_options {
            option_label
          }
        }
    }
  }
  }
}
```

### Expected result (*)

1. "Product \"configurable\" type is not supported"

### Actual result (*)

1. 
[stacktrace.json.txt](https://github.com/magento/graphql-ce/files/2836981/stacktrace.json.txt)

**Comment by XxXgeoXxX** [comment]
this issue related to https://github.com/magento/graphql-ce/issues/380.
And fix from https://github.com/magento/graphql-ce/pull/383 will help to solve this problem.
