### ISSUE TITLE
"The requested qty is not available" should be received instead of Internal server error

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#350]
### Preconditions (*)

1. #224 or #320  is merged or #142 is fixed
2. Default mode or 
```
php bin/magento deploy:mode:set default
rm -rf generated/* var/*
```

### Steps to reproduce (*)

1. Create Configurable Product with
Name & SKU: conf
Weight: 1
Price: 1
Variations:
- sku: conf-white, qty: 12, price: 10
- sku: conf-black, qty: 12, price: 10
2. Perform GraphQL query:
```
mutation {
  addConfigurableProductsToCart(
    input: {
      cart_id: "gbK3g1pcEiyd39h2clKomLU6qsyFLAVT"
      cartItems: [
        {
          variant_sku: "conf-black"
          data: {
            qty: 13
            sku: "conf-black"
          }
        }
        {
          variant_sku: "conf-white"
          data: {
            qty: 13
            sku: "conf-white"
          }
        }
      ]
    }
  ) {
    cart {
      items {
        id
        qty
        product {
          name
          sku
        }
      }
    }
  }
}

  
```

### Expected result (*)

1. "message": "The requested qty is not available",

### Actual result (*)

1. "message": "Internal server error",

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/368
