### ISSUE TITLE
When maxSaleQty is set and qty is more than maxSaleQty the "The most you may purchase is %1." message should be sent instead of "Internal server error"

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#354]
[Test Execution](https://app.hiptest.com/projects/114163/test-runs/232368/folder-snapshots/1925571/scenario-snapshots/7442473/test-snapshots/9621360)
Scenario: [https://app.hiptest.com/projects/114163/test-plan/folders/801154/scenarios/2692157](https://app.hiptest.com/projects/114163/test-plan/folders/801154/scenarios/2692157)

### Preconditions (*)

1. Simple Product is created

### Steps to reproduce (*)

1. Go to Stores->Configuration->Catalog->Inventory
2. Open tab "Product Stock Options"
3. Change "Manage Stock" to "Yes"
4. Change "Maximum Qty Allowed in Shopping Cart" to 3
5. Click button "Save config"
6. Go to Store -> Cache Management
7. Click button Flush Magento Cache
8. Create empty cart with GraphQL (or just remove all the products from shopping cart)
9. Perform query
```
mutation {
  addSimpleProductsToCart(
    input: {
      cart_id: "{{ CART_ID }}", 
      cartItems: [
        {
          data: {
            sku: "simple-1", 
            qty: 4
          },         
        }
      ]
    }
  ) {    
    cart {
      items {
        id
        qty        
        product {
          sku
          name         
        }
      }
    }    
  }
}
```

### Expected result (*)

1. `... "message": "The most you may purchase is 3.", ...`

### Actual result (*)

1. `... "message": "Internal server error", ...`
```
{
  "errors": [
    {
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addSimpleProductsToCart"
      ]
    }
  ],
  "data": {
    "addSimpleProductsToCart": null
  }
}
```

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/367
