### ISSUE TITLE
While adding the product to Cart when the requested Qty is zero or less then zero, one was unexpectedly added

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#357]
### Preconditions (*)

1. #224 or #320  is merged or #142 is fixed (if not need to work create a  new branch based on `142_Add_configurable_product_to_Cart`, not `2.3-develop`)

### Steps to reproduce (*)

1. Create any Product from Storefront with qty 1000 and Stock Status IN_STOCK. For example:

| Key                     | Value                        | Value                        |
|-------------------------|------------------------------|------------------------------|
| PRODUCT TYPE            | SIMPLE                       | VIRTUAL                      |
| Name                    | Simple Product               | Virtual Product              |
| SKU                     | simple-product               | virtual-product              |
| Price                   | 10                           | 10                           |
| qty                     | 1000                         | 1000                         |
| Tax Group               | Taxable Goods                | Taxable Goods                |
| Stock Status            | IN_STOCK                     | IN_STOCK                     |
| Weight                  | 1                            | 1                            |

2. Create an empty Cart from Storefront or using GraphQL API.
3. Get the Masked Quote Id
4. Perform GraphQL request:
```graphql
mutation {
  addSimpleProductsToCart(
    input: {
      cart_id: "BVbiFodiH2s8m0HOcLvrUAKzpEJuvzHQ"
      cartItems: [{
        data: {
          sku: "simple-product"
          qty: 0
        } 
      }{
        data: {
          sku: "virtual-product"
          qty: 0
        }
      }
      ]
    }
  ) {
    cart {
      items {
        qty
        ... on SimpleCartItem {
          product {
            type_id
            name
            sku
            price {
              regularPrice {
                amount {
                  value
                }
              }
            }
            stock_status
          }
        }
        ... on VirtualCartItem {
          product{
            type_id
            name
            sku
            price {
              regularPrice {
                amount {
                  value
                }
              }
            }
            stock_status
          }
        }
      }
    }
  }
}
```
### Expected result (*)

1. message: "Please enter a quantity greater than 0." or at least qty in the Cart doesn't change after request

### Actual result (*)

1. Qty is increasing by one after every request

**Comment by naydav** [comment]
@TomashKhamlai 
Please, recheck this bug on latest `2.3-developer` branch
Thanks

**Comment by XxXgeoXxX** [comment]
Hi, everyone 
I reproduced this bug. It happens because Magento recheck input value by knokout(uses class 'validate-greater-than-zero':true).

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/487
