### ISSUE TITLE
[Cart Operations] Add configurable product with required customizable option(s) to Cart

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#362]
As a Magento developer, I need to manipulate the shopping cart via GraphQL so that I can build basic ecommerce experiences for shoppers on the front-end using only GraphQL.

GraphQL needs to provide sufficient mutations (ways to create/update/delete data) for a developer to build out the storefront checkout experience for a shopper.

**Use cases:**
- Both guest and registered shoppers can add configurable products with customizable options to cart
- [Hiptest](https://app.hiptest.com/l/scenario/2734001/mc-7770-add-configurable-product-by-providing-required-custom-options-to-cart)

**Acceptance criteria:**
- Cart operations should be useable when there are required customizable options

**My Account area impacted:** 
- Cart
- Minicart

**Comment by naydav** [comment]
@TomashKhamlai Please check this issue on the latest dev branch
If the bug is present need to create separate tickets with more clear steps

**Comment by naydav** [comment]
The functionality will be added in https://github.com/magento/graphql-ce/issues/663
