### ISSUE TITLE
[Cart Operations] Manage Cart Items

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#37]
As a Magento developer, I need to manipulate the shopping cart via GraphQL so that I can build basic ecommerce experiences for shoppers on the front-end using only GraphQL.

GraphQL needs to provide sufficient mutations (ways to create/update/delete data) for a developer to build out the storefront checkout experience for a shopper.

**Use cases:**
- Both guest and registered shoppers can add new items to cart
- Both guest and registered shoppers can update item qty in cart 
- Both guest and registered shoppers can remove items from cart
- Both guest and registered shoppers can update the configuration (for a configurable product) or quantity of a previously added configurable product in cart
    - Edit Item link > Product page > Update configuration or qty > Update Cart 

**Acceptance criteria:**
- Cart operations should be useable in both standard Cart and mini-cart
- GraphQL provides the following mutations:
  - `addCartItems`
  - `updateCartItems`
  - `removeCartItems`
- `updateCartItems` mutation allows the cart item quantity to be updated in a shopper's cart
- All product types are supported in a modular way (e.g. configurable-related schema and resolvers must be declared in `ConfigurableProductGraphQl` module and the rest of the system should still work if this module is disabled)
- Depending on token in `Authorization` header (if any), customer or guest service contract should be used
- Changes are covered with web API functional tests. See [\Magento\GraphQl\TestModule\GraphQlMutationTest::testMutation](https://github.com/magento/graphql-ce/blob/db3f2c73416c19f9cc13b1cbc48d504e843dc476/dev/tests/api-functional/testsuite/Magento/GraphQl/TestModule/GraphQlMutationTest.php#L15) as an example.

[**Proposed schema**](https://github.com/magento/architecture/pull/15/files)

**My Account area impacted:** 
- Cart
- Minicart

**Comment by masodu** [comment]
@misha-kotov a general comment is that normally cart operations are based on a single product selection. AFAICS I am not sure about the use case to add/update more items at the same time.

**Comment by masodu** [comment]
@misha-kotov I am not sure about current status of magento cart `functionalities` but in practice we could have a cart with 2 different cart items having the same `sku`. A simple use case to visualise this is a promotion with a text like `By one and get one for free`. Again I am not sure how this is (if) implemented  in magento but for a promotion like that the cart could have two cart items, with same `sku`, where the price for one of the cart items is 0. For this kind of use cases I think it is much safer to modify a cart item based on its internal `id`.

**Comment by masodu** [comment]
@misha-kotov how would be possible to remove just one cart item?

**Comment by misha-kotov** [comment]
@masodu updated the description, though I'm not sure where I had described the use case of updating multiple items at the same time. Agreed it should likely be one at a time. 
Thanks for pointing out the use case of multiple line items with the same `sku`. Good scenario to consider. 
Not sure if I understand your last question correctly, but you can remove one item at a time from your cart like so: 
![image](https://user-images.githubusercontent.com/18131925/42330250-5d9430f4-8038-11e8-90a4-969115e85d84.png)

**Comment by masodu** [comment]
@misha-kotov my previous comments are based on the following spec:
`type Mutation {`
`carttemsAdd(cartId: String!, items: [CartItemInput!]!): Cart`
`    cartItemsUpdate(cartId: String!, items: [CartItemInput!]!): Cart`
`   cartItemsRemove(cartId: String!): Cart`
`}`
IIUC the `cartItemsRemove` has as input only the `cartId` so that's why I wasn't sure how an item can be removed from cart. 

A simpler definition could be: 
`type Mutation {`
`   cartItemAdd(cartId: String!, sku String!, quantity Float!): Cart`
`   cartItemUpdate(cartId: String!, itemId String!, quantity Float!): Cart`
`   cartItemRemove(cartId: String!, itemId String!): Cart`
`}`

Btw what is the scope of  the `options` in cart mutations?

**Comment by mhaack** [comment]
@misha-kotov the `type Cart` & `type CartItem` we need to make sure this is not an 1:1 mapping of the REST api. A few comments on that.

`type Cart` should additionally contain all relevant information of an entire cart, like:
* all relevant price & cost information like totals, tax, discounts, costs for payment or shipping
* should have a discount attribute (array) to indicate applied discounts for cart or shipping discounts
* should have a coupon/voucher attribute (array) which contains applied coupons


Related to `type CartItem`:
* only one price is not enough, price should be a list to support multiple prices like item price, discounts, strike price, unit price of product, net/gross, etc.
* should have a discount attribute to indicate applied discounts
* `qty: Float` not int? If this is to support cart items like "0.5kg of meat"? If yes then I think the unit is missing.
* `price: Money` money is not defined, I guess that already exists?
* it should be possible to "expand" the product of related to a cart entry to get all product attributes (description, assets, ...) needed to render a cart view without additional calls

**Comment by paliarush** [comment]
@mhaack thanks for the feedback!

We can design schema of `Cart` as we think makes the most sense. REST representation served as a starting point and now we can discuss and evolve the schema as needed.

`type Cart`:
- It will contain all fields relevant to cart, they will be added in scope of other tasks. Right now there is a comment about that in type declaration

`type CartItem`:
- We'll think what price types should be available and update proposed schema
- Magento allows quantity to be `float`, it is configurable on product level as far as I remember
- `Money` already exists and is used within `ProductInterface`
- Regarding "expand" makes sense, we'll see how to represent it taking into account different product types

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/373

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/377
