### ISSUE TITLE
Category Query Missing Children

### ISSUE THREAD

**Issue by tjwiebell** [magento/graphql-ce#374]
### Preconditions (*)

1. Magento 2.3.x (repro'd on 2.3.0 and 2.3.1-alpha1)
2. Magento Cloud Pro (Production)
3. Categories created with nesting

### Steps to reproduce (*)

1. Execute category query below with variables `{id: 2}` (or Default Category ID)
```graphql
category(id: $id) {
  id
  name
  children {
    id
    name
  }
}
```

### Expected result (*)

1. CategoryTree is returned with children

### Actual result (*)

1. Children is empty array

### Notes
We found a temporary work around that tricks the instance into returning the correct data. If you include a products field in the query, I think it tricks the system into running a query against the database instead of using a cache/fts/flat table (haven't dug into the cause, just a suspicion).

```graphql
category(id: $id) {
  id
  name
  children {
    id
    name
  }
  products(pageSize: 1) {
    items {
      small_image
    }
  }
}
```

**Comment by TomashKhamlai** [comment]
@tjwiebell don't you think that this is Cloud only bug?
And I want to know one little detail. Is it possible to reproduce it again after workaround and how?

**Comment by tjwiebell** [comment]
My title indicates this is specific to Magento Pro Cloud, but is likely an issue with any instance that uses distributed resources. I would have preferred to keep this ticket internal, since it's very specific to Magento Cloud Pro, but we've taken all graphql issues/development public.

No, the work around resolves the problem. If you wanted to re-create, remove the work around (the first query in the issue).

**Comment by priti2jcommerce** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  priti@twojay.in
    Domain 2jcommerce.in has exceeded the max emails per hour (274/250 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from out-9.smtp.github.com ([192.30.254.192]:51127)
	by mail.2jcommerce.co.uk with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1gw9O8-000REw-5Y
	for priti@2jcommerce.in; Tue, 19 Feb 2019 17:41:00 +0000
Date: Tue, 19 Feb 2019 09:40:18 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1550598018;
	bh=6ewH5s7RYFJkag88eq6ddTi2rvoY5a1Ak/JOhPm2tq0=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=V1RMC7p/yX5UiQRo54kSCrFR6RemMjhdRXtFoZFVAUh1YzQ4mLWTULdGt6WF6T1hR
	 zWYmj0B86/ltDqRJ++0hMAzoOEy3u7L4jIOnMYtMMrn3FZWIgbn9b4JXvwFwuLb0Bm
	 pbm53Vx3SH+HUICfKuWVGkxMwnp8902adP5VYKcQ=

**Comment by naydav** [comment]
Hi @tjwiebell,
Can't reproduce on cloud instance https://master-7rqtwti-srb4q4z3ynk4s.us-4.magentosite.cloud/index.php/graphql

**Comment by naydav** [comment]
Closed due to https://github.com/magento/graphql-ce/issues/567
