### ISSUE TITLE
[Checkout coverage] Manage Shipping methods on Cart

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#39]
As a Magento developer, I need to set and manage the selected shipping method on cart to support checkout via GraphQL so that I can build basic ecommerce experiences for shoppers on the front-end.

**Use Cases**
- Render available shipping methods on storefront
- Set and be able to modify the shipping method on the cart
- Request the currently set shipping method on cart
- Changes are covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.

**High Level I/O**
- Render available shipping methods on storefront
   - Input: saved address (id) or custom/new address
   - Output: available shipping methods
- Set and be able to modify the shipping method on the cart
   - Input: shipping carrier (code), shipping method (code)
   - Output: current cart
- Request the currently set shipping method on cart
   - Input: current cart
   - Output: currently set shipping method

**TO DO**
- find exact address fields that need to be provided in order to estimate OOTB shipping methods

**Comment by TravisBernard** [comment]
RE required address fields. In our experience Country, Region/State, Post/ZipCode, and City will get you base rating from most carriers. That said, for the best accuracy the full address including street address is [edit]suggested[/edit]. For example if street address is available FedEx will use it to determine if the delivery location is residential or a business as they provide better rates to businesses. So providing street address as optional is fine, but leaving it completely out of the schema would quickly become an issue.

The first few comments on this M2 issue list other use cases for the less-commonly-needed address fields: https://github.com/magento/magento2/issues/3789

**Comment by misha-kotov** [comment]
Thanks @TravisBernard , appreciate your input!

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/192
