### ISSUE TITLE
[Cart operations] Cannot get information about DateTime customizable option after adding product to cart

### ISSUE THREAD

**Issue by rogyar** [magento/graphql-ce#394]
### Description
On an attempt to retrieve information about customizable DateTime option of a product in the shopping cart the following error occurs:

```
The option instance type in options group is incorrect
```

### Steps to reproduce (*)
1. Create a simple product
2. Assign a Date & Time customizable option to the product
3. Add the newly created product to the shopping cart and retrieve information about its customizable options using the following query:
```graphql
mutation {
  addSimpleProductsToCart(
    input: {
      cart_id: "$cart_id",
      cartItems: [
        {
          data: {
            qty: 1
            sku: "simple simple"
          },
          customizable_options: [{id:140,value:"2000-12-03 12:00:00"}]
        }
      ]
    }
  ) {
    cart {
      items {
        ... on SimpleCartItem {
          customizable_options {
            label
              values {
                label
                value
              }
            }
        }
      }
    }
  }
}
```

### Expected result (*)
Product is added, information about customizable options is displayed

### Actual result (*)
Product is added, the following error displayed instead of customizable options

```graphql
{
  "errors": [
    {
      "debugMessage": "The option instance type in options group is incorrect.",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 19,
          "column": 11
        }
      ],
      "path": [
        "addSimpleProductsToCart",
        "cart",
        "items",
        0,
        "customizable_options"
      ]
    }
  ]
}
```

**Comment by rogyar** [comment]
Ok, the problem is datetime type is not introduced within a scope of GraphQl coverage. Closing this one

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/414
