### ISSUE TITLE
mutations add<Product Type>ProductsToCart dosn't check if the cart is active

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#408]
Customer is able to perform requests to the cart even if the cart is not active.

Imagine such sequence of user actions considering that we use graphql and msi:
 - create product with qty = 1000
 - add product to cart with qty = 1 and place order
 - add 999 products to non-active cart (probably reservations will be created)
 - create empty cart and have a fun with merchant

Even if no real data interaction is performed and we won't have any problems with inventory data still I believe such behaviour is not user friendly. Some message should appear to notify user that he has to create a new cart if the cart id cannot be generated automatically.

After adding products to non-active cart user can try to perform `setShippingAddressesOnCart` and get 
"No such entity with cartId = 22". From this moment user knows how to get some metrics about the store.

### Preconditions (*)

1. Registered customer is created
2. Simple Product is created

### Steps to reproduce (*)

1. Generate Customer token (GraphQL)
2. Create empty cart (GraphQL)
3. Add simple product to cart (GraphQL)
4. Login as Customer (Storefront)
5. Place order (Storefront)
6. Add simple product to cart (GraphQL)
7. Set shipping address on cart (GraphQL)
```
mutation {
  setShippingAddressesOnCart(
    input: {
      cart_id: "{{ CART_ID }}"
      shipping_addresses: {
        customer_address_id: {{ ADDRESS_ID }}
      }
      
    }
  ) {
    cart {
      shipping_addresses {
        items_weight
        available_shipping_methods {
          method_code
          carrier_code
        }
      }
    }
  }
}
```

### Expected result (*)

1. User is not allowed to go so far

### Actual result (*)

1. User thinks that he is adding products to  the cart
2. User can collect some metrics like checkouts per day
```
{
  "errors": [
    {
      "debugMessage": "No such entity with cartId = 22",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "setShippingAddressesOnCart"
      ]
    }
  ],
  "data": {
    "setShippingAddressesOnCart": null
  }
}
```

**Comment by naydav** [comment]
Need to load cart by
`\Magento\Quote\Api\CartRepositoryInterface::getActive`
in `\Magento\QuoteGraphQl\Model\Cart\GetCartForUser::execute`

Functionality should be covered with API-functional tests

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/455
