### ISSUE TITLE
items are not populated to SetShippingAddressesOnCartOutput

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#410]
Could be not a bug

### Preconditions (*)

1. Customer is created
2. Simple Product is created

### Steps to reproduce (*)

1. Generate Customer token (GraphQL)
2. Create empty cart (GraphQL)
3. Add Simple Product to Cart (GraphQL)
4. Set shipping address on cart
```
mutation {
  setShippingAddressesOnCart(
    input: {
      cart_id: "{{ CADT_ID }}"
      shipping_addresses: {
        customer_address_id: {{ ADDRESS_ID }}
      }
    }
  ) {
    cart {
      items {
        product {
          ... on PhysicalProductInterface {
            weight
          }
        }
      }
    }
  }
}
```

### Expected result (*)

1. `data.setShippingAddressesOnCart.cart.items` is populated with data

### Actual result (*)

1. `data.setShippingAddressesOnCart.cart.items` is null

**Comment by naydav** [comment]
@TomashKhamlai @XxXgeoXxX 
Please, recheck this bug on last 2.3-develop branch
Should have been fixed in the scope of https://github.com/magento/graphql-ce/pull/330

**Comment by XxXgeoXxX** [comment]
rechecked. 
Issue was fixed
