### ISSUE TITLE
Create scheme design for taxes

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#411]
There is no way to display taxes in Shopping Cart and Customer Orders.

### Preconditions (*)

1. **Tax Rule is created(by default) based on default tax rates (Stores -> Tax Rule):**
 - US-CA-*-Rate 1 = 8.2500
 - US-NY-*-Rate 1 = 8.3750
2. **Tax configuration (Store -> Configuration -> Sales -> Tax)**

- Default Tax Destination Calculation
- - Default Country = United States
- - Default State = New York
- - Default Post Code = *
- Shopping Cart Display Settings
- - Include Tax In Grand Total	= Yes
- - Display Full Tax Summary = Yes
- - Display Zero Tax Subtotal = Yes
- Fixed Product Tax
- - Enable FPT
3. **Simple product is created:**
- Price = 10
- FTP:
- - United States/California/10
- - United States/New York/20
4. **Customer is created with default addresses:**
- First Name = John
- Last Name = Doe
- Company = qa
- Phone Number = 13456768768
- Fax = 987654321
- Street Address line 1 = Main st1
- Street Address line 2 = ap.66
- City = Culver City
- State/Province = California
- Zip/Postal Code = 90230
- Country = United States

### Steps to reproduce (*)

1. Generate Customer token (GraphQL)
2. Add Simple product to cart (GraphQL)
3. Set shipping address!!!  (GraphQL)
4. Get information about taxes

![image](https://user-images.githubusercontent.com/11827230/53433523-38904980-39fd-11e9-8c79-2d5879900ceb.png)

**Comment by naydav** [comment]
Closed due to https://github.com/magento/graphql-ce/issues/426
