### ISSUE TITLE
Test coverage: GetAvailablePaymentMethodsTest for Customer

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#419]
Need to cover next cases:

```
\Magento\GraphQl\Quote\Customer\GetAvailablePaymentMethodsTest
GetPaymentsForNotExistenCart
GetPaymentsFromCustomerCart
GetPaymentsFromAnotherCustomerCart
GetPaymentsIfPaymentsAreNotSet
```

Examples: https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest

**Comment by atwixfirster** [comment]
**Pull request:** https://github.com/magento/graphql-ce/pull/451

| Proposed Name | Name in Test|
| ------------- | ------------- |
| GetPaymentsFromCustomerCart | testGetPaymentMethodsFromCustomerCart |
| GetPaymentsFromAnotherCustomerCart | testGetPaymentMethodsFromAnotherCustomerCart |
| GetPaymentsIfPaymentsAreNotSet | testGetPaymentMethodsIfPaymentsAreNotSet |
| GetPaymentsForNotExistenCart | testGetPaymentMethodsOfNonExistentCart |

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/451
