### ISSUE TITLE
Test coverage: GetAvailablePaymentMethodsTest for Guest

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#420]
Need to cover next cases:

```
\Magento\GraphQl\Quote\\Guest\GetAvailablePaymentMethodsTest
GetPaymentsForNotExistenCart
GetPaymentsFromGuestCart
GetPaymentsFromAnotherCustomerCart
GetPaymentsIfPaymentsAreNotSet
```

Examples: https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest

**Comment by atwixfirster** [comment]
**Pull request:** https://github.com/magento/graphql-ce/pull/450

| Proposed Name                                          | Name in Test|
| ------------- | ------------- |
| GetPaymentsForNotExistenCart                | testGetPaymentMethodsFromGuestCart |
| GetPaymentsFromGuestCart                     | testGetPaymentMethodsFromAnotherCustomerCart |
| GetPaymentsFromAnotherCustomerCart | testGetPaymentMethodsIfPaymentsAreNotSet |
| GetPaymentsIfPaymentsAreNotSet           | testGetPaymentMethodsOfNonExistentCart |

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/450
