### ISSUE TITLE
[Place order] Cart tax

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#426]
Implement "cart tax" according to proposed scheme
https://github.com/magento/architecture/blob/master/design-documents/graph-ql/coverage/CartPrices.graphqls 

The scheme could be changed

Functionality should be covered by API-functional tests

Also, need to check the case described in
https://github.com/magento/graphql-ce/issues/411

**Comment by rogyar** [comment]
Hi @XxXgeoXxX. I'm accidentally unassigned myself. I'm working on that solution alongside the cart grand total. There's might be just one resolver, so no reason to have a few separate PRs.

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/441
