### ISSUE TITLE
Test coverage: nonExistentCart

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#429]
Need to add case when a user tries to work with a non-existent shopping cart to:

```
\Magento\GraphQl\Quote\Customer\SetPaymentMethodOnCartTest
\Magento\GraphQl\Quote\Guest\SetPaymentMethodOnCartTest
\Magento\GraphQl\Quote\Customer\SetBillingAddressOnCartTest
\Magento\GraphQl\Quote\Guest\SetBillingAddressOnCartTest
```

Examples you could find in
https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer

https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest

**Comment by atwixfirster** [comment]
**Pull request:** https://github.com/magento/graphql-ce/pull/444

Thank you!

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/444
