### ISSUE TITLE
[Query] My Account > My Wish List

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#43]
As a Magento developer, I need to render the My Account experience for customers via GraphQL so that I can build basic ecommerce experiences for shoppers on the front-end using GraphQL.

GraphQL needs to provide sufficient information for a developer to build out the storefront My Account experience for a shopper.

This includes being able to fetch, for the logged in customer:
My Wish List
![image](https://user-images.githubusercontent.com/18131925/40257594-590687de-5ab4-11e8-8d5b-05db077aaa90.png)

Changes are covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.

**Comment by davidverholen** [comment]
#squashtoberfest

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/223
