### ISSUE TITLE
Internal server error for query urlResolver while message "We can't find products matching the selection." appears on frontend

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#436]
If you discover that steps are not precise? please write a comment below and I will add more details.

### Preconditions (*)

1. Have some product that has corresponding URL rewrite, for example
simple-product.html -> catalog/category/view/id/5

### Steps to reproduce (*)

1. Create Custom URL Rewrite
	Request Path: bla-bla-bla
	Target Path: catalog/category/view/id/5
	Redirect Type: No
2. Perform query:
```
query{
  urlResolver(
    url: "bla-bla-bla"
  ) {
    id
    relative_url
    type
    
  }
}
```

### Expected result (*)

1. message "We can't find products matching the selection." instead of "message": "Internal server error"

### Actual result (*)

1. Internal server error
```
{
  "errors": [
    {
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ],
      "path": [
        "urlResolver",
        "type"
      ]
    }
  ],
  "data": {
    "urlResolver": {
      "id": 0,
      "relative_url": "catalog/category/view/id/5",
      "type": null
    }
  }
}
```

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/445
