### ISSUE TITLE
Improve coverage for mutation addConfigurableProductToCart

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#437]
[testAddOutOfStockProduct()](https://github.com/magento/graphql-ce/blob/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/AddConfigurableProductToCartTest.php#L86)
not covered all possible scenarios

### Preconditions (*)

1. 

### Steps to reproduce (*)

1. Create Configurable Product with
Name Configurable Product
SKU: configurable-product
Weight: 1
Price: 1
Variations:
- sku: configurable-product-option1, qty: 1000, price: 10
- sku: configurable-product-option2, qty: 1000, price: 10
2. Create empty cart as a Guest or as Customer (GraphQL)
3. Add configurable product to Cart (GraphQL)
4. Go to admin
5. Set Configurable product to be Out of Stock but don't change anything in configurable variations
6. Add configurable product to Cart again (GraphQL)
```
mutation {
  addConfigurableProductsToCart(
    input: {
      cart_id: "{{ CART_ID }}"
      cartItems: [
        {
          variant_sku: "useless-field"
          data: {
            qty: 11
            sku: "configurable-product-option1"
          }
        }
        {
          variant_sku: "useless-field"
          data: {
            qty: 11
            sku: "configurable-product-option2"
          }
        }
      ]
    }
  ) {
    cart {
      items {
        qty
      }
    }
  }
}
```

### Expected result (*)

1. When we try to add the product to the cart
![screenshot_20190305_145317](https://user-images.githubusercontent.com/11827230/53808259-6d028900-3f5a-11e9-9c9c-43e17ad9ecbf.png)

2. When we try to proceed to checkout
![screenshot_20190305_145302](https://user-images.githubusercontent.com/11827230/53808295-8c011b00-3f5a-11e9-9372-d84fb4464e89.png)

### Actual result (*)

1. Product is added to cart
```graphql
{
  "data": {
    "addConfigurableProductsToCart": {
      "cart": {
        "items": [
          {
            "qty": 5034
          },
          {
            "qty": 5034
          }
        ]
      }
    }
  }
}
```

**Comment by rogyar** [comment]
I would recommend postponing testing virtual products until the mutation is fixed. Currently, adding virtual products to cart does not work. Current routine does not take into account `variant_sku` and adds only simple products to the shopping cart. 
It's also related to https://github.com/magento/graphql-ce/issues/349

In a few words, we need to achieve the following scenario:
- Specify configurable product(s) for adding to cart
- Specify super attributes (configurable options) for the configurable product
- Add the configurable product to the shopping cart
- Check the database, `quote_item` table contains a configurable product and a simple product that corresponds the selected super attributes. The simple products have configurable cart item ID in the `parent_item_id` field.

I have ideas about the fix but need to discuss with @naydav.

**Comment by rogyar** [comment]
@TomashKhamlai I described the problem in details here https://github.com/magento/graphql-ce/issues/438

**Comment by TomashKhamlai** [comment]
Ok, I understood what you explain. #439 describes the problem and expectations that could be in future in a more simple manner.

**Comment by naydav** [comment]
Closed due to work on
https://github.com/magento/graphql-ce/issues/438
