### ISSUE TITLE
Adjust adding configurable products to the shopping cart

### ISSUE THREAD

**Issue by rogyar** [magento/graphql-ce#438]
### Desciption
Currently, we use the same approach for adding configurable products to the shopping cart as for the simple products. As result, we are able to add only simple products using `addConfigurableProductsToCart` mutation.

Take a look at the following mutation:

```graphql
mutation {
  addConfigurableProductsToCart(
    input: {
      cart_id: "{{ CART_ID }}"
      cartItems: [
        {
          variant_sku: "useless-field"
          data: {
            qty: 11
            sku: "configurable-product-option1"
          }
        }
        {
          variant_sku: "useless-field"
          data: {
            qty: 11
            sku: "configurable-product-option2"
          }
        }
      ]
    }
  ) {
    cart {
      items {
        qty
      }
    }
  }
}
```

`configurable-product-option1` and  `configurable-product-option2` are SKUs of the simple products. There's no mention about a configurable product that we are going to add to the shopping cart. `variant_sku` is not being processed in resolvers or somewhere else. So, yes, this field is useless.
After using the mentioned query we will have two simple products in the shopping cart (`configurable-product-option1` , `configurable-product-option2`) but zero configurable products.

Ideally, the mutation should have the following look:

```graphql
mutation {
  addConfigurableProductsToCart(
    input: {
      cart_id: "{{ CART_ID }}"
      cartItems: [
        {
          variant_sku: "configurable-product-option1"
          data: {
            qty: 11
            sku: "configurable-product-sku"
          }
        }
        {
          variant_sku: ""configurable-product-option2"
          data: {
            qty: 11
            sku: "configurable-product-sku"
          }
        }
      ]
    }
  ) {
    cart {
      items {
        qty
      }
    }
  }
}
```

In this case, we would have two configurable parent products in the cart and two corresponding simple items. This scenario corresponds to the scenario we have currently in storefront->backend flow.
But, as it was mentioned, this query will not work since `variant_sku` is not processed.

We could simply add `variant_sku` processing. But, unfortunately, things are not that easy. 
In order to create a correct buy request for a configurable product (https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/QuoteGraphQl/Model/Cart/AddSimpleProductToCart.php#L79) we need to pass super attributes values of the configurable product to this request, but not SKU of a child product. 
The storefront is designed in the following way:
- On a configurable product page, we see super attributes (not child simple products)
- Customer selects super attributes values and adds configurable product to the shopping cart
- On the backend side the super attributes and their values are converted to the simple product that is being added alongside to the configurable product. 

From the PWA perspective, I believe we should use a similar approach. Instead of possibility to pass a child product's SKU we should use super attributes (unless child products are going to be shown instead of attributes on a configurable PDP)

So the schema will look something like:

```graphql
mutation {
  addConfigurableProductsToCart(
    input: {
      cart_id: "{{ CART_ID }}"
      cartItems: [
        {
          configurable_attributes {[
          {
              id: $id
              value: $value
          }
          {
              id: $id
              value: $value
          }
          ]}
          data: {
            qty: 11
            sku: "configurable-product-sku"
          }
        }
      ]
    }
  ) {
    cart {
      items {
        qty
      }
    }
  }
}
```

Current GraphQl schema and resolvers don't respect this flow and we have no information about selected super attributes. So we cannot pass this information to the buy request. We have SKU of the child product but It's really hard to convert SKU -> supper attributes:values. The system designed to process it in reverse order: super attributes:values -> SKU.

**Comment by naydav** [comment]
@rogyar You vision is absolutely correct
Moreover, it was described in initial scheme proposal
https://github.com/magento/architecture/blob/master/design-documents/graph-ql/coverage/add-items-to-cart/AddConfigurableProductToCart.graphqls#L22

So, we need to have implement support of
```
mutation {
  addConfigurableProductsToCart(
    input: {
      cart_id: "{{ CART_ID }}"
      cartItems: [
        {
          variant_sku: "configurable-product-option1"
          data: {
            qty: 11
            sku: "configurable-product-sku"
          }
        }
        {
          variant_sku: ""configurable-product-option2"
          data: {
            qty: 11
            sku: "configurable-product-sku"
          }
        }
      ]
    }
  ) {
    cart {
      items {
        qty
      }
    }
  }
}
```

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/699
