### ISSUE TITLE
[Query] My Account > Gift Registry

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#44]
As a Magento developer, I need to render the My Account experience for customers via GraphQL so that I can build basic ecommerce experiences for shoppers on the front-end using GraphQL.

GraphQL needs to provide sufficient information for a developer to build out the storefront My Account experience for a shopper.

This includes being able to fetch, for the logged in customer:
Gift Registry
![image](https://user-images.githubusercontent.com/18131925/40257711-cae47352-5ab4-11e8-9872-6b23c0f0171a.png)

Changes are covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.

**Comment by naydav** [comment]
EE functionality
