### ISSUE TITLE
Enable GraphQL text fields to contain WYSIWYG/Pagebuilder content (as complex object)

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#45]
As a developer I want be able to add different response format for content fields in product, CMS, and Category API. Currently the API returns simple type (string), but in the future we may want to return HTML and/or JSON for more convenient processing by web apps. 

**Acceptance Criteria**
- Modify all fields of type textarea in Products GraphQL API to return an object instead of simple type so later data can be extended and retrieved in JSON format.
- Add a new attribute named `format` within each object, with two possible values (for now): `html` and `json` (potentially to be expanded later)
- By default complex object contains only string format, property value is `html`
- It is not necessary to modify the responses to return json values in the scope of this story
- Changes are covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.

**Example**
Before
```
type ProductInterface {
...
name: String
...
}
```

After
```
type ProductInterface {
   ...
   name: ComplexTextValue
   ...
}

type ComplexTextValue {
   html: String!   
   # this list can be expanded later, like adding json format 
}
```

**Comment by melnikovi** [comment]
Need to discuss AC before we start implementation.

**Comment by misha-kotov** [comment]
@melnikovi please provide list of Pagebuilder fields that need to be modified on each entity. 
Then the issue will be "ready to start"

**Comment by melnikovi** [comment]
We need to do this for all EAV attributes of type textarea.
