### ISSUE TITLE
Query category for disabled catalog with products returns the products count

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#463]
### Steps to reproduce (*)

1. Create Simple Product and assign it to any category that can be added to menu
2. Navigate to Catalog -> Categories and edit the category from previous step
3. Disable the category
4. Perform the query:
```graphql
{
  category(id: {{ ID }} ) {
    product_count
  }
}
```

### Expected result (*)

The following could be suggested:
```graphql
{
  "errors": [
    {
      "message": "Category doesn't exist",
      "category": "graphql-no-such-entity",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "category"
      ]
    }
  ],
  "data": {
    "category": null
  }
}
```

### Actual result (*)

```graphql
{
  "data": {
    "category": {
      "product_count": 1
    }
  }
}
```

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/476
