### ISSUE TITLE
Currency misspelled in graphql attributes

### ISSUE THREAD

**Issue by erikmarr** [magento/graphql-ce#464]
### Preconditions (*)
In the following PR: https://github.com/magento/graphql-ce/pull/313/files 'currency' is spelled 'currecy'. This occurs in the schema and test

### Steps to reproduce (*)
View the currency attributes in graphiql.

### Expected result (*)
'currecy' should be 'currency'

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/465
