### ISSUE TITLE
In some cases only data is received even when error or validation message is also expected

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#477]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1. Execute query:
```graphql
mutation {
  addDownloadableProductsToCart(
    input: {
      cart_id: "wwuiBJ2ZuJmwZcYbNBU7bqeX8Y0JDpql"
      cartItems: {
        data: {
          qty: 1
          sku: "downloadable-product-purchase-separately"
        }
        downloadable_product_links: [
          {
            link_id: 9
          }
          {
            link_id: 10
          }
        ]
      }
    }
  ) {
    cart {
      items {
        id
        qty
      }
    }
  }
}
```
2. Execute query:
```graphql
mutation {
  addDownloadableProductsToCart(
    input: {
      cart_id: "wwuiBJ2ZuJmwZcYbNBU7bqeX8Y0JDpql"
      cartItems: {
        data: {
          qty: 0.5
          sku: "downloadable-product-purchase-separately"
        }
        downloadable_product_links: [
          {
            link_id: 9
          }
          {
            link_id: 10
          }
        ]
      }
    }
  ) {
    cart {
      items {
        id
        qty
      }
    }
  }
}
```

### Expected result (*)

1. Validation with data:
```graphql
{
  "errors": [
    {
      "message": "Could not add the product with SKU downloadable-product-purchase-separately to the shopping cart: The fewest you may purchase is 1.",
      "category": "graphql-input",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addDownloadableProductsToCart"
      ]
    }
  ],
  "data": {
    "addDownloadableProductsToCart": {
      "cart": {
        "items": [
          {
            "id": "11",
            "qty": 1
          }
        ]
      }
    }
  }
}
```

### Actual result (*)

1. Only data:
```graphql
{
  "data": {
    "addDownloadableProductsToCart": {
      "cart": {
        "items": [
          {
            "id": "11",
            "qty": 1
          }
        ]
      }
    }
  }
}
```

**Comment by atwixfirster** [comment]
**Pull request:** https://github.com/magento/graphql-ce/pull/523

**Comment by atwixfirster** [comment]
@TomashKhamlai , I am not sure if this issue is an error.

In the first your query you added to Cart `1` x `Product A`.

In the second one, you added `0.5` x `Product A` to the same shopping cart. 

So, in the background process you added `1.5` x `Product A` into shopping cart because `Product A` with quantity `1` already exists in the cart + a new quantity `0.5`. 

In the result, you added to cart `1.5` x `Product A`. 

`Product A` does not support decimal product qty that is why `1.5` has been converted into `1`.

Could you please review this issue again and let me know your thoughts.

Thank you!

CC: @galaoleksandr

**Comment by naydav** [comment]
@TomashKhamlai 
It looks like not a bug... 

1st request: you added product with qty 1
2nd request: you try to add product with invalid qty 0.5

So, the expected result is a validation error about wrong qty
System talk us that something was wrong in input parameters

@atwixfirster Sorry that the ticket was not triaged. 
Now we are working on improvements of new ticket statuses (should be absolutely clear when a ticket is ready for development).
