### ISSUE TITLE
[Test Coverage] 'Selected Shipping Method' functionality

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#478]
Need to cover `Selected Shipping Method` functionality with API-functional tests.

Query scheme: `app/code/Magento/QuoteGraphQl/etc/schema.graphqls`

Testcases should be created::
```
\Magento\GraphQl\Quote\Guest\SelectedShippingMethodTest
- testGetCartWithShippingMethod
- testGetShippingMethodFromCustomerCart
- testGetShippingMethodIfShippinhMethodIsNotSet
- testGetShippingMethodOfNonExistentCart
```
Example: `\Magento\GraphQl\Quote\Guest\GetAvailablePaymentMethodsTest`

```
\Magento\GraphQl\Quote\Customer\SelectedShippingMethodTest
- testGetCartWithShippingMethod
- testGetShippingMethodFromGuestCart
- testGetShippingMethodFromAnotherCustomerCart
- testGetShippingMethodIfShippinhMethodIsNotSet
- testGetShippingMethodOfNonExistentCart
```
Example: `\Magento\GraphQl\Quote\Customer\GetAvailablePaymentMethodsTest`

Please, reuse current fixtures instead of creating new.

More examples you could find in
https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer

https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest

**Comment by 06romix** [comment]
#lvivcd19

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/491
