### ISSUE TITLE
[Test Coverage] 'GetBillingAddress' functionality

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#480]
Need to cover `GetBillingAddress` functionality with API-functional tests.

Query scheme: `app/code/Magento/QuoteGraphQl/etc/schema.graphqls`

Testcases should be created::
```
\Magento\GraphQl\Quote\Guest\GetBillingAddressTest
- testGetCartWithBillingAddress
- testGetBillingAddressFromCustomerCart
- testGetBillingAddressIfBillingAddressIsNotSet
- testGetBillingAddressOfNonExistentCart
```
Example: `\Magento\GraphQl\Quote\Guest\GetAvailablePaymentMethodsTest`

```
\Magento\GraphQl\Quote\Customer\GetBillingAddressTest
- testGetCartWithBillingAddress
- testGetBillingAddressFromGuestCart
- testGetBillingAddressFromAnotherCustomerCart
- testGetBillingAddressIfBillingAddressIsNotSet
- testGetBillingAddressOfNonExistentCart
```
Example: `\Magento\GraphQl\Quote\Customer\GetAvailablePaymentMethodsTest`

Please, reuse current fixtures instead of creating new.

More examples you could find in
https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer

https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest

**Comment by atwixfirster** [comment]
**Pull request:** https://github.com/magento/graphql-ce/pull/494

Thank you!

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/494
