### ISSUE TITLE
[Test Coverage] 'RemoveCouponFromCart' functionality

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#481]
Need to cover `RemoveCouponFromCart` functionality with API-functional tests.
Functionality should be fixed if needed.

Query scheme: `app/code/Magento/QuoteGraphQl/etc/schema.graphqls`

Testcases:
```
\Magento\GraphQl\Quote\**Guest**\RemoveCouponFromCartTest
- testRemoveCouponFromCart (should be moved and refactored from \Magento\GraphQl\Quote\CouponTest::testRemoveCoupon)
- testRemoveCouponFromCartWithoutItems
- testRemoveCouponFromCustomerCart (should be moved and refactored from 
\Magento\GraphQl\Quote\CouponTest::testRemoveCouponFromCustomerCartByGuest)
- testRemoveNonExistenCouponFromCart
- testRemoveCouponFromNonExistentCart
- testApplyCouponWithoutCartId
```
```
\Magento\GraphQl\Quote\**Customer**\RemoveCouponFromCartTest
- testRemoveCouponFromCart (should be moved and refactored from \Magento\GraphQl\Quote\CouponTest::testRemoveCoupon)
- testRemoveCouponFromCartWithoutItems
- testRemoveCouponFromGuestCart
- testRemoveCouponFromAonotherCustomerCart
- testRemoveNonExistenCouponFromCart
- testRemoveCouponFromNonExistentCart
- testApplyExpiredCoupon
- testApplyCouponWithoutCartId
```
Check another cases in `\Magento\Quote\Model\CouponManagement::remove`

Please, reuse current fixtures instead of creating new.

Examples you could find in
https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer

https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest

**Comment by roma-glushko** [comment]
Hi @naydav Thank you for creating this task!
I have some thoughts about cases that were mentioned in the description.

### Guest\RemoveCouponFromCartTest
- testApplyCouponWithoutCartId - seems like this part will be covered in #479 
### Customer\RemoveCouponFromCartTest
- testApplyExpiredCoupon - seems like this part will be covered in #479 
- testApplyCouponWithoutCartId - seems like this part will be covered in #479 

Rest of cases were covered in PR #497

Thank you,
Roman

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/497
