### ISSUE TITLE
[Test Coverage] 'SetPaymentMethodOnCart' functionality

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#483]
Need to cover `SetPaymentMethodOnCart` functionality with API-functional tests.
Functionality should be fixed if needed.

Query scheme: `app/code/Magento/QuoteGraphQl/etc/schema.graphqls`

Testcases:
```
\Magento\GraphQl\Quote\Customer\SetPaymentMethodOnCartTest
- add checking of purchase_order_number
- testSetPaymentMethodWitoutRequiredParameters [missed cart_id, missed payment_method, missed payment_method[code]] (example \Magento\GraphQl\Quote\Customer\RemoveItemFromCartTest::testUpdateWithMissedItemRequiredParameters)
```
```
\Magento\GraphQl\Quote\Guest\SetPaymentMethodOnCartTest
- add checking of purchase_order_number
- testSetPaymentMethodWitoutRequiredParameters [missed cart_id, missed payment_method, payment_method[code]] (example \Magento\GraphQl\Quote\Customer\RemoveItemFromCartTest::testUpdateWithMissedItemRequiredParameters)
```

Please, reuse current fixtures (from the same class) instead of creating new.

**Comment by AlexandrKozyr** [comment]
started at contribution day kharkiv 19

**Comment by AlexandrKozyr** [comment]
after discussing with @naydav 
- add checking of purchase_order_number

the requirement is out of the scope of this issue. it is specific only for purchase order Payment Method, so will be checked inside the separate issue.

**Comment by AlexandrKozyr** [comment]
@naydav 
pull request created.
https://github.com/magento/graphql-ce/pull/521
notices:
1. add checking of purchase_order_number - will be implemented in the another issue as discussed. (issue https://github.com/magento/graphql-ce/issues/499);
2. changed error message for https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/QuoteGraphQl/Model/Resolver/SetPaymentMethodOnCart.php#L68 (edited) 
 from `'Required parameter "code" for "payment_method" is missing'` to `'Required parameter "payment_method" is missing'` as we have discussed in the slack.
Please take a look on the PR

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/521
