### ISSUE TITLE
Add customer account validation in Quote operations

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#486]
Now "locked" or "not confirmed" customer could perform any operation with own cart.

Need to add the check with `\Magento\CustomerGraphQl\Model\Customer\GetCustomer::execute` (see examples of using this class in code)
in
https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/QuoteGraphQl/Model/Cart/GetCartForUser.php#L84
to avoid this behavior.

Functionality should be covered with API-functional tests.

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/714

**Comment by lenaorobei** [comment]
Fixed in magento/graphql-ce#714
