### ISSUE TITLE
Improve GraphQL caching

### ISSUE THREAD

**Issue by paliarush** [magento/graphql-ce#5]
As a Magento developer, I want appropriate GraphQL queries to be cached so that I get the maximum performance out of my applications and integrations that leverage GraphQL framework.

- GraphQL config caching: invalidate cache on certain dynamic events (as opposed to code modifications), like
  - adding/removing/updating EAV attribute
- [Server-side query caching](https://github.com/magento/graphql-ce/issues/17)
- https://philsturgeon.uk/api/2017/01/26/graphql-vs-rest-caching/

**Comment by paales** [comment]
Might be interesting: https://github.com/apollographql/apollo-cache-control
https://www.apollographql.com/docs/engine/caching.html

**Comment by cherdman** [comment]
Will be completed here: https://jira.corp.magento.com/browse/MC-15957
