### ISSUE TITLE
 [Test Coverage] We do not have a rollback for Magento/Customer/_files/three_customers.php fixture

### ISSUE THREAD

**Issue by atwixfirster** [magento/graphql-ce#502]
### Summary (*)
We do not have a rollback for `dev/tests/integration/testsuite/Magento/Customer/_files/three_customers.php` fixture

### Examples (*)
Run any test with `Magento/Customer/_files/three_customers.php` fixture. It could be, GetAvailablePaymentMethodsTest, for example. 

Please pay your attention to `customer_entity` table. Customers with emails customer2@search.example.com and customer3@search.example.com will exist

### Proposed solution
I've added a rollback in the PR: https://github.com/magento/graphql-ce/pull/495

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/495
