### ISSUE TITLE
CartAddress.available_shipping_methods should be type of Money

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#507]
### Summary (*)

`CartAddress.available_shipping_methods.amount`
`CartAddress.available_shipping_methods.price_excl_tax`
`CartAddress.available_shipping_methods.price_incl_tax`
`CartAddress.available_shipping_methods.base_amount`
should be type of `Money`

### Examples (*)

```
mutation {
  setShippingAddressesOnCart(
    input: {
      cart_id: "H37aMTEx5YpXLVG8ayZef39ZtW388fk4"
      shipping_addresses: {
        customer_address_id: 1
      }
    }
  ) {
    cart {
      shipping_addresses {
        available_shipping_methods {
          price_incl_tax {
            currency
            value
          }
          base_amount {
            currency
            value
          }
          price_excl_tax {
            currency
            value
          }
          amount {
            currency
            value
          }
        }
      }
    }
  }
}
```

### Proposed solution

Change GraphQL schema. Add description to clarify the difference between `price` and `amount`.

In every day life there is a difference between Price and Total. **Amount** is the same as **Total** or it is the same as **Price**. @paliarush, @keharper could you share your opinion? This opinion will be very useful for those who will update descriptions on schema.

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/645
