### ISSUE TITLE
Test coverage for tag cache generation

### ISSUE THREAD

**Issue by nrkapoor** [magento/graphql-ce#514]
1.Pre-conditions :
     (a)   Built-in cache enabled
     (b) Deploy mode is set to developer ( for the debug headers to be visible in the response)

*Use Case 1*: Cache tag validation
Steps:
1. Create a product
2. Send a curl  request via graphql endpoint( or use Postman )
       curl -I http://localhot/graphql?query=UrlEncodedQuery
Expected result:
Verify the tag X-Magento-Cache-Debug: MISS
3. Send the request again
   Expected Result:
    X-Magento-Cache-Debug: HIT

USE CASE 2: Cache Invalidation 
1. Create a product
2. Assert that the Response headers have X-Magento-Cache-Debug: MISS when you issue graphql request
3. Change product attribute( for exampe: price update)
4.Assert that the Response headers have X-Magento-Cache-Debug: MISS when you issue graphql request ( since a cache invalidation has occured)

USE CASE 3: Updating price or any product attribute for one of the many products and verify if cache invalidation happens for only the affected product
   1. Create couple products(prod1, prod2) in a category
   2. send the graphql query with store code in the header for prod1
         Validate the debug headers in the  response ( for a MISS)
   4. Now, update the product price for prod1  and load the product
        Verify the response header for MISS when querying for prod1
         Verify the response header for HIT when querying for prod2 

USE CASE 4: Updating product in second store doesn't affect the X-Debug-Cache-status for the same product in the default store

Use case 5: Validating the cache tag for category in the response header
   Expected: X-Magento-Tags →cat_c,cat_c_.$categoryId,cat_p,cat_p_$productId,FPC

**Comment by cherdman** [comment]
Blocked pending the resolution of https://jira.corp.magento.com/browse/DEVOPS-4924

**Comment by dthampy** [comment]
This is blocked by DEVOPS-4924
Since the api-functional tests created for testing this feature require magento to be in MODE_DEVELOPER, a separate job or an instance to run these tests with magento on developer mode , would be great.
