### ISSUE TITLE
Integration test to cover for varnish support for graphql

### ISSUE THREAD

**Issue by nrkapoor** [magento/graphql-ce#515]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by cherdman** [comment]
Blocked pending the resolution of https://jira.corp.magento.com/browse/DEVOPS-4924

**Comment by avattam06** [comment]
Internal Magento wiki/MAGE2/Caching+TP#CachingTP-TestCases
