### ISSUE TITLE
Spike - Varnish testing

### ISSUE THREAD

**Issue by nrkapoor** [magento/graphql-ce#516]
### Preconditions (*)
1. Install Magento + Varnish enabled
 
### Steps to reproduce (*)
1. Add a test to make sure that Varnish cache works for products queries and invalidates properly on the related product modifications on Magento+ GraphQL + Varnish enabled
2. Also check manually cache HIT, MISS manually and Response Headers.

**Comment by avattam06** [comment]
Added Analysis Document on https://github.com/magento/graphql-ce/wiki/Spike-Varnish-Testing
and internal wiki/Spike+On+Varnish+Testing, DevOps ticket DEVOPS-4924.
