### ISSUE TITLE
[Query] My Account > My Invitations

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#53]
As a Magento developer, I need to render the My Account experience for customers via GraphQL so that I can build basic ecommerce experiences for shoppers on the front-end using GraphQL.

GraphQL needs to provide sufficient information for a developer to build out the storefront My Account experience for a shopper.

This includes being able to fetch, for the logged in customer:
My Invitations

![image](https://user-images.githubusercontent.com/18131925/40329205-6cb007d6-5d0e-11e8-85ae-303d205da257.png)

Changes are covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.

**Comment by pfantini** [comment]
Hi @misha-kotov! 
The `Magento_Invitation` module is only available in EE. Are you thinking to moving it to CE in 2.3 or this requirement is not valid for graphql-ce?

**Comment by naydav** [comment]
EE functionality
