### ISSUE TITLE
[Cart Operations] Update Cart Items validation messages

### ISSUE THREAD

**Issue by atwixfirster** [magento/graphql-ce#530]
Issue is reproduce-able in GraphQl - https://github.com/magento/graphql-ce
 
### Preconditions (*)
1. Create a simple product with SKU `my-simple-product`
2. Advanced Inventory > Qty: `100`
3. Advanced Inventory > Minimum Qty Allowed in Shopping Cart: `1`
4. Advanced Inventory > Qty Uses Decimals: `No`

### Steps to reproduce (*)
1. Create an empty cart through
```
mutation {
  createEmptyCart
}
```

2. Try to add `0.5` x `my-simple-product` into shopping cart
```
mutation {
  addSimpleProductsToCart(
    input: {
      cart_id: "d4viG4wIYOorhYCOxGsxd3GTjn8DnBqc"
      cartItems: {
        data: {
          qty: 0.5
          sku: "my-simple-product"
        }
      }
    }
  ) {
    cart {
      items {
        id
        qty
      }
    }
  }
}
```

3. You will get `Could not add the product with SKU my-simple-product to the shopping cart: The fewest you may purchase is 1.` error. This is the expected result.

4. Now, please add `1` x `my-simple-product` into shopping cart
```
mutation {
  addSimpleProductsToCart(
    input: {
      cart_id: "d4viG4wIYOorhYCOxGsxd3GTjn8DnBqc"
      cartItems: {
        data: {
          qty: 1
          sku: "my-simple-product"
        }
      }
    }
  ) {
    cart {
      items {
        id
        qty
      }
    }
  }
}
```

5. You will get 
```
{
  "data": {
    "addSimpleProductsToCart": {
      "cart": {
        "items": [
          {
            "id": "131",
            "qty": 1
          }
        ]
      }
    }
  }
}
```

6. Let's update `my-simple-product` quantity through `updateCartItems` mutation query
```
mutation {
  updateCartItems(input: {
    cart_id: "d4viG4wIYOorhYCOxGsxd3GTjn8DnBqc"
    cart_items: [
      {
        cart_item_id: 131
        quantity: 0.5
      }
    ]
  }) {
    cart {
      items {
        id
        qty
      }
    }
  }
}
```

### Expected result (*)
`updateCartItems`should return `The fewest you may purchase is 1.` error:

<img width="1287" alt="01" src="https://user-images.githubusercontent.com/13585327/54925864-dcdfb000-4f17-11e9-8e58-f111afda4dc7.png">

### Actual result (*)
`updateCartItems` returns `Invalid value of "0" provided for the qty field.`:

<img width="1287" alt="02" src="https://user-images.githubusercontent.com/13585327/54925817-c20d3b80-4f17-11e9-8ece-0dcc82568bdb.png">

@TomashKhamlai , could you please review this issue and let me know if the expected result is correct?

Thank you!!

CC: @galaoleksandr

**Comment by atwixfirster** [comment]
**PR:** https://github.com/magento/graphql-ce/pull/531

Thank you!

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/531
