### ISSUE TITLE
Api-functional tests fixture refactoring

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#538]
Create set of reusable fixtures for Quote testing

**Comment by atwixfirster** [comment]
@naydav , could you provide more information here. What kind of fixtures, etc...

Many thanks! 😊

**Comment by naydav** [comment]
@atwixfirster I assigned this ticket on myself. The result will be available tomorrow. Generally, it simplifies writing tests for us.

**Comment by atwixfirster** [comment]
> @atwixfirster I assigned this ticket on myself. The result will be available tomorrow. Generally, it simplifies writing tests for us.

sure, sir! ;)

Thank you!

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/539
