### ISSUE TITLE
[Mutations] My Account: Change Password

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#54]
As a Magento developer, I need to build a functional My Account experience for customers via GraphQL so that I can build basic ecommerce experiences for shoppers on the front-end using only GraphQL.

GraphQL needs to provide sufficient mutations (ways to create/update/delete data) for a developer to build out the storefront My Account experience for a shopper.

**Use cases:** 
- A logged-in shopper can change their password from the My Account Page

**Acceptance criteria:** 
- GraphQL provides a mutation through which the current logged-in shopper can change their password 
- Password change should work for both auth mechanisms: customer token and the session cookie
- A guest shopper cannot change the password for any user
- A meaningful error message is given if current password is incorrect or if new password does not conform to minimum requirements
- Changes are covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.

My Account area impacted: Account Information tab
![image](https://user-images.githubusercontent.com/18131925/40376315-ab6b8d88-5db3-11e8-9b46-f5774b67e11d.png)

**Comment by rogyar** [comment]
Hi guys. As far as I know, we use bearer token for the authentication, like the original API does. The task description says that we need to use cookies. Is the authentication principle has been changed recently? Could you clarify this point, please? Thank you

**Comment by misha-kotov** [comment]
@rogyar sorry for the confusion. Auth principles did not change, but GraphQL currently can use two methods for auth: Bearer token and [session authentication](https://devdocs.magento.com/guides/v2.2/get-started/authentication/gs-authentication-session.html) (given you're on the same browser/agent). @paliarush please confirm I'm not talking crazy talk. 
For this story, it should work with both, but honestly it's probably more important that it works with the token approach. I will update the description to reflect this.

**Comment by paliarush** [comment]
@misha-kotov You are correct, we have both, token-based and [cookie-based](https://github.com/magento/magento2/blob/f534469d94e3ddc15f0b0eecac7a413936ac504d/app/code/Magento/Customer/etc/graphql/di.xml#L13) authentication enabled for customers in GraphQL.
