### ISSUE TITLE
Replace deprecated Magento/Checkout/_files/quote_with_address_saved.php fixture in SetOfflineShippingMethodsOnCartTest

### ISSUE THREAD

**Issue by atwixfirster** [magento/graphql-ce#542]
### Summary (*)

Use new fixtures from https://github.com/magento/graphql-ce/issues/538 for `Magento/GraphQl/Quote/SetOfflineShippingMethodsOnCartTest.php` API functional test.

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/543
