### ISSUE TITLE
ProductFilterInput. Remove duplicate "special_price" field

### ISSUE THREAD

**Issue by atwixfirster** [magento/graphql-ce#547]
### Summary (*)
There are 2 `special_price` fields in the `ProductFilterInput` declaration. 

![547](https://user-images.githubusercontent.com/13585327/55150055-02f19400-5154-11e9-8ab6-4645d85f5432.png)

Issue exists in Magento 2 release `version 2.3.1` - https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/CatalogGraphQl/etc/schema.graphqls

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/548
