### ISSUE TITLE
[Mutations] My Account > Change account information

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#55]
As a Magento developer, I need to build a functional My Account experience for customers via GraphQL so that I can build basic ecommerce experiences for shoppers on the front-end using only GraphQL.

GraphQL needs to provide sufficient mutations (ways to create/update/delete data) for a developer to build out the storefront My Account experience for a shopper.

**Use cases:**
- A logged-in shopper can change their account information from the My Account Page

**Acceptance criteria:**
- GraphQL provides a mutation through which the current logged-in shopper can change their account information
- Authentication is handled through a session cookie (changing the email address requires that current password is provided)
- A guest shopper cannot change the account information for any user
- A meaningful error message is given if current password is incorrect or if entered data does not conform to requirements
- List of fields that can be changed: 
  - First Name
  - Last Name 
  - Email address (requires current password)
- Changes are covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.
- Please propose GraphQL schema before starting implementation

**My Account area impacted:** 
- Account Information tab

Note: will likely merge https://github.com/magento/graphql-ce/issues/56 into this story

**Comment by nuzil** [comment]
As example of schema:

```
mutation {
  customerUpdate(
    firstname: "NAME",
    lastname: "LastNAME",
    email:"E-Mail"
    password: "password if required"
  ){
    firstname
    lastname
    email
  }
}
```

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/162
