### ISSUE TITLE
Document GET request support

### ISSUE THREAD

**Issue by danielrenaud** [magento/graphql-ce#554]
See magento/graphql-ce#229 

We should update documentation to disclose that GET requests are supported.

An example query like the following can be sent via GET

<pre>
query categoryList($id: Int!) {
    category(id: $id) {
        id
        children {
            id
            name
            url_key
            url_path
            children_count
            path
            image
            productImagePreview: products(pageSize: 1) {
                items {
                    small_image {
                      label
                      url
                    }
                }
            }
        }
    }
}
variables: {
  "id": 4
}
</pre>

<pre>
http://magento.test/graphql?query=querycategoryList%28%24id%3AInt%21%29%7B%0Acategory%28id%3A%24id%29%7B%0Aid%0Achildren%7B%0Aid%0Aname%0Aurl_key%0Aurl_path%0Achildren_count%0Apath%0Aimage%0AproductImagePreview%3Aproducts%28pageSize%3A1%29%7B%0Aitems%7B%0Asmall_image%7B%0Alabel%0Aurl%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%0A%7D%26variables%3D%7B%22id%22%3A4%7D
</pre>

Mutations are not allowed via GET.

**Comment by keharper** [comment]
Devdocs PR: https://github.com/magento/devdocs/pull/4142

**Comment by keharper** [comment]
Merged documentation into devdocs. See https://github.com/magento/devdocs/pull/4142 for details.
