### ISSUE TITLE
[Mutations] My Account > Newsletter Subsciption

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#56]
As a Magento developer, I need to build a functional My Account experience for customers via GraphQL so that I can build basic ecommerce experiences for shoppers on the front-end using only GraphQL.

GraphQL needs to provide sufficient mutations (ways to create/update/delete data) for a developer to build out the storefront My Account experience for a shopper.

**Use cases:**
- A logged-in shopper can change their newsletter subscription preference from the My Account Page

**Acceptance criteria:**
- GraphQL provides a mutation through which the current logged-in shopper can subscribe or unsubscribe from any newsletter 
- Authentication is handled through a session cookie
- A guest shopper cannot change the account information for any user
- Changes are covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.

**My Account area impacted:** 
- Newsletter Subscriptions tab
![image](https://user-images.githubusercontent.com/18131925/40377106-aecf96fc-5db5-11e8-91c3-87284c6e248e.png)

**Note:** functionality is closely related to issue #55 since they both modify the customer record

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/162
