### ISSUE TITLE
Category Tree - unable to return children of top-level categories after upgrade from 2.3.0 to 2.3.1

### ISSUE THREAD

**Issue by codeAdrian** [magento/graphql-ce#561]
### Preconditions (*)

1. Install Magento 2.3.0
2. Install Venia Sample Data
3. Upgrade to Magento 2.3.1 (run in production mode)

Also reproducible on Cloud version 2.3.1 with Venia sample data (default endpoint for PWA Studio): https://release-dev-231-npzdaky-zddsyhrdimyra.us-4.magentosite.cloud/

### Steps to reproduce (*)

1. Use the following query on a top level category (for example "Bottoms", id is 10, but it may vary)
```
query navMenu {
    category(id:10) {
        id
        name
        url_key
        level
        image
        position
        url_path
        children {
            id
            name
            image
            position
        }
    }
}

```

<img width="1280" alt="Screen Shot 2019-04-02 at 1 54 52 PM" src="https://user-images.githubusercontent.com/11479290/55402988-0bcbd680-5555-11e9-89d7-02d9cee3301a.png">

*Note:* Root category with `id: 2` returns children properly, this only affects top-level categories.

### Expected result (*)

1. Should return "Pants & Shorts" and "Skirts" subcategories as `children`

Screenshot from 2.3.0 instance
<img width="951" alt="Screen Shot 2019-04-02 at 1 40 29 PM" src="https://user-images.githubusercontent.com/11479290/55403256-bd6b0780-5555-11e9-8c21-ffa3e1646b1b.png">

### Actual result (*)

1. `null` is returned
2. Error is displayed on frontend

**Comment by codeAdrian** [comment]
From @tjwiebell 

It seems that this is the issue with Venia Sample data

> Tommy Wiebell   [3 hours ago]
We’ve recently resolved a bug in the sample data that was causing `children_count` to always be zero, and it appears to have also solved this issue. We don’t have a blue/green deployment process for that backing instance, so we’ll have to come up with a good time to get it re-installed w/o disrupting too many people.

**Comment by huykon** [comment]
Do you have any solution ?
