### ISSUE TITLE
Efficient Data Retrieval Framework for Category Queries

### ISSUE THREAD

**Issue by nrkapoor** [magento/graphql-ce#567]
As a developer,
I want to optimize the graphql data retrieval framework for category queries
so that
I can improve the response times at scale.

Every query optimization must follow the following steps.

Deploy the existing version on cloud starter.
Run Blazemeter perf test for the query with 50 concurrent users.
Optimize the data retrieval framework for the query.
Deploy the changes to cloud starter.
Rerun the perf test in step 2 again and document the findings.
Merge the changes to mainline and deploy to cloud pro.
Run the perf test on cloud pro with 5000 concurrent users.

**Comment by naydav** [comment]
@nrkapoor 
Please, review the description from initial ticket

The category query should include a filter argument, similar to the products query. It should achieve parity with the REST API's search criteria functionality on category entities.

AC
- User is able to filter categories by
   - id
   - name
   - description
   - isAnchor: return only categories that are isAnchor=yes or isAnchor=no
   - level: return only categories that are on the specified level in the tree
   - parentId: return only direct children of the specified parent category
- Endpoint accepts new filter criteria, and returns an array of matching CategoryTree objects

References:
* See [\Magento\CatalogGraphQl\Model\Resolver\Products::resolve](https://github.com/magento/magento2/blob/fb5eccfc7179d9180178bc5e648fd0ad07ea3cf6/app/code/Magento/CatalogGraphQl/Model/Resolver/Products.php#L82) as an example to generate search criteria with existing framework mechanisms

### Expected result
1. It is possible to filter categories based on filterable attributes in a category query.
2. Functionality is covered by automated api-functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.
