### ISSUE TITLE
Query Optimization on data retrieval framework for Category Queries.

### ISSUE THREAD

**Issue by avattam06** [magento/graphql-ce#572]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by mslabko** [comment]
Internal task for track progress: https://jira.corp.magento.com/browse/MC-15778
