### ISSUE TITLE
Unskip testApplyExpiredCoupon

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#574]
Unskip and fix
`\Magento\GraphQl\Quote\Customer\ApplyCouponToCartTest::testApplyExpiredCoupon`
`\Magento\GraphQl\Quote\Guest\ApplyCouponToCartTest::testApplyExpiredCoupon`

Failed just on Jenkins

**Comment by osrecio** [comment]
I will work on this!

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/694
