### ISSUE TITLE
Additional test coverage for queries based on the scenarios from graphql traceablity

### ISSUE THREAD

**Issue by dthampy** [magento/graphql-ce#577]
Functional test coverage for the below list has to be added:
    *1. GetCategoryQuery* 
    Steps: 
           -   create category with couple products 
          -  Run the category query :
`query GetCategoryQuery($id: Int!, $pageSize: Int!, $currentPage: Int!) {
        category(id: $id) {
            id
            description
            name
            product_count
            products(pageSize: $pageSize, currentPage: $currentPage) {
                items {
                    id
                    name
                    url_key
                }
                total_count
            }
        }
    }`
 - validate the Magento cache tags in the response header
Expected: Assert `cat_c,cat_c_$categoryId,cat_p,cat_p_$product1Id,cat_p_$product2Id,FPC`
    Use case 2: 
         Using the above query, validate` X-Magento-Cache-Debug` for `MISS` and `HIT` when the category is loaded the first and the second time respectively.
    Use Case 3: 
         update product1 attribute and run the above category query and validate ` X-Magento-Cache-Debug`= `MISS` 
Run product query for product 2 and verify ` X-Magento-Cache-Debug` for `HIT` 
     2. navigationMenu
     3. ProductSearchByUrl
     4. urlResolver
     5. productSearch
     6. textSearch
     7. Swatch color code/ImageData
     8. Related Products
Please refer to this internal wiki page for queries ran for PWA:
https://wiki.corp.magento.com/display/COREENG/Queries+executed+for+PWA+Cloud+Starter

**Comment by cherdman** [comment]
Blocked pending the resolution of https://jira.corp.magento.com/browse/DEVOPS-4924

**Comment by dthampy** [comment]
CR: https://fisheye.corp.magento.com/cru/CR-MAGETWO-45615

**Comment by cherdman** [comment]
Will be done as part of https://jira.corp.magento.com/browse/MC-16165
