### ISSUE TITLE
[Test Coverage] 'SetShippingMethodsOnCart' functionality

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#579]
Need to cover SetShippingMethodsOnCart functionality with API-functional tests both for Customer and Guest. Functionality should be fixed if needed.

Query scheme: `app/code/Magento/QuoteGraphQl/etc/schema.graphqls`

Test Cases:
```
\Magento\GraphQl\Quote\Customer\SetShippingMethodsOnCartTest
- testSetShippingMethodIfMethodIsDisabled
```

```
\Magento\GraphQl\Quote\Guest\SetShippingMethodsOnCartTest
- testSetShippingMethodIfMethodIsDisabled
```

Please, reuse current fixtures (from the same class) instead of creating new.

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/582
