### ISSUE TITLE
[Test Coverage] 'SetPaymentMethodOnCart' functionality

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#580]
Need to cover SetPaymentMethodOnCart functionality with API-functional tests both for Customer and Guest. Functionality should be fixed if needed.

Query scheme: `app/code/Magento/QuoteGraphQl/etc/schema.graphqls`

Test Cases:
```
\Magento\GraphQl\Quote\Customer\SetPaymentMethodOnCartTest
- testSetPaymentMethodIfMethodIsDisabled
```

```
\Magento\GraphQl\Quote\Guest\SetPaymentMethodOnCartTest
- testSetPaymentMethodIfMethodIsDisabled
```

Please, reuse current fixtures (from the same class) instead of creating new.

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/584
