### ISSUE TITLE
'save_in_address_book' is required

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#583]
Guest Account:
There is no such field
![screencapture-m2-test-io-checkout-1](https://user-images.githubusercontent.com/11827230/55874853-46102600-5b9c-11e9-9b82-361820585d7d.png)

Customer without address (new):
There is no such field
![screencapture-m2-test-io-checkout-3](https://user-images.githubusercontent.com/11827230/55874870-50cabb00-5b9c-11e9-9504-58d59fc86b9d.png)

Customer with address:
There is such field, but not required
![screencapture-m2-test-io-checkout-2](https://user-images.githubusercontent.com/11827230/55874887-5922f600-5b9c-11e9-95cf-1a22f7f321a9.png)

### Preconditions (*)

1. No preconditions

### Steps to reproduce (*)

1. Use `setShippingAddressesOnCart` for Guest Cart without specifying `save_in_address_book`.

### Expected result (*)

It not required to specify `save_in_address_book`

### Actual result (*)

1. Schema validation problem
![image](https://user-images.githubusercontent.com/11827230/55875889-de0f0f00-5b9e-11e9-812d-e0fa994f9e06.png)

**Comment by TomashKhamlai** [comment]
@naydav, please check.

**Comment by naydav** [comment]
Fix will be part of https://github.com/magento/graphql-ce/issues/509
