### ISSUE TITLE
Docs: Add a tutorial for the checkout workflow

### ISSUE THREAD

**Issue by keharper** [magento/graphql-ce#589]
Create a GraphQL tutorial for the checkout workflow. Conceptually, it should be similar to REST tutorials, such as [Order Processing](https://devdocs.magento.com/guides/v2.3/rest/tutorials/orders/order-intro.html).

Primary source: https://github.com/TomashKhamlai/graphql-ce/wiki/Checkout-workflow

This issue replaces devdocs issue https://github.com/magento/devdocs/issues/3715

**Comment by atwixfirster** [comment]
PR describes basic flow: https://github.com/magento/devdocs/pull/4271
