### ISSUE TITLE
Schema inconsistency in 'setBillingAddressOnCart', 'setShippingAddressesOnCart', 'CartAddress' declaration

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#592]
`CartAddressInput.region` for `setBillingAddressOnCart`/`setShippingAddressesOnCart` is expected to be type of `Int!` and should have name `region_id` or should have similar meaning as `CustomerAddress.region_id`
and
`CartAddress.region` is expected to be similar to `CustomerAddressRegion`

**Comment by naydav** [comment]
Closed due to splitting work in
https://github.com/magento/graphql-ce/issues/627
