### ISSUE TITLE
Invalid validation message "Unable to place order: Some addresses can't be used due to the configurations for specific countries."  when placing order without billing address

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#593]
**[ Draft ]**
We already have tests for this and expected message is `"Unable to place order: Please check the billing address information"`
actual message is `"Unable to place order: Please check the billing address information"`

Probably we need to cover this with end-to end test, write additional test or reconstruct existing test.

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. Order was placed

### Actual result (*)

1. "Unable to place order: Some addresses can't be used due to the configurations for specific countries.

**Comment by naydav** [comment]
@TomashKhamlai Please, provide more information about this issue
```
expected message is "Unable to place order: Please check the billing address information"
actual message is "Unable to place order: Please check the billing address information"
```

**Comment by TomashKhamlai** [comment]
@naydav, I have automated script. Ping me when #665 will be merged. I believe this PR resolves the problem.

Related to #658

**Comment by TomashKhamlai** [comment]
#665
