### ISSUE TITLE
Category with Product (Integration Test for Tag Cache Generation)

### ISSUE THREAD

**Issue by cherdman** [magento/graphql-ce#595]
<pre>
{
  category(id: 2) {
    products {
      total_count
      page_info {
        current_page
        page_size
      }
      items {
        attribute_set_id
        created_at
        id
        product_links {
          sku
          position
          link_type
        }
        short_description {
            html
        }
        sku
        type_id
        updated_at
        url_key
        url_path
      }
    }
  }
}
</pre>

**Comment by avattam06** [comment]
Fisheye review: CR-MAGETWO-45609
