### ISSUE TITLE
Category with Products with...(deep nesting) (Integration Test for Tag Cache Generation)

### ISSUE THREAD

**Issue by cherdman** [magento/graphql-ce#596]
<pre>
{
  category(id: 2) {
    products {
      total_count
      page_info {
        current_page
        page_size
      }
      items {
        attribute_set_id
        country_of_manufacture
        created_at
        description {
            html
        }
        gift_message_available
        id
        categories {
          name
          url_path
          available_sort_by
          level
          products {
            items {
              name
              id
            }
          }
        }
              }
    }
  }
}
</pre>

**Comment by prabhuram93** [comment]
Review: CR-MAGETWO-45620
