### ISSUE TITLE
Cart - No Cache Test (Api-functional Test for Tag Cache Generation)

### ISSUE THREAD

**Issue by cherdman** [magento/graphql-ce#597]
<pre>
#create guest cart
mutation {
  createEmptyCart
}
#add product to cart
mutation {
  addSimpleProductsToCart(
    input: {
      cartItems: [ {data: {  qty:1, sku: "simple-4"}}  ],
      cart_id: "MgzHhSQUVu4KSXmr73jnPa0P8ntJk9JD"
    }
  ) {
    cart {
      items {
        id
        product {
          name
          sku
        }
        qty
      }
      
    }
  }
}

# check cart
query {
  cart(cart_id: "MgzHhSQUVu4KSXmr73jnPa0P8ntJk9JD") {
    items {
      id
      product {
        sku
        name
        categories {
          name
          url_key
          products {
            items {
              name
              sku
            }
          }
        }
      }
      qty
    }
    available_payment_methods {
      code
      title
    }
  }

}
</pre>

Run the query in the order to make sure that the cart is not cached and it is a MISS , all subsequent times when loading the cart

**Comment by dthampy** [comment]
Link to the CR:
https://fisheye.corp.magento.com/cru/CR-MAGETWO-45636#CFR-1119411
