### ISSUE TITLE
[Mutations] My Account > Manage Stored Payment Methods

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#60]
As a Magento developer, I need to build a functional My Account experience for customers via GraphQL so that I can build basic ecommerce experiences for shoppers on the front-end using only GraphQL.

GraphQL needs to provide sufficient mutations (ways to create/update/delete data) for a developer to build out the storefront My Account experience for a shopper.

**Use cases:**
- A logged-in shopper can add/remove stored payment methods from the My Account Page

**Acceptance criteria:**
- GraphQL provides a mutation through which the current logged-in shopper can add/remove stored payment methods
- Authentication is handled through a session cookie (changing the email address requires that current password is provided)
- A guest shopper cannot change the data for any user
- Changes are covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.

**My Account area impacted:** 
- Stored Payment Methods tab
![image](https://user-images.githubusercontent.com/18131925/40387377-2f570744-5dd2-11e8-9691-ecb898cfe075.png)

**Comment by pmclain** [comment]
@naydav This was resolved here https://github.com/magento/graphql-ce/pull/307
Looks like there may have been a duplicate issues:
https://github.com/magento/graphql-ce/issues/46
