### ISSUE TITLE
[Test Coverage] Get Specified shipping address

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#602]
- Test coverage for "Get Specified shipping address"

Testcases should be introduced:
`\Magento\GraphQl\Quote\Customer\GetSpecifiedShippingAddressTest`
`\Magento\GraphQl\Quote\Guest\GetSpecifiedShippingAddressTest`

Example:
https://github.com/magento/graphql-ce/blob/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/GetSpecifiedBillingAddressTest.php

**Comment by atwixfirster** [comment]
**Pull Request:** https://github.com/magento/graphql-ce/pull/652/files

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/652
