### ISSUE TITLE
Expand `createEmptyCart` mutation

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#607]
- Need to add optional input parameter “cart_id” (like predefined id) to “createEmptyCart” mutation
https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L9
- Validation should be added
- API functional tests should be added

Examples:
https://github.com/magento/graphql-ce/blob/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/CreateEmptyCartTest.php

https://github.com/magento/graphql-ce/blob/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/CreateEmptyCartTest.php

**Comment by anzin** [comment]
@naydav, can you help me ?
How to validate cart_id? The length should be equal to 32, as in the standard implementation: http://joxi.ru/Dr8M0GMtozdgEm ? Or can it be smaller?

**Comment by naydav** [comment]
> @naydav, can you help me ?
> How to validate cart_id? The length should be equal to 32, as in the standard implementation: http://joxi.ru/Dr8M0GMtozdgEm ? Or can it be smaller?

yes + `\w\d+`
Thanks

**Comment by anzin** [comment]
@naydav , Thanks a lot for your help

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/610
