### ISSUE TITLE
[Mutations] My Account > Manage Gift Cards

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#61]
As a Magento developer, I need to build a functional My Account experience for customers via GraphQL so that I can build basic ecommerce experiences for shoppers on the front-end using only GraphQL.

GraphQL needs to provide sufficient mutations (ways to create/update/delete data) for a developer to build out the storefront My Account experience for a shopper.

**Use cases:**
- A logged-in shopper can redeem gift card (if it transfers to store credit) from My Account
- A logged-in shopper can check the status and balance of a gift card from My Account

**Acceptance criteria:**
- GraphQL provides a mutation through which the current logged-in shopper can redeem a gift card
- GraphQL provides a mutation through which the current logged-in shopper can check status and balance of a gift card
- Account authentication is handled through a session cookie (changing the email address requires that current password is provided)
- A guest shopper cannot change the data for any user
- Changes are covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.

**My Account area impacted:** 
- Gift Cards tab
![image](https://user-images.githubusercontent.com/18131925/40388103-36397da6-5dd4-11e8-9356-a496b4cc28ab.png)

**Comment by naydav** [comment]
EE functionality
