### ISSUE TITLE
Cart mutations return types that seem unnecessary

### ISSUE THREAD

**Issue by zetlen** [magento/graphql-ce#613]
### Summary (*)
@naydav kindly showed me this schema for review. It looks mostly good, but I have a couple of general concerns with it.

#### Cart IDs are not where we would expect them to be

All of the direct mutations on cart objects require a `cart_id` parameter, but the Cart type itself does not have an `id` property. This makes it hard for our client cache to recycle cart objects. It's also difficult for us to naturally store the `cart_id` in a local GraphQL cache, since there is no complex type that includes it. We would need to store the string response from `createEmptyCart` in a separate field in our cache. For this reason, I think that `Cart` should have an `id: ID!` member, `createEmptyCart` should respond with the new Cart object, and all of the IDs should be changed to the `ID!` type.

#### Cart mutations return redundant types

The [definitions of cart mutation operations](https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L9-L20) specify a special return type for each mutation. All of these return types are identical so far: [this group of types](https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L132-L154) and [this group of types](https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L237-L259) are both wrappers around `Cart`.

This adds weight to the schema and makes it more difficult to automate client code generation. It seems like all of these mutations should simply return the `Cart`. Did we add these types so that we could later add specific information about each operation to the response? If so, I recommend that we use a collection of cart messages on the Cart object to contain any metadata about recent operations, including the one the client just performed.

#### Addresses don't implement a common interface

I may not understand enough about the difference between billing and shipping addresses, but it seems like all the Address types ought to implement an `Address` interface, so that we can use generic components to render them.

Other than these comments, I think the schema looks great; the mutations are clearly named, they support our use cases, and it'll be great to use GraphQL instead of REST for our cart management.

**Comment by supernova-at** [comment]
Here is the [schema](https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/QuoteGraphQl/etc/schema.graphqls).

**Comment by supernova-at** [comment]
**Support for Configurable Products?**

`addSimpleProductsToCart` and `addVirtualProductsToCart` appear, but I don't see a `addConfigurableProductsToCart`.

**Can only update Quantity of Items?**

The [input](https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L58-L66) for `updateCartItems` appears to only support updating the `quantity`.

Often times configurable products want to change their configurable options as well.

**Quantity / Qty Inconsistency**

In some places `qty` is used ([CartItemInput](https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L45) and [CartItemInterface](https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L271)), and in other places it is expanded to the full word `quantity` ([CartItemQuantityInput](https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L65) and [CartItemQuantity](https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L186)).

**placeOrder**

Love the simplicity here and that there is one endpoint to call to place an order 💯 

**Cart Totals**

I notice that the [Cart type](https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L156) doesn't include anything about the total price (and neither do the `items` contained within).

**What is ProductInterface?**

The [CartItemInterface references a ProductInterface](https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L272) but I don't see a definition for it.

**Comment by naydav** [comment]
Hello @supernova-at,
Thanks for review

> Support for Configurable Products?

Located in separate module
https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/ConfigurableProductGraphQl/etc/schema.graphqls#L4

> Quantity / Qty Inconsistency

Good point. Thanks.

> placeOrder
> Love the simplicity here and that there is one endpoint to call to place an order

Now, this topic is under discussion. @akaplya could share more details.

> Cart Totals

Cart Prices were added today.
https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L132
But for items the price is missed, a ticket will be created

> What is ProductInterface?

Declaration is in https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/CatalogGraphQl/etc/schema.graphqls#L247
But now static test doesn't support dependencies in `graphql.scheme`

**Comment by tjwiebell** [comment]
There is an issue presently with the REST API, where after placing an Order you're given `order_id`, which is the internal id. For guest orders, there's nothing you can do with this ID non-auth'd, but at the very least it would be nice to display the external OrderId to the guest user on their checkout receipt that matches the order number they get in their email. Can we add the external order id to the Order type?

**Comment by paliarush** [comment]
Makes sense from my side. Requires product approval, @nrkapoor please approve.

**Comment by lenaorobei** [comment]
@tjwiebell in GraphQl resolver `order_id` is actually increment id.

https://github.com/magento/graphql-ce/blob/57ffbd948415822d134397699f69411b67bcf7bc/app/code/Magento/QuoteGraphQl/Model/Resolver/PlaceOrder.php#L81
