### ISSUE TITLE
[Cart Operation] Cannot Checkout as Guest

### ISSUE THREAD

**Issue by pmclain** [magento/graphql-ce#615]
### Preconditions (*)
1. Storefront with at least one product and guest checkout enabled.

### Steps to reproduce (*)
Using only graphql...
1. Create cart for guest
2. Add product to cart
3. Add cart shipping address
4. Set cart shipping method
5. Set cart billing address
6. Set cart payment method
7. Place order

Or execute tests added in #614 

### Expected result (*)
1. `placeOrder` mutation should return order increment id

### Actual result (*)
1. `Guest checkout currently fails with the error: `GraphQL response contains errors: Guest email for cart is missing. Please enter`

I don't see path for adding the guest email to a quote via graphql.

**Comment by pmclain** [comment]
A possible mutation for setting the email:
```graphql
type Mutation {
  setGuestCartEmail(input: SetGuestCartEmailInput): SetGuestCartEmailOutput
}

type SetGuestCartEmailInput {
  cart_id: String!
  email: String!
}

type SetGuestCartEmailOutput {
  cart: Cart!
}
```

**Comment by atwixfirster** [comment]
**Related PRs:**
- https://github.com/magento/graphql-ce/pull/564
- https://github.com/magento/graphql-ce/pull/404

CC: @rogyar
