### ISSUE TITLE
Cache invalidation for the FPC tag

### ISSUE THREAD

**Issue by cpartica** [magento/graphql-ce#618]
Some queries don't support caching because they're not tied to any entities, so invalidation could not be supported at this time.
Invalidation is tied to system configuration, that when is changed should invalidate the FPC tag, or some custom tag that represents configuration. 
Frontend does it, so should graphql. Note that FPC works differently in Varnish & Builtin.
Based on research tag FPC or CONFIG, the system doesn't invalidate this tag when system config is changed

Following queries must support caching based on this consideration:

storeConfig
currency
countries
country
customAttributeMetadata
isEmailAvailable - not related to system but still a system state.

### Preconditions (*)

1. Enable cache

### Steps to reproduce (*)

Query one of the queries listed above (eg:currency)

### Expected result (*)

Queries should be cached

### Actual result (*)

Queries are not cached, partially because we added the @nocache tag to them but also becase they have no tags assigned to them because we don't control the invalidation, so by definition, so far,  they're not cacheable

**Comment by cherdman** [comment]
Will be completed as part of https://jira.corp.magento.com/browse/MC-15962
