### ISSUE TITLE
Customer queries caching

### ISSUE THREAD

**Issue by cpartica** [magento/graphql-ce#619]
### Description (*)

Currently we don't cache any customer queries. We need to do this by leveraging the data that's public specific to the customer, part of the cache vary string. 
Currently we support only guest info, also part of the cache vary string:
 - Store View
 - Currency

We need to support:
Language preference
Customer Group (EE only)

### Expected behavior (*)

Cache all customer queries based on data that comes in the headers that maps 1-1 to context documented in devdocs about public data.

### Benefits

We could support caching for  50% of remaining queries

### Additional information

In order to do this the headless implementor must consume an endpoint that exposes this data when the customer logs in and requests a token, so additional data must be provided to the login query.

**Comment by cherdman** [comment]
Will be done as part of https://jira.corp.magento.com/browse/MC-15964
