### ISSUE TITLE
[Cart Operations] Set Shipping Address

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#62]
As a Magento developer, I need to manipulate the shopping cart via GraphQL so that I can build basic ecommerce experiences for shoppers on the front-end using only GraphQL.

GraphQL needs to provide sufficient mutations (ways to create/update/delete data) for a developer to build out the storefront checkout experience for a shopper.

**Use cases:**
- Both guest and registered shoppers can add and update the shipping and billing addresses on their cart in checkout

**Acceptance criteria:**
- GraphQL provides a mutation through which the shipping and billing addresses can be added/updated on a shopper's cart in checkout
- Changes are covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.

**Assumptions:** 
- A shopper cannot remove a shipping nor billing address on their cart once it is set

**My Account area impacted:** 
- Checkout
![image](https://user-images.githubusercontent.com/18131925/40389039-e5b50b04-5dd6-11e8-97ca-c767d32c4497.png)
![image](https://user-images.githubusercontent.com/18131925/40389083-01c3f7ce-5dd7-11e8-80b4-82047f5bc94b.png)

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/391
