### ISSUE TITLE
Implement GQL cache

### ISSUE THREAD

**Issue by cpartica** [magento/graphql-ce#620]
### Description (*)

Currently GraphQL cache works with FPC, like the frontend
We need to implement and decouple it into having it's own cache

### Expected behavior (*)

Caching for graphql must work independently from full page cache in frontend

### Benefits

Dispatch method can have a Response interface result, while now uses a frontend Result, to keep compatibility with all frontend, and interface is not clear.
This requires some boilerplate code that in most cases would be similar to frontend cache, but with a different cache, eg: GQLC tag instead of FPC and a separate configuration that can be turned on and off, 
could even support different integration of caching only for graphql

**Comment by cherdman** [comment]
Will be done as part of https://jira.corp.magento.com/browse/MC-15965
