### ISSUE TITLE
Separate Graphql cache handing  in VCL for the /graphql area

### ISSUE THREAD

**Issue by cpartica** [magento/graphql-ce#623]
### Summary (*)

VCL files for graphql caching are mixed with FPC caching. We should make a separate section for addressing "/graphql" varnish request and header handling that doesn't mix with FPC.
### Examples (*)

FPC is using cache vary cookie and we don't support it on Graphql. If the client sends it varnish will process it and generate a different cache key.
Example would be if client sends a cache vary cookie, varnish would interpret it and we don't want that.

### Proposed solution

Separate graphql and FPC caching in the VCL files
While this is related with issue #620 it can be delivered separately

**Comment by cherdman** [comment]
Done as part of https://jira.corp.magento.com/browse/MC-15960
