### ISSUE TITLE
Implement caching for url resolver

### ISSUE THREAD

**Issue by cpartica** [magento/graphql-ce#624]
### Description (*)

In current implementation urlResolver query is not cacheable. This can be easily achievable as the only entities that are catalog & cms for which we already have an invalidation strategy.

### Expected behavior (*)

urlResolver should be cacheable using tags cat_p, cat_c, cms_p, cms_b

### Benefits

urlResolver query is widely used in the PWA headless implementation so by leveraging cache, performance & rendering would be improved.

### Additional information

Implement a cache resolver and return dynamically one of the tags by appending the id of the entity to the type of the url resolved.
It will require to create a composite resolver and provide this code in 3 modules, url rewrites, catalog & cms

**Comment by cherdman** [comment]
Will be done as part of https://jira.corp.magento.com/browse/MC-15959
