### ISSUE TITLE
Provide hints through validation/introspection for postcode like on frontend area

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#629]
When GraphQL consumer starts typing `country_id` value for `updateCustomerAddress` mutation he has autocomplete and validation messages that helps a lot.
![image](https://user-images.githubusercontent.com/11827230/56666802-3bce4b80-66b5-11e9-9fc8-9cdd12e4a5b5.png)

On front-end area we also have validation that looks like:
![image](https://user-images.githubusercontent.com/11827230/56666495-b054ba80-66b4-11e9-968f-a993694600c8.png)

### Expected result (*)

1. Hint about proper postcode for India

### Actual result (*)

1. 
![image](https://user-images.githubusercontent.com/11827230/56667659-e5faa300-66b6-11e9-83c2-f397c0790b71.png)

**Comment by naydav** [comment]
It's developer experience issue caused by implementation by graphiql and we have not any influence over it
