### ISSUE TITLE
[Cart Operations] Coupons

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#64]
As a Magento developer, I need to manipulate the shopping cart via GraphQL so that I can build basic ecommerce experiences for shoppers on the front-end using only GraphQL.

GraphQL needs to provide sufficient mutations (ways to create/update/delete data) for a developer to build out the storefront checkout experience for a shopper.

**Use cases:**
- Both guest and registered shoppers can add and remove coupon codes to/from their shopping cart

**Acceptance criteria:**
- Proposed schema is [here](https://github.com/magento/architecture/pull/15/files)
- GraphQL provides a mutation through which the coupons can be added/removed on a shopper's cart in checkout
- When a coupon is already applied to the cart and user tries to apply another, give an error message: "A coupon is already applied to the cart. Please remove it to apply another." 
- Changes are covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.

**Assumptions:** 
- A coupon cannot be updated in place (only removed and re-added)
- A cart can have only one coupon applied at any time (Cannot add multiple coupon codes to the same cart)

**My Account area impacted:** 
- Cart

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/163
