### ISSUE TITLE
Input type declaration in GraphQL SDL cannot be empty

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#640]
The problem is on [#L265](https://github.com/magento/graphql-ce/blob/d1a39c661b8b2054570c0bdbd542c1b09db286e0/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L265) and on [#L137](https://github.com/magento/graphql-ce/blob/d1a39c661b8b2054570c0bdbd542c1b09db286e0/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L137)

### Preconditions (*)

1. No preconditions

### Steps to reproduce (*)

1. `php bin/magento dep:mod:set production`
2. Open GraphQL client and read the documentation

### Expected result (*)

1. Documentation loads without errors

### Actual result (*)

1. Error
```
app.b7ae4eb6fb0db4c81377.js:134868 Uncaught SyntaxError: Syntax Error: Expected Name, found } (3148:1)
  3146 | input PaymentMethodAdditionalDataInput {
  3147 | 
> 3148 | }
       | ^
  3149 | 
  3150 | input PaymentMethodInput {
  3151 |   """Additional payment data"""
```

**Comment by VitaliyBoyko** [comment]
Hi @naydav 
What should I put there :)?

**Comment by naydav** [comment]
@VitaliyBoyko 
Did you check? Does this solve the problem if you put some dummy parameter in the scheme?

**Comment by VitaliyBoyko** [comment]
@naydav seems like removing curly braces has fixed the issue.

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/648

**Comment by LuciferStrome** [comment]
#dmcdindia1
