### ISSUE TITLE
Incorrect name of Selected Shipping Method

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#646]
The easier way to reproduce a bug is adding assert to current API-functional tests
```
\Magento\GraphQl\Ups\SetUpsShippingMethodsOnCartTest

public function testSetUpsShippingMethod(string $methodCode, string $methodTitle) {
    self::assertEquals($methodTitle, $shippingAddress['selected_shipping_method']['method_title']);
}
```

Actual result: method title is incorrect ('1GDN')
Expected result: method title is equal to `$methodTitle`

**Comment by atwixfirster** [comment]
**Pull request:** https://github.com/magento/graphql-ce/pull/647

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/647
