### ISSUE TITLE
GetSpecifiedBillingAddressTest fix misspelling

### ISSUE THREAD

**Issue by atwixfirster** [magento/graphql-ce#649]
### Summary (*)
We have misspelling issues in the functions names of the next tests:
1. `dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/GetSpecifiedBillingAddressTest.php`
2. `dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/GetSpecifiedBillingAddressTest.php`

### Examples (*)
1. `dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/GetSpecifiedBillingAddressTest.php`
- testGeSpecifiedBillingAddress()
- testGeSpecifiedBillingAddressIfBillingAddressIsNotSet()

2. `dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/GetSpecifiedBillingAddressTest.php`
- testGeSpecifiedBillingAddress()
- testGeSpecifiedBillingAddressIfBillingAddressIsNotSet()
- testGeSpecifiedBillingAddressOfNonExistentCart()
- testGeSpecifiedBillingAddressFromAnotherGuestCart()
- testGeSpecifiedBillingAddressFromAnotherCustomerCart()

### Proposed solution
1. `dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/GetSpecifiedBillingAddressTest.php`
- testGe`t`SpecifiedBillingAddress()
- testGe`t`SpecifiedBillingAddressIfBillingAddressIsNotSet()

2. `dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/GetSpecifiedBillingAddressTest.php`
- testGe`t`SpecifiedBillingAddress()
- testGe`t`SpecifiedBillingAddressIfBillingAddressIsNotSet()
- testGe`t`SpecifiedBillingAddressOfNonExistentCart()
- testGe`t`SpecifiedBillingAddressFromAnotherGuestCart()
- testGe`t`SpecifiedBillingAddressFromAnotherCustomerCart()

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/651
