### ISSUE TITLE
[Mutations] Cart Operations > Gift Cards

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#65]
As a Magento developer, I need to manipulate the shopping cart via GraphQL so that I can build basic ecommerce experiences for shoppers on the front-end using only GraphQL.

GraphQL needs to provide sufficient mutations (ways to create/update/delete data) for a developer to build out the storefront checkout experience for a shopper.

**Use cases:**
- Both guest and registered shoppers can add and remove gift cards to/from their shopping cart

**Acceptance criteria:**
- GraphQL provides a mutation through which gift cards can be added/removed to/from a shopper's cart in checkout
- Changes are covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.

**Assumptions:** 
- Gift cards cannot be updated in place (only removed and re-added)

**My Account area impacted:** 
- Cart
- Checkout

**Comment by naydav** [comment]
EE functionality
