### ISSUE TITLE
Integration test "testToCheckCmsPageRequestCacheTags" is failed

### ISSUE THREAD

**Issue by vpodorozh** [magento/graphql-ce#654]
### Preconditions (*)
1. GraphQl repo
2. "2.3-develop" branch is used

### Steps to reproduce (*)
Execute the next integration test: `\Magento\GraphQlCache\Controller\Cms\CmsPageCacheTest::testToCheckCmsPageRequestCacheTags`
### Expected result (*)
Test is passed;

### Actual result (*)
Test is failed;

> 1) Magento\GraphQlCache\Controller\Cms\CmsPageCacheTest::testToCheckCmsPageRequestCacheTags
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
\-    0 => 'cms_p'
\-    1 => 'cms_p_5'
\-    2 => 'FPC'
\+    0 => 'FPC'

UPD: raw log of failed travis build for this PR #585 with current problem [log.txt](https://github.com/magento/graphql-ce/files/3139835/log.txt)

**Comment by avattam06** [comment]
@vpodorozh Are you in developer mode and all remaining tests are passing?

**Comment by vpodorozh** [comment]
@avattam06 - I am in developer mode, however, I have not executed all other tests locally.
For full integration tests suite execution, you can check this travis build: https://travis-ci.org/magento/graphql-ce/builds/526610867?utm_source=github_status&utm_medium=notification from this PR #585

**Comment by vpodorozh** [comment]
Seems that this failed test caused by changes in cache tag policy for cms page in Magento core that has come into GraphQl while fork update.

**Comment by avattam06** [comment]
@vpodorozh, Thanks for the info. We are working on refactoring this test as part of another story and will merge it soon.

**Comment by naydav** [comment]
@avattam06 
Please, share a link to the story for more transparency
Thanks

**Comment by avattam06** [comment]
Fixed in MC-15959.
