### ISSUE TITLE
Split QuoteGraphQl module into QuoteGraphQl and CheckoutGraphQl

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#659]
Need to split QuoteGraphQl module into QuoteGraphQl and CheckoutGraphQl

QuoteGraphQl: create cart, cart item operations, coupons, custom options
CheckoutGraphQl: shippings, payments, place order

Api-functional tests also should be split

**Comment by moloughlin** [comment]
PR: https://github.com/magento/graphql-ce/pull/704
