### ISSUE TITLE
[Cart Operations] Fetch registered shopper cart

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#66]
As a Magento developer, I need to fetch the shopping cart via GraphQL so that I can build basic ecommerce experiences for shoppers on the front-end using only GraphQL.

As an iteration of GraphQL support for cart, expose registered shopper cart query using resolver based on service contracts.

References:
- [How to expose a new query via GraphQL in Magento](https://devdocs.magento.com/guides/v2.3/graphql/develop/create-graphqls-file.html)
- TODO: specify equivalent registered shopper interface: 
[\Magento\Quote\Api\GuestCartRepositoryInterface::get](https://github.com/magento/magento2/blob/b2ce2a37d921b5ad88fc38663fc0ff3dd6c582d1/app/code/Magento/Quote/Api/GuestCartRepositoryInterface.php#L22)

**Acceptance Criteria**:
1. It is possible, using GraphQL, to query information about the cart created via REST APIs
1. Changes are covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.
1. Appropriate documentation is updated in DevDocs

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/266
