### ISSUE TITLE
[Test coverage] Is customer email available for registration

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#673]
Need to cover with API-functional tests cases in 
```
isEmailAvailable (
        email: String! @doc(description: "The new customer email")
    ): IsEmailAvailableOutput @resolver(class: "Magento\\CustomerGraphQl\\Model\\Resolver\\IsEmailAvailable")
```

Test cases:
```
\Magento\GraphQl\Customer\IsEmailAvailableTest
- testIsEmailAvailable (positive scenario)
- testIsEmailAvailableWithInvalidEmail (email parameter is not set, email parameter is missed, email parameter is invalid)
```

Examples:
https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Customer
https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer

Guide:
https://devdocs.magento.com/guides/v2.3/graphql/functional-testing.html

**Comment by moloughlin** [comment]
Note: Also added email validation on the isEmailAvailable query which was previously missing (and hence untestable).

https://github.com/magento/graphql-ce/pull/706

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/706
