### ISSUE TITLE
[Test coverage] Generate customer token

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#675]
Need to cover with API-functional tests cases in 
```
generateCustomerToken(email: String!, password: String!): CustomerToken @resolver(class: "\\Magento\\CustomerGraphQl\\Model\\Resolver\\GenerateCustomerToken") @doc(description:"Retrieve the customer token")
```

Test cases:
```
\Magento\GraphQl\Customer\GenerateCustomerTokenTest
- testGenerateCustomerTokenWithInvalidEmail (email is missed, email is empty)
- testGenerateCustomerTokenWithInvalidPassword (password is missed, password is empty)
- testRegenerateCustomerToken (should be different from initial token)
```

Examples:
https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Customer
https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer

Guide:
https://devdocs.magento.com/guides/v2.3/graphql/functional-testing.html

**Comment by atwixfirster** [comment]
Pull request: https://github.com/magento/graphql-ce/pull/677

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/677
