### ISSUE TITLE
[Test coverage] Send email to friend

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#678]
Need to cover with API-functional tests cases in 
```
sendEmailToFriend (input: SendEmailToFriendInput): SendEmailToFriendOutput @resolver(class: "\\Magento\\SendFriendGraphQl\\Model\\Resolver\\SendEmailToFriend") @doc(description:"Recommends Product by Sending Single/Multiple Email")
```

Test cases:
```
\Magento\GraphQl\SendFriend\SendFriendTest
- sender email is missed/empty
- send product which is not visible in catalog
```
Also, need to fix Code Style of this class

Examples:
https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Customer
https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer

Guide:
https://devdocs.magento.com/guides/v2.3/graphql/functional-testing.html

**Comment by naydav** [comment]
@TomashKhamlai @lenaorobei 
Looks like `- send product which is not visible in catalog` should be negative (we should not send product if it is not visible on frontend)
@TomashKhamlai please check this case

**Comment by TomashKhamlai** [comment]
magento/magento2#23053

**Comment by TomashKhamlai** [comment]
Mainline got fixes. It is time to update the test.

**Comment by naydav** [comment]
So, need to fix case 
https://github.com/magento/graphql-ce/blob/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/SendFriend/SendFriendTest.php#L210

It should be negative. Need to investigate why this test is green and fix the issue.

**Comment by rleshchenko** [comment]
#kharkiv2019

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/752
