### ISSUE TITLE
[Test coverage] Missed parameters at 'setBillingAddressMutation'

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#682]
Need to cover with API-functional tests cases in 
```
setBillingAddressOnCart(input: SetBillingAddressOnCartInput): SetBillingAddressOnCartOutput @resolver(class: "\\Magento\\QuoteGraphQl\\Model\\Resolver\\SetBillingAddressOnCart")
```

Test cases:
```
\Magento\GraphQl\Quote\Customer\SetBillingAddressOnCartTest
-  testSetBillingAddressWithoutRequiredParameters (add case to dataprovider when `customer_address_id` and `address` are empty at the same time)

\Magento\GraphQl\Guest\Customer\SetBillingAddressOnCartTest
-  testSetBillingAddressWithoutRequiredParameters (add case to dataprovider when `customer_address_id` and `address` are empty at the same time)
```

Testcase which cover case in `\Magento\QuoteGraphQl\Model\Cart\SetBillingAddressOnCart::execute`:
```
if ($useForShipping && count($addresses) > 1) { 
throw new GraphQlInputException(__('Using the "use_for_shipping" option with multishipping is not possible.'));
}
```

Examples:
https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer
https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest

Guide:
https://devdocs.magento.com/guides/v2.3/graphql/functional-testing.html

**Comment by sergiy-v** [comment]
Pull request: #700

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/700
