### ISSUE TITLE
Extract logic related to customer from DownloadableGraphQl module into new one

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#685]
1. Need to introduce new module `CustomerDownloadableGraphQl `
2. Move from `DownloadableGraphQl` scheme to `CustomerDownloadableGraphQl `
```
type Query {
    customerDownloadableProducts: CustomerDownloadableProducts @resolver(class: "Magento\\DownloadableGraphQl\\Model\\Resolver\\CustomerDownloadableProducts") @doc(description: "The query returns the contents of a customer's downloadable products") @cache(cacheable: false)
}
```
3. Move corresponding logic to new module
4. Cover new module with API-functional tests cases:
```
\Magento\GraphQl\CustomerDownloadable\CustomerDownloadableProductsTest
-  testGetCustomerDownloadableProducts
-  testGetCustomerDownloadableProductsIfProductsAreNotExists 
- testGetCustomerDownloadableProductsByGuest
```
Examples:
https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer
https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest

Guide:
https://devdocs.magento.com/guides/v2.3/graphql/functional-testing.html

**Comment by naydav** [comment]
Hi @larsroettig,
Do you have some updates on this ticket?
Thanks

**Comment by larsroettig** [comment]
I started - WIP finish I can next week I have to finish one release for a customer

**Draft PR:**
https://github.com/magento/graphql-ce/pull/754
