### ISSUE TITLE
Remove extra quotation sign

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#686]
### Preconditions (*)

1. No preconditions

### Steps to reproduce (*)

1. No steps

### Expected result (*)

1. [IsEmailAvailable.php#L47](https://github.com/magento/graphql-ce/blob/c2012388eb962a0e8d27278766ed87bb4192f3dc/app/code/Magento/CustomerGraphQl/Model/Resolver/IsEmailAvailable.php#L47)
```php
throw new GraphQlInputException(__('Email must be specified'));
```
2. [UpdateCustomerAddress.php#L73](https://github.com/magento/graphql-ce/blob/c2012388eb962a0e8d27278766ed87bb4192f3dc/app/code/Magento/CustomerGraphQl/Model/Resolver/UpdateCustomerAddress.php#L73)
```php
throw new GraphQlInputException(__('Address "id" value must be specified'));
```
3. [UpdateCustomerAddress.php#L77](https://github.com/magento/graphql-ce/blob/c2012388eb962a0e8d27278766ed87bb4192f3dc/app/code/Magento/CustomerGraphQl/Model/Resolver/UpdateCustomerAddress.php#L77)
```php
throw new GraphQlInputException(__('"input" value must be specified'));
```

### Actual result (*)

1. [IsEmailAvailable.php#L47](https://github.com/magento/graphql-ce/blob/c2012388eb962a0e8d27278766ed87bb4192f3dc/app/code/Magento/CustomerGraphQl/Model/Resolver/IsEmailAvailable.php#L47)
```php
throw new GraphQlInputException(__('"Email should be specified'));
```
2. [UpdateCustomerAddress.php#L73](https://github.com/magento/graphql-ce/blob/c2012388eb962a0e8d27278766ed87bb4192f3dc/app/code/Magento/CustomerGraphQl/Model/Resolver/UpdateCustomerAddress.php#L73)
```php
throw new GraphQlInputException(__('Address "id" value should be specified'));
```
3. [UpdateCustomerAddress.php#L77](https://github.com/magento/graphql-ce/blob/c2012388eb962a0e8d27278766ed87bb4192f3dc/app/code/Magento/CustomerGraphQl/Model/Resolver/UpdateCustomerAddress.php#L77)
```php
throw new GraphQlInputException(__('"input" value should be specified'));
```

**Comment by TomashKhamlai** [comment]
@naydav, please set estimation points.

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/695
