### ISSUE TITLE
Redundant 'isset' should be omitted in resolvers

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#687]
### Acceptance Criteria
Eliminate redundant `!isset` in `CustomerGraphQl` and `QuoteGraphQl` resolvers.
```php
if (!isset($args['arg']) || empty($args['arg']))
```
Use `empty($args['arg'])` instead.

**Comment by TomashKhamlai** [comment]
@naydav, please validate (change labels if needed) and unassign issue

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/749
