### ISSUE TITLE
Remove type casting if redundant

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#688]
### Preconditions (*)

1. No preconditions

### Steps to reproduce (*)

1. No steps

### Expected result (*)

1. [GetCustomer.php#L116](https://github.com/magento/graphql-ce/blob/c2012388eb962a0e8d27278766ed87bb4192f3dc/app/code/Magento/CustomerGraphQl/Model/Customer/GetCustomer.php#L116) has no redundancy type casting

### Actual result (*)

1. Everything works but could work faster

**Comment by TomashKhamlai** [comment]
@naydav, please validate and unassign issue

**Comment by naydav** [comment]
Was fixed and merged in the scope of 
https://github.com/magento/graphql-ce/pull/714/files#diff-b1547c1e44db103f077782d2f80856fd
