### ISSUE TITLE
Wishlist description coverage

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#692]
### Description:

The schema is provided:
```graphql
type WishlistItem {
    id: Int @doc(description: "The wish list item ID")
    qty: Float @doc(description: "The quantity of this wish list item"),
    description: String @doc(description: "The customer's comment about this item"),
    added_at: String @doc(description: "The time when the customer added the item to the wish list"),
    product: ProductInterface @resolver(class: "\\Magento\\WishlistGraphQl\\Model\\Resolver\\ProductResolver")
}
```
but `description` is not implemented

**Comment by TomashKhamlai** [comment]
Hi, @mallikaverma. I've invited you to join #magento #graphql slack channel. I hope you don't mind it.
Please visit our [dashboard](https://github.com/magento/graphql-ce/projects). You can get more information on how to use it in our slack channel (pinned messages).

**Comment by mallikaverma** [comment]
#imagine2019

**Comment by TomashKhamlai** [comment]
Hi @mallikaverma! Are you working on this issue?

**Comment by naydav** [comment]
Hi @mallikaverma ,
Unfortunately, I need to unassign the ticket because still no response from you.

**Comment by larsroettig** [comment]
Hi @TomashKhamlai @naydav,
`description` is implemented and works fine.  I think we close these issue correct?

Used Query:
```
query{
  wishlist{
    updated_at,
    items{
      id,
      product{
        sku
      },
      description,
    }
  }
}
```
![GraphQL_Playground](https://user-images.githubusercontent.com/5289370/59852173-9a8b0b00-936e-11e9-8933-c92f72b57d15.png)

**Comment by naydav** [comment]
Closed according to the last comment from @larsroettig.
Thanks
