### ISSUE TITLE
url_path is not working as documented 

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#713]
### Preconditions (*)

1. Simple Product is created and assigned to the category "sale"

### Steps to reproduce (*)

1. Perform query
```graphql
{
  products(
    search: "simple"
    filter: {
      sku: {
        eq: "simple"
      }
    }
  ) {
    items {
      type_id
      sku
      name
      url_key
      url_path
      canonical_url
      url_rewrites {
        url
        url
      }
    }
    total_count
  }
}
```

### Expected result (*)

1. Works according to [documentation](https://devdocs.magento.com/guides/v2.3/graphql/reference/products.html)

Attribute | Data Type | Description
--- | --- | ---
`url_path` | String | The part of the URL that precedes the url_key. </br> This attribute is defined in the CatalogUrlRewrite module

### Actual result (*)

1. Response:
```graphql
{
  "data": {
    "products": {
      "items": [
        {
          "type_id": "simple",
          "sku": "simple",
          "name": "simple",
          "url_key": "simple",
          "url_path": null,
          "canonical_url": "http://graph-sd.io/simple.html",
          "url_rewrites": [
            {
              "url": "simple.html"
            },
            {
              "url": "sale/simple.html"
            }
          ]
        }
      ],
      "total_count": 1
    }
  }
}
```

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/721
