### ISSUE TITLE
[2.3.2 REGRESSION] Configurable Product Result w/ UrlKey Filter

### ISSUE THREAD

**Issue by tjwiebell** [magento/graphql-ce#715]
### Preconditions (*)

1. Magento 2.3.2
2. Configurable Product w/ a few variations 

### Steps to reproduce (*)

1. Execute the below query and filter by `urlKey` of configurable product

```gql
query productDetail($urlKey: String) {
    productDetail: products(filter: { url_key: { eq: $urlKey } }) {
        items {
            __typename
            sku
            name
            price {
                regularPrice {
                    amount {
                        currency
                        value
                    }
                }
            }
            description {
                html
            }
            media_gallery_entries {
                label
                position
                disabled
                file
            }
        }
    }
}
```

### Expected result (*)

1. Configurable Product is returned

### Actual result (*)

1. SimpleProduct variants are returned along with ConfigurableProduct

### Debugging Note
Removing the `media_gallery_entries` join appears to return the result set to normal, but this is not a viable work around for PWA.

**Comment by TomashKhamlai** [comment]
Hi @tjwiebell. I writing to you to clarify the conditions. I've installed sample-data and tried this request:
```graphql
query productDetail(
  $urlKey: String = "zoe-tank"
) {
  productDetail: products(
    filter: {
      url_key: {
        eq: $urlKey
      }
    }
  ) {
    total_count
    items {
      __typename
      sku
      name
      price {
        regularPrice {
          amount {
            currency
            value
          }
        }
      }
      description {
        html
      }
      media_gallery_entries {
        label
        position
        disabled
        file
      }
    }
  }
}
```
and got this response:
```graphql
{
  "data": {
    "productDetail": {
      "total_count": 1,
      "items": [
        {
          "__typename": "ConfigurableProduct",
          "sku": "WT02",
          "name": "Zoe Tank",
          "price": {
            "regularPrice": {
              "amount": {
                "currency": "USD",
                "value": 29
              }
            }
          },
          "description": {
            "html": "<p>The Zoe Tank leads with eye-catching fitness-pop looks, keeping your studio style uptrend. The inner shelf bra and soft, breathable fabric create a tank top that looks, feels and fits great.</p>\n<p>&bull; Salmon heather tank top.<br />&bull; 1\" elastic band on inner bra.<br />&bull; Mesh lining on shelf bra for support.<br />&bull; Soft, breathable fabric.<br />&bull; Dry wick fabric to stay cool and dry.</p>"
          },
          "media_gallery_entries": [
            {
              "label": "",
              "position": 1,
              "disabled": false,
              "file": "/w/t/wt02-orange_main_1.jpg"
            },
            {
              "label": "",
              "position": 2,
              "disabled": false,
              "file": "/w/t/wt02-orange_back_1.jpg"
            }
          ]
        }
      ]
    }
  }
}
```
The total count is 1. The `media_gallery_entries` are the same as on admin edit product page.
Magento instance was installed from git and is up to date with this commit `211dd25c73bb2539c3c064374d9d5649f253fd14`.

Could you please add more details? The most important is the response body. (Other details: git commit/tag or if installed from the composer, then which modules were additionally enabled Vertex, MSI... etc.).

It would be awesome if you could provide Mftf test for this case or bash script for us :)

**Comment by danielrenaud** [comment]
@TomashKhamlai The issue happens when the parent product and the variation have the same urlKey. It also happens for other fields like name. We are already working on this issue internally.
I'm going to assign it to myself and update this ticket when we resolve the internal ticket.
Thanks for taking the time to look into it.

**Comment by tjwiebell** [comment]
Re-tested on the latest `2.3.2-develop` and the issue appears to be resolved now. Thank you @danielrenaud!
