### ISSUE TITLE
null and empty string should be semantically equal for search, but internal server error occurred for empty string 

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#720]
This issue has 2 two aspects:
1) Internal Server Error should be replaced with the content of the debugging message. (good first issue)
2) It feels like there are some problems in the schema because the search string can be skipped so that only filtering by attributes is used, or even can be set to `null` (thinking that it's the same) but an empty string results in an error.

### Preconditions (*)

1. Sample Data installed or some products are created

### Steps to reproduce (*)

1. Search:
```graphql
{
  products(
    search: ""
    filter: {
      sku: {
        eq : "WT02"
      }	
    }
  ) {
    items {
      sku
      ... on ConfigurableProduct {
        canonical_url
        options {
          option_id
          required
          sort_order
          title
          __typename
        }
        product_links {
          sku
        }
      }
    }
  }
}
```

### Expected result (*)

1. `The request query and filters aren't set. Verify the query and filters and try again.`

### Actual result (*)

1. Error:
```graphql
{
  "errors": [
    {
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "products"
      ]
    }
  ],
  "data": {
    "products": null
  }
}
```

**Comment by pmclain** [comment]
I'm fairly sure this is resolved here https://github.com/magento/graphql-ce/pull/304/files#diff-9474cfb5bac8ff8a44d8df121bd593a3R63

**Comment by TomashKhamlai** [comment]
@XxXgeoXxX, there is one left that needs a fix.

One or more spaces in the search field.
```graphql
{
  products(
    search: "   "
    filter: {
      price: {
        gt: "90"
      }
    }
  ) {
    items {
      sku
      ... on ConfigurableProduct {
        canonical_url
        options {
          option_id
          required
          sort_order
          title
          __typename
        }
        product_links {
          sku
        }
      }
    }
  }
}
```

**Comment by naydav** [comment]
Closed due to
https://github.com/magento/graphql-ce/issues/735
https://github.com/webonyx/graphql-php/issues/497
