### ISSUE TITLE
rest api & graphql endpoints are returning 404 for bots

### ISSUE THREAD

**Issue by mkum73** [magento/graphql-ce#728]
### Summary (*)
Request any api from browser 
<Domain.com>/rest/V1/store/storeConfigs
It's working fine when requested as user for it returns 404 when requested as googlebot. 
what is blocking these calls?

**Comment by lenaorobei** [comment]
@mkum73, this GitHub issue tracker is intended for Magento GraphQL technical issues only.

Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
