### ISSUE TITLE
Guest User can SendFriend products ignoring restrictions

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#732]
### Preconditions (*)

1. Navigate to Stores > Settings > Configuration > Catalog > Email to a Friend > Email Templates and verify that Allow for Guests is disabled by default

### Steps to reproduce (*)

1. Use `sendEmailToFriend`

### Expected result (*)

1. The authorization token is mandatory

### Actual result (*)

1. Works the same as for registered Customer

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/734
