### ISSUE TITLE
Introduce mock for Fedex shipping testing

### ISSUE THREAD

**Issue by lenaorobei** [magento/graphql-ce#740]
### Description (*)
Instead of real calls to the carrier service we need to introduce mock object that will return expected info.

### Additional information
1. Introduce new test module under `dev/tests/api-functional/_files/Magento`.
2. Module will serve for other carriers as well.
3. Declare preference in `di.xml` for `Magento\Fedex\Model\Carrier`.
4. Instead of real call to the gateway, return expected info.
5. Undo skipped tests `Magento\GraphQl\FedEx\SetFedExShippingMethodsOnCartTest` https://github.com/magento/graphql-ce/issues/661

See https://github.com/magento/graphql-ce/issues/739 for details

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/755
