### ISSUE TITLE
Empty PaymentMethodAdditionalDataInput causes schema invalidation

### ISSUE THREAD

**Issue by lenaorobei** [magento/graphql-ce#751]
### Steps to reproduce (*)
Set GraphQL endpoint in using Chrome extension.
https://devdocs.magento.com/guides/v2.3/graphql/

### Expected result (*)
Valid scheme. Documentation explorer allows scheme navigation. 

### Actual result (*)
`Error: PaymentMethodAdditionalDataInput fields must be an object with field names as keys or a function which returns such an object.`
Documentation explorer says `NO SCHEMA AVAILABLE`.

### ToDo:
- remove [PaymentMethodAdditionalDataInput](https://github.com/magento/magento2ce/blob/2.3-develop/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L137);
- change backend implementation.

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/757
