### ISSUE TITLE
Cart applied_taxes of empty cart causes 'Internal server error' message on PHP 7.2

### ISSUE THREAD

**Issue by therealtbs** [magento/graphql-ce#758]
### Preconditions (*)

1. PHP 7.2.18
2. Magento 2.3.2

### Steps to reproduce (*)

1. Create an empty cart
```graphql
mutation {
  createEmptyCart
}
```
2. Retrieve that cart without adding any products
```graphql
{
  cart(cart_id: "CARTID") {
    prices {
      grand_total {
        value
      }
      applied_taxes {
        amount {
          value
        }
      }
    }
  }
}
```

### Expected result (*)

```json
{
  "data": {
    "cart": {
      "prices": {
        "grand_total": {
          "value": 0
        },
        "applied_taxes": []
      }
    }
  }
}
```

### Actual result (*)

```json
{
  "errors": [
    {
      "debugMessage": "Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/vendor/magento/module-quote-graph-ql/Model/Resolver/CartPrices.php on line 75",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "cart",
        "prices"
      ]
    }
  ],
  "data": {
    "cart": {
      "prices": null
    }
  }
}
```

https://github.com/magento/graphql-ce/blob/21b3cafa7e2c2acea150d6555f23906e2872db61/app/code/Magento/QuoteGraphQl/Model/Resolver/CartPrices.php#L76

At this point $appliedTaxes is NULL and therefore not countable. From PHP 7.2 onwards there is a warning generated which I assume Magento turns into a Throwable.

Since the fix is quite easy I'm not sure if I should make a PR for this.

**Comment by pmclain** [comment]
@therealtbs thanks for pointing out. Would you like to submit a PR to fix? If not I can this weekend.

**Comment by therealtbs** [comment]
Sure, I'll get it going first thing tomorrow.
