### ISSUE TITLE
[Customizable Options] Call to a member function format() on boolean

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#761]
### Preconditions (*)

1. Simple Product is created:
SKU: simple-product-1
qty: 100500
Customizable options:
type: date

### Steps to reproduce (*)

1. Perform query for Customer and use header
**Header:**
```json
{
  "Authorization": "Bearer {{ CUSTOMER_TOKEN }}"
}
```
**Query:**
```graphql
mutation {
  addSimpleProductsToCart(
    input: {
      cart_id: "{{ CART_ID }}"
      cart_items: {
        data: {
          quantity: 1
          sku: "simple-product-3"
        }
        customizable_options: [
          {
            id: 1
            value_string: "12-12-12"
          }
        ]
      }
    }
  ) {
    cart {
      items {
        quantity
        product {
          sku
        }
      }
    }
  }
}
```

### Expected result (*)

1. Product was added to cart

### Actual result (*)

1. Error:
```graphql
{
  "errors": [
    {
      "debugMessage": "Call to a member function format() on boolean",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addSimpleProductsToCart"
      ]
    }
  ],
  "data": {
    "addSimpleProductsToCart": null
  }
}
```

**Comment by sedonik** [comment]
Hi @TomashKhamlai,

I've created [PR](https://github.com/magento/graphql-ce/pull/771) with changes to the code. It should fix the problem. Please check. 

Thanks.

**Comment by lenaorobei** [comment]
@TomashKhamlai we discussed this issue with @naydav and think that the expected behaviour here is the error message like `Invalid format provided. Please use 'Y-m-d' for 'date' type.` The same for `date-time` and `time`. It looks more obvious than format data and guess its type under the hood.
