### ISSUE TITLE
Subscribe for newsletter even when not allowed

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#762]
### Preconditions (*)

1. No preconditions

### Steps to reproduce (*)

1. Navigate to Stores > Settings > Configuration > Customers > Newsletter
2. In the **General Options** set **Enabled** to **No**
3. Save config and Flush Cache
4. Navigate to frontend and verify that footer doesn't contain button subscribe when the user is Guest. (I mean that subscription is disabled completely despite the default config setting **Allow Guest Subscription** is set to **Yes** and is visible). Click on "Create the Account" link in the header section and verify that checkbox for subscribing also disappeared.
5. Perform query:
```graphql
mutation {
  createCustomer(
    input: {
      firstname: "John"
      lastname: "Lennon"
      email: "john.lennon@thebeatles.com"
      is_subscribed: true
    }
  ) {
    customer {
      email
      is_subscribed
    }
  }
}
```

### Expected result (*)

1. Rsponse:
```graphql
{
  "data": {
    "createCustomer": {
      "customer": {
        "email": "john.lennon@thebeatles.com",
        "is_subscribed": false
      }
    }
  }
}
```
or even
```graphql
{"errors": [
   {
        "message": "Some message like\: you cannot subscribe now, please try to subscribe later or call to customer support",
         "category": "...", "locations": "...", "path": "..."
   }
],
  "data": {
    "createCustomer": {
      "customer": {
        "email": "john.lennon@thebeatles.com",
        "is_subscribed": false
      }
    }
  }
}
```

### Actual result (*)

1. Response:
```graphql
{
  "data": {
    "createCustomer": {
      "customer": {
        "email": "john.lennon@thebeatles.com",
        "is_subscribed": true
      }
    }
  }
}
```

#35

**Comment by sedonik** [comment]
Hi @TomashKhamlai,

I have created [PR](https://github.com/magento/graphql-ce/pull/763) with the fix of the issue. Could you clarify is it correct? Or maybe check?

Thanks.
