### ISSUE TITLE
Docs: Add attributes to Customer endpoint

### ISSUE THREAD

**Issue by keharper** [magento/graphql-ce#765]
### Summary (*)

#194 added several new mutations for managing customer addresses. These mutations have already been documented, but several attributes/data types still need to be documented, including:

* `extension_attributes`
* `CountryCodeEnum`

There might be others.

### Proposed solution

Update this page: https://devdocs.magento.com/guides/v2.3/graphql/reference/customer.html

**Comment by atwixfirster** [comment]
Pull request: https://github.com/magento/devdocs/pull/4977
