### ISSUE TITLE
Docs: Add documentation for related/upsell/crosssell products

### ISSUE THREAD

**Issue by keharper** [magento/graphql-ce#766]
### Summary (*)

#371 enabled product queries to return related/upsell/crosssell products. This needs to be documented.

### Proposed solution

Update the ProductInterface table at https://devdocs.magento.com/guides/v2.3/graphql/reference/products.html

Also provide an example that includes at least one of related/upsell/crosssell.

**Comment by atwixfirster** [comment]
PR: https://github.com/magento/devdocs/pull/4978

**Comment by keharper** [comment]
fixed in https://github.com/magento/devdocs/pull/4986
