### ISSUE TITLE
Test framework documentation

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#77]
As a Magento developer, I need complete documentation for the GraphQL test framework so that I can learn to use this framework and use it in my developement. 

Today we have existing docs for REST/SOAP tests but we need to create the same for GraphQL: 
https://devdocs.magento.com/guides/v2.2/get-started/web-api-functional-testing.html

Content should be delivered to DevDocs

Documentation should ideally include: 
- Overview
- Implementation Details
   - Any pre-requisites
   - Architecture
- How to Create New Test
- How to Run the Tests
   - Prerequisites

**Comment by keharper** [comment]
Some basic information is available at https://devdocs.magento.com/guides/v2.3/graphql/functional-testing.html . More info could be added, including mentioning the `dev/tests/api-functional/phpunit_graphql.xml.dist` file.

**Comment by naydav** [comment]
https://devdocs.magento.com/guides/v2.3/graphql/functional-testing.html
