### ISSUE TITLE
[Test Coverage] PaypalGraphQl API Functional

### ISSUE THREAD

**Issue by pmclain** [magento/graphql-ce#772]
### Description
Queries and Mutations introduced in `Magento_PaypalGraphQl` lack api functional test coverage. A module for mocking the Paypal API should be introduced `dev/tests/api-functional/_files/Magento`

**Comment by dthampy** [comment]
Queries and mutations introduced for the below Paypal variations are covered by integration tests:
- PaypalExpressCheckout
- PaypalPayflow_Pro 
- Paypal_payflow_Link

**Comment by pmclain** [comment]
@naydav There's no clear adapter within Magento_Paypal to rewrite for mocking in api-functional tests similar to what was done in #757 and #392. It also looks like integration tests aren't running on this repo. I haven't executed the tests locally, but I would hope the schema changes introduced in #757 would have caused related integration tests referenced above to fail.

**Comment by naydav** [comment]
@TomashKhamlai 
Please communicate with @pmclain and check the coverage of PayPal  functionality
Thanks
