### ISSUE TITLE
[Obsolete]

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#78]
Security analysis

**Comment by DanielRuf** [comment]
Security issues should be addressed to some security@ email address and not in the public in general.

**Comment by misha-kotov** [comment]
This story is just for visibility and is not in reference to a specific security issue. We've made a decision to put all GraphQL stories on this public backlog regardless of whether they'll be handled by community or internally at Magento.

**Comment by misha-kotov** [comment]
After further discussion, we are going to close this item to avoid confusion
