### ISSUE TITLE
BundleItemOption.qty / quantity schema inconsistency 

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#786]
### Preconditions (*)

1. No preconditions

### Steps to reproduce (*)

1. No steps

### Expected result (*)

1. `quantity` on line 61 of **app/code/Magento/BundleGraphQl/etc/schema.graphqls** 

### Actual result (*)

1. `qty` on line https://github.com/magento/graphql-ce/blob/82fc82659f115c3e96e81c7cb64379cdec92d60a/app/code/Magento/BundleGraphQl/etc/schema.graphqls#L61

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/788
