### ISSUE TITLE
urlResolver support for absolute paths

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#79]
As a Magento Developer, I want urlResolver to support absolute paths in addition to relative so that it's easier for me to pass it URLs without performing additional formatting. 

This story is only for the *input* of the urlResolver query. The output fields will be corrected in the scope of https://github.com/magento/graphql-ce/issues/80

**Acceptance Criteria:** 
- urlResolver accepts absolute and relative URLs as input (relative urls already work today)
- Changes are covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.

**Comment by misha-kotov** [comment]
@naydav @pfantini I updated the description and AC to make this more clear. Let me know if there are any more outstanding questions here.

**Comment by naydav** [comment]
@misha-kotov 

So for example, if we have a request
```
{
  urlResolver(url:"privacy-policy-cookie-restriction-mode")
  {
   id
   relative_url
   absolute_url 
   type
  }
}
```

Result should be
```
{
  "data": {
    "urlResolver": {
      "id": 4,
      "relative_url": "cms/page/view/page_id/4",
      "absolute_url": "http://graphql.local/index.php/cms/page/view/page_id/4",
      "type": "CMS_PAGE"
    }
  }
}
```
Correct?
But in such a case, I can not get a target_path

**Comment by misha-kotov** [comment]
This story is about the input only. User should be able to pass an absolute url to the resolver as input and get a valid response: 
```
{
  urlResolver(url:"http://magento23.mk/privacy-policy-cookie-restriction-mode/")
  {
```

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/398
