### ISSUE TITLE
Separate cart items are created instead of quantity increment

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#792]
...and they are joined together only if the last cart-item gets an update.

Related to #699

The cart is not updating properly: new cart items are created instead of changing quantity while adding the same product to the cart. At the same time update of the first cart-item do not trigger recalculation while update of the last one joins them back together.

Note: could be specific to customizable_options

https://github.com/magento/graphql-ce/pull/699/commits/cfd065e923f5e7db5ed350a76e77128e485995b0

### Preconditions (*)

1. Create a configurable product with a customizable option that is not required
![2019-07-29-16-02-graphql-ce loc](https://user-images.githubusercontent.com/11827230/62051830-e312cf80-b21c-11e9-91de-efcf65c1e9da.png)

2. Add this product to cart via `addConfigurableProductsToCart`. Specify that **package** is `D` and **quantity** is `3` 
3. Change **quantity** to `2` via `updateCartItems`
3) Add this product to cart via `addConfigurableProductsToCart`. Specify that **package** is `D` and **quantity** is `3` (repeat what was done in step 2 without any changes. Even quantity is updated it is still the same cartItem)
4. Verify that your cart contains 2 cart items. Stop reproducing here if your information differs. For example:
```graphql
{
  "data": {
    "updateCartItems": {
      "cart": {
        "items": [
          {
            "id": "17",
            "quantity": 2
          },
          {
            "id": "19",
            "quantity": 3
          }
        ]
      }
    }
  }
}
```

### Steps to reproduce (*)

1. Update the first item
```graphql
mutation {
  updateCartItems(input: {
    cart_id: "X9klnJz5K840LhG22VeJPvoOnHFZ6KsZ"
    cart_items: {
      cart_item_id: 17
      quantity: 4
      
    }
  }) {
    cart {
      items {
        id
        quantity
      }
    }
  }
}
```

My result was:
```graphql
{
  "data": {
    "updateCartItems": {
      "cart": {
        "items": [
          {
            "id": "17",
            "quantity": 4
          },
          {
            "id": "19",
            "quantity": 3
          }
        ]
      }
    }
  }
}
```
2. Update last item
```graphql
mutation {
  updateCartItems(input: {
    cart_id: "X9klnJz5K840LhG22VeJPvoOnHFZ6KsZ"
    cart_items: {
      cart_item_id: 19
      quantity: 4
      
    }
  }) {
    cart {
      items {
        id
        quantity
      }
    }
  }
}
```

### Expected result (*)

1. Predictive behavior
2. Quantity increment for the request with the same product

### Actual result (*)

1. Suddenly, it becomes clear that items are the same.
```graphql{
  "data": {
    "updateCartItems": {
      "cart": {
        "items": [
          {
            "id": "17",
            "quantity": 8
          }
        ]
      }
    }
  }
}
```

**Comment by rogyar** [comment]
Basically, the issue appears even on a first attempt to update the configurable product quantity. Just go through the steps 1-3 and try fetching the cart information:
```graphql
{
  cart(cart_id:"$maskedQuoteId") {
    items {
      id
      quantity
      product {
        name
      }
    }
  }
}
```
You will see that the quantity has not been updated.
It might be related but I'm going to create another issue
