### ISSUE TITLE
WebAPI test failing with MSI for AddProductToCartTest::testAddMoreProductsThatAllowed

### ISSUE THREAD

**Issue by cpartica** [magento/graphql-ce#795]
### Preconditions (*)

1.Deploy 2.3-develop with latest MSI
2.Run integration tests

### Steps to reproduce (*)
1.You will see a failure:
Magento\GraphQl\CatalogInventory\AddProductToCartTest::testAddMoreProductsThatAllowed
Failed asserting that exception message 'GraphQL response contains errors: Could not add the product with SKU custom-design-simple-product to the shopping cart: The requested qty exceeds the maximum qty allowed in shopping cart
' contains 'The most you may purchase is 5.'.
 

### Expected result (*)

1. Test should pass

### Actual result (*)

1. Test doesn't pass

**Comment by cpartica** [comment]
From our investigations it was this PR that caused it:
https://github.com/magento/magento2ce/pull/4542

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/796
