### ISSUE TITLE
[Cart Operations] Fetch guest shopper cart

### ISSUE THREAD

**Issue by paliarush** [magento/graphql-ce#8]
As a Magento developer, I need to fetch the shopping cart via GraphQL so that I can build basic ecommerce experiences for shoppers on the front-end using only GraphQL.

As an initial iteration of GraphQL support for cart, expose guest cart query using resolver based on service contracts.

References:
- [How to expose a new query via GraphQL in Magento](https://devdocs.magento.com/guides/v2.3/graphql/develop/create-graphqls-file.html)
- [\Magento\Quote\Api\GuestCartRepositoryInterface::get](https://github.com/magento/magento2/blob/b2ce2a37d921b5ad88fc38663fc0ff3dd6c582d1/app/code/Magento/Quote/Api/GuestCartRepositoryInterface.php#L22)

**Acceptance Criteria**:
1. It is possible, using GraphQL, to query information about the cart created via REST APIs
1. Changes are covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.
1. Appropriate documentation is updated in DevDocs

**Comment by roma-glushko** [comment]
Hi @paliarush how are you?

I'm working on this task right now and I have a couple of questions I would like to clarify with you.
1. Do we really need to distinguish between guest/customer quotes? They are returned by different service contracts right now, but result interface is the same. Probably it may make easier to deal with both cases in the same way on the frontend. CC @nuzil 
2. I'm thinking about such signature for quote API:

```
type Query {
    quote(quoteId: String): Quote @resolver(class: "Magento\\QuoteGraphQl\\Model\\Resolver\\QuoteResolver") @doc(description: "Quote")
}

type Quote @doc(description: "") {
    store_id: Int @doc(description: "")
    customer: Customer @doc(description: "")
    customer_note: String @doc(description: "")
    currency: CurrencyEnum @doc(description: "")
    is_guest: Boolean @doc(description: "")
    is_virtual: Boolean @doc(description: "")
    items_qty: Int @doc(description: "")
    items_count: Int @doc(description: "")
    billing_address: CustomerAddress @doc(description: "")
    items: [QuoteItem] @doc(description: "")
}

type QuoteItem @doc(description: "") {
    item_id: Int @doc(description: "")
    sku: String @doc(description: "")
    qty: Int @doc(description: "")
    price: Price @doc(description: "")
    options: [CustomizableOptionInterface] @doc(description: "")
}
```

Would it be okay to expose only this data here? Should I add something else?

Thanks,
Roman.

**Comment by paliarush** [comment]
Thanks for proposing the schema for cart query, @roma-glushko. I think we should pause work on current task until we get final version of schema approved here https://github.com/magento/architecture/pull/15 
Please leave your feedback, and I will definitely incorporate your proposal into the schema.

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/266
