### ISSUE TITLE
UrlResolver: relative, seo-friendly, system urls

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#80]
As a Magento Developer, I want urlResolver to return the url in convenient formats so that it's easier for me to process it without much additional formatting.

Currently, the urlResolver query returns one field, `canonical_url`. The problem is, canonical urls are expected to be 1. absolute, and 2. SEO-friendly. Current `canonical_url` is neither. This story is to have the output return a correct canonical url and also the internal system url. 

Steps to reproduce: 
1. Pass a valid product url to urlResolver

Request 
```
{
  urlResolver(url: "/phoebe-zipper-sweatshirt.html") {
    id
    canonical_url
  }
}
```

Actual result: 
1. canonical_url is a relative, non SEO-friendly url
```
{
  "data": {
    "urlResolver": {
      "id": 1138,
      "canonical_url": "catalog/product/view/id/1138"
    }
  }
}
```

Expected result: 
1. Canonical URL is a full absolute SEO-friendly URL
2. System URL is a relative system URL
```
{
  "data": {
    "urlResolver": {
      "id": 1138,
      "canonical_url": "catalog/product/view/id/1138"   # this field to be deprecated
      "url": {
      	"canonical": "http://store.com/phoebe-zipper-sweatshirt.html"
      	"system": "catalog/product/view/id/1138"
      }
    }
  }
}
```

**Acceptance criteria:**
- Deprecate current `canonical_url` field (removing it is backwards-incompatible)
- Add new `url > canonical` and `url > system` fields
- `canonical` url is an absolute, SEO-friendly url
- `system` url is the relative, id-based, internal url 
- Changes are covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.

**Comment by misha-kotov** [comment]
@naydav @pfantini @paliarush updated the issue description and acceptance criteria. Please review and let me know if something is not clear.

**Comment by novikor** [comment]
@misha-kotov , it the issue still actual? There is a mess of issues and pull requests.
