### ISSUE TITLE
Configurable variants which were added manually and have custom option(s) should not be added to cart

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#803]
### Preconditions (*)

Related to #799

1. Color attribute has options: **black**, **white**
2. Attribute set: **attr-color-black-and-white** has **color** attribute
3. Simple Product with SKU **simple-product-1-black** with a required custom option of any type is created
4. Simple Product with SKU **simple-product-1-white** is created
5. Configurable product with SKU **configurable-product-1** has product variants added manually. (Keep in mind that all the products have visibility **Catalog/Search** by default.)

### Steps to reproduce (*)

1. Use query `products` to gather information about options. The main idea is to use the next code snippet:
```graphql
    	... on CustomizableProductInterface {
        options {
          option_id
          required
          sort_order
          title
          __typename
        }
        __typename
      }
```
The part of the output is:
```graphql
"stock_status": "IN_STOCK",
          "options": [
            {
              "option_id": 2,
              "required": true,
              "sort_order": 1,
              "title": "opt",
              "__typename": "CustomizableFieldOption"
            }
          ],
```
2. Add configurable product to cart using next query but first verify that Customer cannot add this as a variation of the Configurable Product and the only option he has is to buy the **simple-product-1-black**
```graphql
mutation {
  addConfigurableProductsToCart(
    input: {
      cart_id: "{{ $cart_id }}"
      cart_items: {
        data: {
          quantity: 1
          sku: "simple-product-1-black"
        }
        customizable_options: {
          id: 2
          value_string: "Hello!"
        }
        parent_sku: "configurable-product-1"
      }
    }
  ) {
    cart {
      email
      items {
        id
        quantity
      }
    }
  }
}
```
3. It is not hard to predict that Merchant changes the visibility of configurable variants of **simple-product-1-white** and **simple-product-1-black** to **Not Visible Individually**
4. Add configurable product to cart using next query but first, verify that Customer cannot add this as a variation of the Configurable Product or using catalog search or navigating through catalog **simple-product-1-black**
```graphql
mutation {
  addConfigurableProductsToCart(
    input: {
      cart_id: "{{ $cart_id }}"
      cart_items: {
        data: {
          quantity: 1
          sku: "simple-product-1-black"
        }
        customizable_options: {
          id: 2
          value_string: "Hello!"
        }
        parent_sku: "configurable-product-1"
      }
    }
  ) {
    cart {
      email
      items {
        id
        quantity
      }
    }
  }
}
```

### Expected result (*)

1. The same behavior.

### Actual result (*)

1. When catalog visibility has changed to **Not Visible Individually** it is not possible to find out what is the id of the option and which type of option it is.
2. Creates a "feature" for unfair trades. This is not allowed from Storefront.
![Peek 2019-08-05 18-53](https://user-images.githubusercontent.com/11827230/62477785-5afb6f80-b7b2-11e9-899e-92f7f6e79466.gif)

**Comment by pmclain** [comment]
Simple products with required options are not valid configurable variants. Child variants with required options are explicitly excluded when loading the child products

https://github.com/magento/graphql-ce/blob/b1c944b69b3a7504fa3cda663694481debac362a/app/code/Magento/ConfigurableProduct/Model/ResourceModel/Product/Type/Configurable.php#L161-L172

This behavior can be seen in the admin and on the storefront. Below is a configurable product with two configurable attributes. I have added an optional custom option to the first variant sku:

<img width="1660" alt="co-optional" src="https://user-images.githubusercontent.com/12674247/63632453-33a30000-c604-11e9-94ca-067583ba8f00.png">

The variant `option 1, option 1` is available on the storefront:
<img width="349" alt="Screen Shot 2019-08-24 at 12 12 11 AM" src="https://user-images.githubusercontent.com/12674247/63632448-26861100-c604-11e9-906c-a89f1235e5d5.png">

After requiring the custom option the simple product is no longer listed as a variant of the configurable product in the admin:

<img width="1670" alt="co-required" src="https://user-images.githubusercontent.com/12674247/63632452-33a30000-c604-11e9-8e06-1a3971de1d1f.png">

The variant `option 1, option 1` is not available on the storefront:

<img width="403" alt="Screen Shot 2019-08-24 at 12 11 42 AM" src="https://user-images.githubusercontent.com/12674247/63632449-26861100-c604-11e9-9395-27fa309f09f4.png">

**Comment by TomashKhamlai** [comment]
They are not valid but still can be added using GraphQL. I think it is an issue and desirable behavior is as the title of the issue states that configurable variants which were added manually and have custom option(s) should not be added to cart.
