### ISSUE TITLE
Root category ID

### ISSUE THREAD

**Issue by lenaorobei** [magento/graphql-ce#816]
- add `root_category_id` to the `StoreConfig` 
- write a resolver for it
- get real DB value for root category ID
- if no `id` is specified `category` query should return root category id
- cover with api-functional test

``` graphql
type StoreConfig @doc(description: "The type contains information about a store config") {
    ...
    root_category_id: Int @doc(description: "The ID ot root category") @resolver(class: "New\Resolver\Here")
}
```

**Comment by fooman** [comment]
Do you mind providing some more details on what exactly `root_category_id` should be. I have had a look at `app/code/Magento/CatalogGraphQl/Model/Resolver/CategoryTree.php` which in the code mentions 

```
        $rootCategoryId = $this->getCategoryId($args);
        if ($rootCategoryId !== Category::TREE_ROOT_ID) {
            $this->checkCategoryIsActive->execute($rootCategoryId);
        }
```

which for some reason hard codes the TREE_ROOT_ID as
`TREE_ROOT_ID = 1;`

A quick comparison to a typical DB yields
```
mysql> select * from store_group;
+----------+------------+--------------------+------------------+------------------+--------------------+
| group_id | website_id | name               | root_category_id | default_store_id | code               |
+----------+------------+--------------------+------------------+------------------+--------------------+
|        0 |          0 | Default            |                0 |                0 | default            |
|        1 |          1 | Main Website Store |                2 |                1 | main_website_store |
+----------+------------+--------------------+------------------+------------------+--------------------+
2 rows in set (0.01 sec)
```

So I am not sure if there is already something odd going on there.

Seeing that we can have `root_category_id` in the same request as `children` should `root_category_id` relate to the root of which the children have been requested (requiring  category id input)?

If that is not the case would it make sense to add the store's root category id to the `StoreConfig` query instead?

**Comment by lenaorobei** [comment]
@fooman thanks for pointing this out. I updated the ticket description. `TREE_ROOT_ID ` constant needs to be marked as deprecated and real DB value needs to be returned.
If no `id` is specified `category` query should return root category id. In addition to that `root_category_id` field needs to be added to the  `StoreConfig` type.

**Comment by Rus0** [comment]
#cd19LATAM

**Comment by Rus0** [comment]
#cd19latam
