### ISSUE TITLE
Cart Items Inconsistency

### ISSUE THREAD

**Issue by supernova-at** [magento/graphql-ce#830]
### Preconditions (*)

1. Magento `2.3.2`

### Steps to reproduce (*)

Using a `2.3.2` Magento backend located at `MAGENTO_BACKEND_URL`, perform the following:

#### 1. Request a new cart using the REST API

POST `https://MAGENTO_BACKEND_URL/rest/V1/guest-carts`

The response contains the new cart's ID, which I'll call `CART_ID`.

#### 2. Add an item to the cart using the REST API

⚠️ *Be sure to replace `CART_ID`* ⚠️ 
POST `https://MAGENTO_BACKEND_URL/rest/V1/guest-carts/CART_ID/items`

**POST data:**
⚠️ *Be sure to replace `CART_ID`* ⚠️ 

```json
{
  "cartItem": {
    "qty": 1,
    "sku": "VSK12",
    "quote_id": "CART_ID",
    "product_type": "configurable",
    "product_option": {
      "extension_attributes": {
        "configurable_item_options": [
          {
            "option_id": "176",
            "option_value": 20
          },
          {
            "option_id": "179",
            "option_value": 30
          }
        ]
      }
    }
  }
}
```

#### 3. Query for the items in the cart using GraphQL

⚠️ *Be sure to pass in your `CART_ID` as `$cart_id`* ⚠️ 

```graphql
query cartItems($cart_id:String!){
  cart (cart_id:$cart_id) {
    items {
      id
      product {
        id
        name
      }
      quantity
    }
  }
}
```

### Expected result (*)

1. I expect the cart to contain a single entry for the item I added, with the correct quantity.

### Actual result (*)

The GraphQL response contains a duplicate, extra copy of the item:

```json
{
  "data": {
    "cart": {
      "items": [
        {
          "id": "1667",
          "product": {
            "id": 1117,
            "name": "Isadora Skirt"
          },
          "quantity": 1
        },
        {
          "id": "1668",
          "product": {
            "id": 411,
            "name": "Isadora Skirt"
          },
          "quantity": 1
        }
      ]
    }
  }
}
```

In fact, an extra copy with quantity one (1) of every item shows up no matter what the initial `qty` is set to when adding items via the REST API.

**Comment by fooman** [comment]
The response would be consistent with the database format. When adding a configurable product is added to the cart Magento stores 2 line items - the configurable and the simple product that is the requested variation (I believe this is done as the inventory count is on the simple product).

In other places Magento differentiates between 
`$quote->getAllItems()` would return the 2 items
`$quote->getAllVisibleItems()` would only return the configurable item. 

Maybe a new query `visibleCartItems` is needed for your purposes or a flag isVisible on the individual cartItems?

**Comment by pmclain** [comment]
Only visible cart items should be returned starting with the next release https://github.com/magento/graphql-ce/commit/b7dd416c443daf6160a3d1046da80b90b624d024

**Comment by supernova-at** [comment]
Thanks all!
