### ISSUE TITLE
[Wish List] Add products to the Wish List

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#831]
## Story
As a Customer, I want to add products to the Wish List.

## Business Value
Helps Customer to buy things that cannot be bought right now.
 
## Preconditions 
Customer is authorized by authorization header which contains a valid token.

## Acceptance Criteria

- [ ] GraphQL provides a mutation through which the current Customer can add products to the wishlist.
- [ ] The user gets `WishlistOutput` data on success.
- [ ] The quantity of the item is incremented by the quantity specified in the request if Wish List already contains the same item.
- [ ] Product can be saved in Wish List without options.
- [ ] If options are selected they must be saved in the Wish List.
- [ ] User should be able to add Out of Stock product to Wish List.
- [ ] Functionality is covered by api-functional tests

Approved schema: https://github.com/magento/architecture/blob/master/design-documents/graph-ql/coverage/AddProductsToWishlist.graphqls

**Comment by lenaorobei** [comment]
Approved schema https://github.com/magento/architecture/blob/master/design-documents/graph-ql/coverage/AddProductsToWishlist.graphqls

**Comment by lenaorobei** [comment]
Closed in order to not to increase tech debt and keep feature parity with storefront approach.
