### ISSUE TITLE
[Wish List] Guest Shopper or another Customer cannot see/modify the Wish List

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#832]
## Story
As a Customer I need to know that my Wish List is private and existing validation doesn't provide tips for violation.

## Business Value
Customers data is private and can't be used by other Customers or Guests.
 
## Preconditions 
Customer is authorized by authorization header which contains a valid token.

## Acceptance Criteria
- [ ] A guest shopper cannot see the wishlist of any user
- [ ] A guest shopper cannot change the wishlist for any user
- [ ] The user gets an error when the Authorization header is not present: `You must log in or register to add items to your wishlist.`
- [ ] The user gets an error when Customer's token exists but expired: `You must log in or register to add items to your wishlist.`
- [ ] The user gets an error when the token doesn't exist: `The current customer isn't authorized.`

Not supposed to be supported by current schema:
~When User tries to access somebody's Wish List by incrementing or decrementing his own ID value the only he sees the message: `The current customer doesn't have Wish List with id - %ID.`~
~When User tries to access the Wish List that actually doesn't exist he sees the message `The current customer doesn't have Wish List with id - %ID.` and cannot get the difference between Wish Lists that do not belongs to him and Wish Lists that do not exist.~
~When User tries to access the Wish List with an ID that exceeds Int32 limits he sees standard GraphQL error.~
~When User tries to access the Wish List with less or equal `0` he sees that validation message `ID should be equal or greater than 0`.~

**Comment by lenaorobei** [comment]
Closing this as it is the part of AC in another tickets
