### ISSUE TITLE
[Wish List][Commerce] GraphQL schema should be flexible to support multiple Wish Lists on Magento Cloud and Magento Commerce

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#833]
## Story
As a Magento developer, I want to have a flexible interface which uses the same way to access wishlists as it is used in Magento frontend. 

## Business Value
Allows external developers to use the same queries and mutations. Saves time for internal Magento developers.
 
## Preconditions 
No preconditions

## Acceptance Criteria
- [ ] The Wish List can be accessed by ID.
- [ ] Multiple Wish Lists are returned if the ID was not specified on Magento Cloud and Magento Commerce. The ID is proposed to be optional.
- [ ] One WishList is returned as an only child of the array on Magento Open-Source. It is flexible. Sometimes features migrate from Commerce to Open Source.

**Comment by lenaorobei** [comment]
Closed in order to not to increase tech debt and keep feature parity with storefront approach.
