### ISSUE TITLE
[Wish List] Customer is able to add product(s) from the Wish List to the cart

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#835]
## Story
As a Customer, I want to move one or more products Wish List to the cart

## Business Value
Customer resumes the purchase after the long break.
 
## Preconditions 
Customer is authorized by authorization header which contains a valid token.

## Acceptance Criteria
- [ ] Products with no options and saved quantity must be adde to cart.
- [ ] Products must have minimus quantity of 1 to be added to cart.
- [ ] Products with saved options must be added to cart with those options.
- [ ] Configurable product with no selected options cannot be added to cart. GraphQL must return the following error message: `Please select options for before adding product to cart`.
- [ ] GraphQL must return the product page URL in addition to the error message.

**Comment by lenaorobei** [comment]
Closed in order to not to increase tech debt and keep feature parity with storefront approach.
