### ISSUE TITLE
[Wish List] Customer can paginate items in the Wish List  by 10, 20  and 50 per page

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#838]
## Story
As a Customer, I want to control the number of elements displayed in my Wish List

## Business Value
Customer adjusts the number of displayed items to get even better user experience.
 
## Preconditions 
Customer is authorized by authorization header which contains a valid token.

## Acceptance Criteria
- [ ] When the Wish List is empty, then the response is a message "You have no items in your wish list."
- [ ] When the Wish List contains some items, then the number of items is returned.
- [ ] When the Wish List contains some items, then not more than 10 items are returned and pagination filter returns default data - 10.
- [ ] When the Wish List contains some items and pager configured to show 10 items, then not more than 10 items are returned and pagination filter returns 10.
- [ ] When the Wish List contains some items and pager configured to show 20 items, then not more than 20 items are returned and pagination filter returns 20.
- [ ] When the Wish List contains some items and pager configured to show 50 items, then not more than 50 items are returned and pagination filter returns 50.
- [ ] When the Wish List contains some items and pager configured to show fewer than 10 items, then it behaves as it was configured to show 10 items and pagination filter returns 10.
- [ ] When the Wish List contains some items and pager configured to show more than 10 items but not 20 or 50, then it behaves as it was configured to show 10 items and pagination filter returns 10.

**Comment by lenaorobei** [comment]
Closed in order to not to increase tech debt and keep feature parity with storefront approach.
