### ISSUE TITLE
[Wish List] Customer shares his Wish List

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#839]
## Story
As a Customer, I want to share my Wish List.

## Business Value
Customer finds this as an easy and safe way to show the goods he is really interested in.
 
## Preconditions 
Customer is authorized by authorization header which contains a valid token.

## Acceptance Criteria
- [ ] Any number between 1 and 10 of emails can be added to the list of recipients separated by a comma.
- [ ] A validation message occurs when the list is an empty array or one of the next cases:
`[0], ["0"], [,,], ["",]`
- [ ] A validation message occurs when the list contains an invalid email address.
- [ ] Behavior: all or nothing. Wishlist is not shared until requirements are not fulfilled.
- [ ] When admin increases the number of allowed addresses, those settings are admired.
- [ ] Customer can not add 10,001 recipients on the default configuration or when max allowed a limit of 10,000 is set.

**Comment by lenaorobei** [comment]
Closed in order to not to increase tech debt and keep feature parity with storefront approach.
