### ISSUE TITLE
Return URL Rewrites for products

### ISSUE THREAD

**Issue by paliarush** [magento/graphql-ce#84]
As a Magento developer, I want GraphQL to return enough data so I can construct category-inclusive product urls so I can render context-aware product links on category pages and support the built-in "use categories path for product URLs" feature. 

`products` query already supports [canonical URL](https://github.com/magento/graphql-ce/issues/2) for products, this URL is returned as if it was generated by search  with no category added to the URL. For example `https://magento.store/some-product.html`. 

Sometimes it makes sense to have category added as part of SEO friendly URL, for example `https://magento.store/some-category/some-product.html`. It can be useful while rendering links to products from the specific category page.

AC:
- Add `url_rewrites`: `![UrlRewrite]` field to `ProductInterface` GraphQL type
- `UrlRewrite` GraphQL type should have the following fields:
    - `url`: `String`
    - `parameters`: `[HttpQueryParameter]`. `HttpQueryParameter` type should have fields:
        - `name`: `String`
        - `value`: `String`
- It should be possible to reuse the same types and resolvers for other entities in the future, e.g. for categories or CMS pages
- Redirect rewrites must be excluded from the response (see rewrites grid in the admin panel for more info)
- Modularity should be taken into account and new dependencies between modules should not be introduced. `ProductInterface` schema should be modified via changes in `Magento/CatalogUrlRewriteGraphQl` module
- Changes are covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/107
