### ISSUE TITLE
[Wish List] Customer is not allowed to interact with Wish List is disabled in the configuration

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#840]
## Story
As a Merchant, I want to disable Wish List. 

## Business Value
Merchant has full control over Magento features and can disable this feature for any reason.
 
## Preconditions 
Customer is authorized by authorization header which contains a valid token.

## Acceptance Criteria
- [ ] When the Wish List is disabled and Cache is in the valid state then Customer should see the message which indicates that this feature was disabled for this store.

**Comment by lenaorobei** [comment]
Closed in order to not to increase tech debt and keep feature parity with storefront approach.
