### ISSUE TITLE
[Wish List][Commerce] Create an empty Wish List

### ISSUE THREAD

**Issue by nrkapoor** [magento/graphql-ce#846]
### Story (*)
As a customer I want to create an empty Wish List so i can add products to it at a later time.

### Business Value (*)
Customer can save some personal information in order to memorize the purpose of the purchase after a long period of time.

### Acceptance Criteria
- [ ] Customers can create an empty Wish List. 
- [ ] Customers can specify a name for the Wish List. 
- [ ] Customers can specify if the wishlist is private or public. 

### Additional information
<img width="1293" alt="Screen Shot 2019-08-21 at 1 43 12 PM" src="https://user-images.githubusercontent.com/4700273/63459374-0b57ad80-c41a-11e9-8343-9a1ddb0fee85.png">
<img width="693" alt="Screen Shot 2019-08-21 at 1 43 20 PM" src="https://user-images.githubusercontent.com/4700273/63459383-0e529e00-c41a-11e9-95e5-891063c729f9.png">

**Comment by lenaorobei** [comment]
Closed in order to not to increase tech debt and keep feature parity with storefront approach.
