### ISSUE TITLE
[Wish List] Remove Wish List

### ISSUE THREAD

**Issue by lenaorobei** [magento/graphql-ce#847]
## Story
As a Customer, I want to be able to remove a Wish List.
 
## Preconditions 
Customer is authorized by authorization header which contains a valid token.

## Acceptance Criteria

- [ ] GraphQL provides a mutation through which the current Customer can remove existing Wish List by **UUID**? @paliarush please confirm
- [x] Customer cannot delete the wishlist of another customer
- [x] Guest cannot delete the wishlist of customer

**Comment by Krielkip** [comment]
@magento I am working on it

**Comment by Krielkip** [comment]
In Magento a customer only has one wishlist. There is no need to add the option to add an id / uuid for the wishlist. 
Maybe in the future we can add this feature.

**Comment by lenaorobei** [comment]
Closed in order to not to increase tech debt and keep feature parity with storefront approach.
