### ISSUE TITLE
[Wish List] Remove products from the Wish List

### ISSUE THREAD

**Issue by lenaorobei** [magento/graphql-ce#849]
## Story
As a Customer, I want to be able to remove a one or more products from Wish List.
 
## Preconditions 
Customer is authorized by authorization header which contains a valid token.

## Acceptance Criteria

- [ ] GraphQL provides a mutation through which the current Customer can remove added to the Wish List products by `wishlist_item_id`
- [ ] Covered with api-functional tests

**Comment by LucasCalazans** [comment]
Hey @lenaorobei, I'm working on this.

**Comment by LucasCalazans** [comment]
I figured out that there is a PR to this feature. - #1024

**Comment by lenaorobei** [comment]
Hi @LucasCalazans! This issue is related to removing products from wishlist, https://github.com/magento/graphql-ce/pull/1024 - to removing actual wishlist (entity), so it is different.

**Comment by LucasCalazans** [comment]
Oh, sorry, it's true. I got confused

**Comment by lenaorobei** [comment]
Here is the approved schema for this task https://github.com/magento/architecture/pull/326/files

**Comment by lenaorobei** [comment]
Closed in order to not to increase tech debt and keep feature parity with storefront approach.
