### ISSUE TITLE
[Wish List] Edit product in the Wish List 

### ISSUE THREAD

**Issue by lenaorobei** [magento/graphql-ce#850]
## Story
As a Customer, I want to be able to edit product in Wish List.

## Preconditions 
Customer is authorized by authorization header which contains a valid token.

## Acceptance Criteria

- [ ] GraphQL provides a mutation through which the current Customer can add/update `comment` in the wishlist by `wishlist_item_id` please confirm
- [ ] GraphQL provides a mutation through which the current Customer can add/update product `quantity` in the wishlist by `wishlist_item_id`

**Comment by Krielkip** [comment]
@magento I am working on it

**Comment by lenaorobei** [comment]
Closed in order to not to increase tech debt and keep feature parity with storefront approach.
