### ISSUE TITLE
Product filter with price not working

### ISSUE THREAD

**Issue by hitumca** [magento/graphql-ce#857]
### Preconditions (*)

1. Product search Graphql query with magento 2.3.2
```graphql
{
  products(
    search: "samsung"
    filter: {
     price: {
        lt: "10"
      }
    }
    pageSize: 25
    currentPage:1
    sort: {
      price: DESC
      name:  ASC
    }
  )
  {
    items {
      name
      sku
      description {
        html
      }
      price {
        regularPrice {
          amount {
            value
            currency
          }
        }
      }
    }
    total_count
    page_info {
      page_size
    }
  }
}
```

### Steps to reproduce (*)

1. For reproduct same issue product search with keyword and price with lt: '10' condition

### Expected result (*)

1. The result should not show a product which price greater than 10. 
2. The result also not related to the search keyword match

### Actual result (*)

1.
```graphql
{
  "data": {
    "products": {
      "items": [
        {
          "name": "Galaxy Note 10 Galaxy Buds",
          "sku": "Galaxy Note 10 Galaxy Buds",
          "description": {
            "html": ""
          },
          "price": {
            "regularPrice": {
              "amount": {
                "value": 20,
                "currency": "USD"
              }
            }
          }
        }
      ],
      "total_count": 4,
      "page_info": {
        "page_size": 1
      }
    }
  }
}
```

**Comment by chalov-anton** [comment]
The **lt** field is not defined by type _FilterRangeTypeInput._ 
Only **From** and **To** are available under _Price_ 

![260919_field lt is not defined by type FilterRangeTypeInput](https://user-images.githubusercontent.com/45624059/65687520-2b5e3a80-e072-11e9-81b3-152b261b092e.png)

The Issue can be Closed
