### ISSUE TITLE
Add product filter by product id

### ISSUE THREAD

**Issue by cjelger** [magento/graphql-ce#86]
It would be nice to be able to filter products by id and not only by sku. So for example
```
{
  products(
    filter: {
      id: {
        eq: "123"
      }
    }
  ) {
    items {
      sku
   }
}

**Comment by zetlen** [comment]
In lieu of this, we could also produce another `product` query type for getting individual products, which takes `id` as its argument.

**Comment by paliarush** [comment]
@cjelger @zetlen ID was intentionally removed from the interface as an internal identifier. 
Which use cases are not covered with SKU filters and covered with ID filters?

**Comment by zetlen** [comment]
@paliarush The only reason I asked about ID is that the [`EntityURL` type](https://github.com/magento/graphql-ce/blob/53241b92bc33b7382f04131bfca789bafff31f24/app/code/Magento/UrlRewriteGraphQl/etc/schema.graphqls) implements it.

`EntityURL` is the object that PWAs request to tell them how to request further data. For each type of entity, the PWA will need to request that entity (unless it's acceptable in production to query a collection and filter for an individual entity, which is what we do today for products).

It's nice to have a globally unique `ID`, because then you can get any single entity by passing `ID` as a query variable. If we won't have ID fields, we need another way to fetch an individual of any type of entity that `EntityUrl` can return.

Perhaps `EntityUrl` can return a configuration for a filter that mirrors the `FilterInputType`, instead of an ID:
```graphql
enum FilterOperationEnum @doc(description: "The types of operations available in a FilterTypeInput".) {
    eq @doc(description: "Equals")
    finset @doc(description: "Find in set. The value can contain a set of comma-separated values")
    from @doc(description: "From. Must be used with 'to'")
    gt @doc(description: "Greater than")
    gteq @doc(description: "Greater than or equal to")
    in @doc(description: "In. The value can contain a set of comma-separated values")
    like @doc(description: "Like. The specified value can contain % (percent signs) to allow matching of 0 or more characters")
    lt @doc(description: "Less than")
    lteq @doc(description: "Less than or equal to")
    moreq @doc(description: "More than or equal to")
    neq @doc(description: "Not equal to")
    notnull @doc(description: "Not null")
    null @doc(description: "Is null")
    to @doc(description: "To. Must be used with 'from'")
    nin @doc(description: "Not in. The value can contain a set of comma-separated values")
}

type FilterConfiguration {
  field: String! @doc(description: "The name of the field this filter applies to, e.g. `sku`")
  operation: FilterOperationEnum! @doc(description: "The operation this filter runs on the field.")
  value: String @doc(description: "Arguments to the filter operation.")
  or: FilterConfiguration[] @doc(description: "Optionally, more FilterConfigurations to include as an OR clause.")
}

type EntityUrl @doc(description: "EntityUrl is an output object containing the `id`, `canonical_url`, and `type` attributes") {
    filter: FilterConfiguration[] @doc(description: "Pre-configured filter objects that can be used to build a FilterInputType for retrieving this entity in a subsequent query.")
    canonical_url: String @doc(description: "The internal relative URL. If the specified  url is a redirect, the query returns the redirected URL, not the original.")
    type: UrlRewriteEntityTypeEnum @doc(description: "One of PRODUCT, CATEGORY, or CMS_PAGE.")
}
```

This is just an idea to give you a sense of what we need. If there is a simpler or easier way to get an arbitrary entity, please recommend it!

**Comment by zetlen** [comment]
Example query response:

```json
{
  "data": {
    "type": "PRODUCT",
    "canonical_url": "https://example.com/prod.html",
    "filter": [
      {
        "field": "sku",
        "operation": "eq",
        "value": "PROD-001"
      }
    ]
  }
}
```

In my suggestion, a list of multiple FilterConfigurations would be ANDed together, and a filter configuration with an `or` value would OR together with the recursive list of FilterConfigurations.  would take precedence over AND, but this is how filters appear to work today.

**Comment by paliarush** [comment]
@zetlen what if we change the type of `id` field in `EntityUrl` to `String` and return SKU in case when the entity type is a product? SKU is globally unique identifier for products and can be used with current filter.

**Comment by cjelger** [comment]
@paliarush Actually we strictly do not need that "filter by ID" so if you want to keep it private, it's ok for us. We initially requested that because we needed an "get product by id" endpoint for the Magento integrations, but because of other issues, we decided to use the SKU as ID too, so we no longer need that. Sorry for the noise and thx for replying.

**Comment by ronak2ram** [comment]
@cjelger @zetlen 
We can make the product filter used by entity_id(Product Id). If you still looking for the filter with entity_id then I will create PR for the same filter functionality.

**Comment by zetlen** [comment]
That would be fine, @ronak2ram . There's no use case for using a filter when looking up a specific entity! But it does need to be a root query type `product`, for sure. That query could take multiple optional arguments for different globally unique product identifiers.

**Comment by naydav** [comment]
Closed because we considered that `entity_id` is surrogate key and in new code, we need to use `SKU`.

@zetlen 
Please, reopen if it's needed for PWA track (with some described scenario).
Thanks

**Comment by supernova-at** [comment]
> Please, reopen if it's needed for PWA track (with some described scenario).

Here is a very common scenario: The user navigates to a category page and then to a product detail page.

Let's examine what happens (I've simplified things where possible):

To populate the category page, the PWA issues a `category` GraphQL query alongside a `products` query using the category's `id`:

```graphql
category(id: $id) {
  # some category fields
}
products(
  filter: { category_id: { eq: $idString } } 
  # some other criteria
) {
  items {
    id
    name
    sku
    url_key
    # some other individual product fields
  } 
```

To simplify things, let's say this category only has one product in it - `Product A` - and that we included all the fields of `Product A` that the PDP needs. `Product A` is now in our client-side cache, keyed by `Product_{id}` (or `Product_{sku}`, or whatever).

When the user navigates to the PDP for `Product A`, we know that we already have all the details for this product that we need in the cache.

An individual `product` query by `id` (or `sku`, or whatever) would easily be able to find `Product A`'s entry in the cache and could immediately serve it to the end user, saving a roundtrip to the server. This is the ideal scenario.

Unfortunately, without that individual `product` query we have to issue a filtered `products` query:

```graphql
products(
  filter: { sku: { eq: $sku } }
) {
  items {
    # The same individual product fields we queried for before
  }
}
```

And the results of *this* query have not been previously cached. The individual product with that `sku` is cached to be sure, but this query does not return a `ProductInterface`, it returns a `Product` type, which nests individual `ProductInterface`s under `items`.

Therefore the cache lookup fails and we have to hit the network to retrieve `Product A`'s details that we already have in the cache. Sad faces all around 😭 😄 .

---

PWA Studio does maintain code that manually attempts to find the correct cache entry for the scenario described above. It is possible to do, it just is a long runaround for a case that is so common and should be so straightforward.

**Comment by supernova-at** [comment]
> Please, reopen if it's needed for PWA track (with some described scenario).

Here is a very common scenario: The user navigates to a category page and then to a product detail page.

Let's examine what happens (I've simplified things where possible):

To populate the category page, the PWA issues a `category` GraphQL query alongside a `products` query using the category's `id`:

```graphql
category(id: $id) {
  # some category fields
}
products(
  filter: { category_id: { eq: $idString } } 
  # some other criteria
) {
  items {
    id
    name
    sku
    url_key
    # some other individual product fields
  } 
```

To simplify things, let's say this category only has one product in it - `Product A` - and that we included all the fields of `Product A` that the PDP needs. `Product A` is now in our client-side cache, keyed by `Product_{id}` (or `Product_{sku}`, or whatever).

When the user navigates to the PDP for `Product A`, we know that we already have all the details for this product that we need in the cache.

An individual `product` query by `id` (or `sku`, or whatever) would easily be able to find `Product A`'s entry in the cache and could immediately serve it to the end user, saving a roundtrip to the server. This is the ideal scenario.

Unfortunately, without that individual `product` query we have to issue a filtered `products` query:

```graphql
products(
  filter: { sku: { eq: $sku } }
) {
  items {
    # The same individual product fields we queried for before
  }
}
```

And the results of *this* query have not been previously cached. The individual product with that `sku` is cached to be sure, but it is a `ProductInterface`. This query does not return a `ProductInterface`. It returns a `Product` type, which nests individual `ProductInterface`s under `items`.

Therefore the cache lookup fails and we have to hit the network to retrieve `Product A`'s details that we already have in the cache. Sad faces all around 😭 😄 .

---

PWA Studio does maintain code that manually attempts to find the correct cache entry for the scenario described above. It is possible to do, it just is a long runaround for a case that is so common and could be straightforward.

**Comment by eboxrocks** [comment]
I'd like to add we are having problems using this API. The doc specifies that "id" should be the product id, but it is returning the content staging row_id rather than entity_id. There are definitely scenarios that you would want the original entity id back, as third party graphql extensions written for magento could very well use the entity_id as the identifier for a product (and not the sku) as is the case with one we are working with.

I would suggest that there be another "entity_id" field on the graphql API that will always point to the product entity_id value.

CC @brendanfalkowski

**Comment by brendanfalkowski** [comment]
Reference to bug reported: https://github.com/magento/graphql-ce/issues/1063
