### ISSUE TITLE
[Checkout] Remove setPaymentAndPlaceOrder mutation

### ISSUE THREAD

**Issue by YevSent** [magento/graphql-ce#875]
### Overview

The #723 introduces `setPaymentAndPlaceOrder` mutation to set the payment method for the cart and place an order via the same mutation. 
After internal discussion, we decided to remove `setPaymentAndPlaceOrder` as GraphQL guarantees that multiple mutations will be executed one by one via one HTTP request https://graphql.org/learn/queries/.

### Summary (*)
Remove `setPaymentAndPlaceOrder` mutation.

### Proposed solution
Instead of using `setPaymentAndPlaceOrder` mutation, two mutations should be used:

```graphql
mutation {
  setPaymentMethodOnCart(
      input:{
        cart_id:$cart_id
        payment_method:{
            code:"braintree"
            braintree:{
                payment_method_nonce:"payment_nonce"
            }
        }
    }
  ) {
      cart {
          selected_payment_method {
              code
          }
      }
  }
  placeOrder(
      input: {
          cart_id: $cart_id
      }
  ) {
    order {
      order_id
    }
  }
}
```

This allows solving the potential issues related to data actualization between multiple requests. But at the same time, now, it will be a developer responsibility to define the order of mutations execution as it depends on payment integration features.

**Comment by lenaorobei** [comment]
AC:

- if this mutation was already released, it is marked as deprecated instead of removing
- covered with api-functional tests
