### ISSUE TITLE
[Braintree] Add description to BraintreeInput

### ISSUE THREAD

**Issue by YevSent** [magento/graphql-ce#876]
Braintree payment method input has multiple fields like: `device_data`, `is_active_payment_token_enabler`, `payment_method_nonce` which don't have the description.

### Summary (*)
The Braintree payment fields should have a description.

**Comment by sedonik** [comment]
Hi @lenaorobei @joni-jones,
I've created [PR](https://github.com/magento/graphql-ce/pull/909) with docs updates.
Please check is it correctly.
