### ISSUE TITLE
[Checkout] Rename order_id for Order type

### ISSUE THREAD

**Issue by YevSent** [magento/graphql-ce#877]
### Summary
The `Order` type has `order_id` field which represents increment id (order number) but not the order entity id.

### Acceptance criteria
 - Deprecate `order_id`
 - Introduce new field `order_number: String!`
 - Cover with tests

**Comment by lenaorobei** [comment]
AC:
- if this field was already released, it is marked as deprecated instead of removing
- covered with api-functional tests
