### ISSUE TITLE
[Checkout] Rename increment_id for CustomerOrder type

### ISSUE THREAD

**Issue by YevSent** [magento/graphql-ce#878]
### Summary
The `CustomerOrder` type has `increment_id` field which represents order number on the storefront. The backend service contracts use this field as is but for the storefront API doesn't have business logic for it and the most usage - show to customer the number of the order.

### Acceptance Criteria
 - Deprecate `increment_id` in `CustomerOrder` type
 - Introduce `order_number: String!` in `CustomerOrder` type
 - Cover with tests

**Comment by lenaorobei** [comment]
AC:
- if this field was already released, it is marked as deprecated instead of removing
- covered with api-functional tests

**Comment by okorshenko** [comment]
@strell \Magento\GraphQl\Sales\OrdersTest

Example: https://github.com/XxXgeoXxX/graphql-ce/commit/2c4adbf63b0c108cd45be7df2c335b0dbad8adff
