### ISSUE TITLE
[Braintree] Change description for createBraintreeClientToken mutation

### ISSUE THREAD

**Issue by YevSent** [magento/graphql-ce#879]
The `createBraintreeClientToken` mutation sends a request to generate a client token used by JS SDK for initialization.  The current description says: `Creates Braintree Client Token for creating client-side nonce.` but actually this client token needed to initialize SDK but not to generate a payment nonce. Also, it might be used in different scenarios like Kount initialization.

### Proposed solution
Change the mutation description to `Creates Client Token for Braintree Javascript SDK initialization.`.

**Comment by karyna-t** [comment]
I'm going to work on this issue.

**Comment by lenaorobei** [comment]
https://github.com/magento/graphql-ce/pull/959
