### ISSUE TITLE
'small_image' in 'ProductInterface' does not have enough info

### ISSUE THREAD

**Issue by DrewML** [magento/graphql-ce#88]
### Preconditions

1. `2.3-develop` branch

### Steps to reproduce

1. Using `/graphql`, POST a query that requests the `small_image` for a product
2. The `string` returned for the `small_image` field will be in the format `/m/b/mb02-gray-0.jpg`.
3. The format returned does not have enough information for a client-rendered Magento application to append the uri to an `img` tag. The returned format is `https://mmnl.test/media/catalog/product/cache/2765542505660baab28ecd555e27366e/m/b/mb02-gray-0.jpg`

### Expected result

1. `small_image` (and other image values in the `ProductInterface`) should return a URL that can be used as-is to fetch the associated image

### Actual result

1. `small_image` is populated with a value that can not be used without obtaining other info about cache configuration.

### AC:
- Rename `small_image` to `small_image_url` and return URL in the following format `https://mmnl.test/media/catalog/product/cache/2765542505660baab28ecd555e27366e/m/b/mb02-gray-0.jpg`
- [Optional] Fix existing GraphQL tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.

**Comment by jissereitsma** [comment]
Perhaps there simply needs to come a second property `small_image_url` because you could argue that the image stays the same, while the URL might change depending on media URL settings. The problem here is that the GraphQL schema refers to the generic `ProductInterface` of the catalog module, which counts as `@api`. I've tried to fix things there, but that leads to a lot of work.

An easier solution would simply be to use a variable `media_url` within PWA? What I've now done for myself is create a new file `src/config.json` with a JSON string `{"media_url": "/media/catalog/product/"}`. Next, in the component where a real URL is needed, I import this JSON (`import config from 'src/config.json';`) and I construct the URL itself using `config.media_url + small_image`. Works for me.

**Comment by DrewML** [comment]
> An easier solution would simply be to use a variable media_url within PWA? What I've now done for myself is create a new file src/config.json with a JSON string {"media_url": "/media/catalog/product/"}. Next, in the component where a real URL is needed, I import this JSON (import config from 'src/config.json';) and I construct the URL itself using config.media_url + small_image. Works for me.

There is a problem here with portability. If I'm writing a component for any PWA theme to be able to consume, I'd like to not require that every consumer always pass me a `media_url`, and I can't import it from a static JSON file, because my component is not part of a specific theme.

The other issue is just duplication. If this value already exists on the backend, it wouldn't be great to duplicate that in front-end configuration. We then have an easy place for configs to mismatch and lead to hard-to-debug 404s.

Another thing to keep in mind, too, is that this API is not just for PWA - it's for every consumer of Magento APIs over the next (however many) years. Consuming the API should require as little knowledge of Magento's image management as possible. The more intuitive the API is for new consumers, the better!

**Comment by jissereitsma** [comment]
@DrewML Completely get it. Testing such a component would also point out the flaw - it is another dependency. So it should be in the GraphQL API. However, I do not think it should be in the `small_image` property itself. The image might remain the same, while the URL to that image might be different (CDN, media database). A property `small_image_url` sounds more adequate.

**Comment by DrewML** [comment]
@jissereitsma that sounds reasonable to me. You'd know better than I would what the right call is here 🙂

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/132
