### ISSUE TITLE
[PayPal] Rename PayflowProUrlInput

### ISSUE THREAD

**Issue by YevSent** [magento/graphql-ce#880]
The `PayflowProUrlInput` contains a list of URLs such as `cancel_url`, `error_url`, `return_url`, but not only one URL.

### Proposed solution
Rename `PayflowProUrlInput` to `PayflowProUrlsInput`.

**Comment by lenaorobei** [comment]
AC:

- if the input was already released, it is marked as deprecated instead of removing
- covered with api-functional tests
