### ISSUE TITLE
[PayPal] Rename PayflowProToken type

### ISSUE THREAD

**Issue by YevSent** [magento/graphql-ce#881]
The `PayflowProToken` type represents the output type for `createPayflowProToken` mutation. The output type represents not only token itself but also other fields and also should have a name consistent to other output types.

### Proposed solution
 - Deprecate `PayflowProToken` via comments in GraphQL schema docs
 -  Introduce a replacement `CreatePayflowProTokenOutput`.

**Comment by lenaorobei** [comment]
AC:

- if this field was already released, it is marked as deprecated instead of removing
- covered with api-functional tests
