### ISSUE TITLE
[PayPal] Rename PaypalExpressToken type

### ISSUE THREAD

**Issue by YevSent** [magento/graphql-ce#882]
The `PaypalExpressToken` type represents the output type for `createPaypalExpressToken` mutation. The output type represents not only token itself but also other fields and also should have a name consistent to other output types.

### Proposed solution
 - Deprecate `PaypalExpressToken` via comments
- Introduce replacement`PaypalExpressTokenOutput`

**Comment by lenaorobei** [comment]
AC:

- if this field was already released, it is marked as deprecated instead of removing
- covered with api-functional tests
