### ISSUE TITLE
[Checkout] order id is exposed via CustomerOrder type

### ISSUE THREAD

**Issue by YevSent** [magento/graphql-ce#883]
The `CustomerOrder` type exposes `id` of order entity. The storefront application should not depend on IDs. Also, the current API exposes order number (increment id) which should be enough.

### Proposed solution
Remove `id` field from `CustomerOrder` type.

**Comment by fooman** [comment]
This is also the case for the current M2 frontend. It is actively used in the URLs to view the details of the customer's order. The current GraphQl is not yet able to provide details of individual orders - would be good to combine what we are aiming to do there before removing the id.
