### ISSUE TITLE
Remove purchase_order_number SelectedPaymentMethod type

### ISSUE THREAD

**Issue by YevSent** [magento/graphql-ce#885]
The `SelectedPaymentMethod` type has `purchase_order_number` field which belongs only to the offline payment method `Purchase Order`.

### Proposed solution
Remove `purchase_order_number` field from `SelectedPaymentMethod` as it belongs only to one specific payment method.

**Comment by pmclain** [comment]
`\Magento\Quote\Api\Data\PaymentInterface` has a [getter](https://github.com/magento/magento2/blob/b2ce2a37d921b5ad88fc38663fc0ff3dd6c582d1/app/code/Magento/Quote/Api/Data/PaymentInterface.php#L31) and [setter](https://github.com/magento/magento2/blob/b2ce2a37d921b5ad88fc38663fc0ff3dd6c582d1/app/code/Magento/Quote/Api/Data/PaymentInterface.php#L39) for the PO Number regardless of the selected payment method and is frequently used in B2B applications for allowing users to input a PO number with any payment method.

**Comment by YevSent** [comment]
Closed according to https://github.com/magento/graphql-ce/issues/886#issuecomment-528385688
