### ISSUE TITLE
Move purchase_order_number from quote module

### ISSUE THREAD

**Issue by YevSent** [magento/graphql-ce#886]
The `purchase_order_number` belongs to the `Purchase Order` payment solution but declared in `QuoteGraphQl` module which is not correct as quote should not have knowledge about specific payment details.

### Proposed solution
The `purchase_order_number` field declaration should be moved to `PurchaseOrderGraphQl` module.

**Comment by pmclain** [comment]
The purchase order number belongs to `Magento_Quote` [`\Magento\Quote\Api\Data\PaymentInterface`](https://github.com/magento/magento2/blob/b2ce2a37d921b5ad88fc38663fc0ff3dd6c582d1/app/code/Magento/Quote/Api/Data/PaymentInterface.php)

**Comment by YevSent** [comment]
@pmclain, you are right. I missed that PO number is a part of `\Magento\Quote\Api\Data\PaymentInterface` and `\Magento\Sales\Api\Data\OrderPaymentInterface` and it is required for Level 2 and 3 card transactions.
