### ISSUE TITLE
[Checkout] Support of Payflow Pro Vault

### ISSUE THREAD

**Issue by YevSent** [magento/graphql-ce#888]
### Description (*)
The current Payflow Pro implementation for Magento Luma checkout supports Vault tokenization for credit cards during place order flow. But the GraphQL implementation doesn't support it.

It causes API inconsistency in comparison to standard Magento Checkout.

### Expected behavior (*)
There should be a possibility to enable card tokenization for Payflow Pro payment integration.

**Comment by kvydiuk** [comment]
There is not problem with getting sandbox merchant/buyer account in PayPal.
But unfortunately i'm stuck on getting Manager account:
https://manager.paypal.com/?_ga=1.233707223.871600241.1569587287
that is required for the Payflow Pro.

**Comment by YevSent** [comment]
@kirillvidyuk could you describe your problem with obtaining PayPal Manager account?

**Comment by kvydiuk** [comment]
Hey @joni-jones,

I'm getting this error while trying to login as manager with paypal acccount:
![Screenshot_20191008-210100_Samsung Internet](https://user-images.githubusercontent.com/9048430/66420872-6fa4ef80-ea0f-11e9-946a-ffddcd7fb18f.jpg)

Same problem as described here:
https://www.paypal-community.com/t5/My-Account/Why-can-t-I-login-to-manager-paypal-com-with-my-live-paypal/td-p/1694353

Yeah, seems the country that is choosen in my paypal account is not supported by the payflow. Probably this is the cause.

And unforunatelly i have no availability to register AU, NZ or US paypal account.
