### ISSUE TITLE
Products cannot be fetched in parent/anchor category

### ISSUE THREAD

**Issue by cjelger** [magento/graphql-ce#89]
Performing a products search for a top-level/anchor category with the `category_ids` search filter does not return any product when the products are assigned in the children categories of that top/anchor category.

cc: @antonkril as discussed

See additional examples in "is_anchor not working correctly #91"

**Comment by paliarush** [comment]
Merged in scope of https://github.com/magento/magento2/commit/8eb668b677a327d0c08c1f510107209882096c02

**Comment by cjelger** [comment]
Thx @paliarush I tested the change and it works just fine.
