### ISSUE TITLE
[Checkout] Implement customerCarts query

### ISSUE THREAD

**Issue by paliarush** [magento/graphql-ce#904]
In order to be able to share customer cart between devices, there should be a way to retrieve a list of active customer carts.

Acceptance criteria:
 - schema: `customerCarts: [Cart]!` 
 - operation should give an error for guests (no valid customer token provided in the request)
 - web API functional tests for major positive scenarios

**Comment by karyna-t** [comment]
I'm going to work on this issue.

**Comment by lenaorobei** [comment]
@karyna-tsymbal-atwix it sounds great! I will this issue to you.

**Comment by lenaorobei** [comment]
Closing this issue due to requirement changes. The new flow we'll be working on:
<img width="1269" alt="Screen Shot 2019-10-14 at 9 25 11 AM" src="https://user-images.githubusercontent.com/17548019/66759273-93c85c80-ee65-11e9-9b0c-035c443bd575.png">
