### ISSUE TITLE
[Checkout] Implement mergeCarts

### ISSUE THREAD

**Issue by paliarush** [magento/graphql-ce#905]
A user should be able to start adding items to cart as a guest and proceed to checkout as logged in customer. At the moment each cart has unique hash ID and there is no way for a registered customer to proceed to checkout with the cart he created as a guest.

Suggested solution is to introduce mutation for merging two arbitrary carts accessible by the specific user.

Acceptance criteria:
 - Schema `mergeCarts(firstCartId: String!, secondCartId: String!): String!`, result should contain new cart ID
- Mutation should accept:
  - guest + guest cart IDs
  - guest + registered customer cart IDs
  - registered customer + registered customer cart IDs
- Permissions to access registered customer carts must always be verified. In case permissions are insufficient, error message must be obscured (for security purposes) and should indicate that specified cart cannot be found
 - Web API functional tests must cover all major positive scenarios and combinations
 - For performance optimization, new cart ID should point to one of the existing carts used during the merge instead of creation of completely new cart object
 - Original cart IDs must be disabled and become inaccessible. Even though one of the carts will still be active, it must be accessible only with a new unique ID

**Comment by lenaorobei** [comment]
Closing this Issue due to requirement changes. The new flow we'll be working on:
<img width="1269" alt="Screen Shot 2019-10-14 at 9 25 11 AM" src="https://user-images.githubusercontent.com/17548019/66759273-93c85c80-ee65-11e9-9b0c-035c443bd575.png">

**Comment by ajones55555** [comment]
@lenaorobei is there a ticket tracking progress on this new flow?

**Comment by lenaorobei** [comment]
@aej11a it is already implemented by internal team.
