### ISSUE TITLE
[Customer] Deprecate group_id in Customer

### ISSUE THREAD

**Issue by paliarush** [magento/graphql-ce#910]
Customer group should not be exposed in the storefront scenarios.

Acceptance criteria:
 - Deprecate `group_id` in `Customer` type
 - Return `null` instead of actual group ID for all queries.

**Comment by fooman** [comment]
Why remove it?

There is lots of reasons one might want to customise the front-end based on customer group. For example you might get to see a different banner, description, etc. 

Removing group_id from graphql without a replacement makes building such functionality harder. Not everything is between logged in vs logged out either.
