### ISSUE TITLE
[Customer] Convert gender type to enum

### ISSUE THREAD

**Issue by paliarush** [magento/graphql-ce#913]
`gender` field must be converted from int to enum type. Since this is breaking change, exact conversion strategy depends on decision made in https://github.com/magento/architecture/pull/263

**Comment by fooman** [comment]
Seeing that the PR was closed adding my question on the need for an Enum to here:

>It might not be the best place for this discussion but I feel using an Enum here for the list of genders makes us less inclusive. Example article here https://www.itspronouncedmetrosexual.com/2012/06/how-can-i-make-the-gender-question-on-an-application-form-more-inclusive/

>I would generally consider best practice (if you even have to ask) to include a freeform entry. Switching to Enum would not allow for this. But still maybe a good discussion to have before needing to do gender_v3.

**Comment by lenaorobei** [comment]
@fooman thanks for pointing. I contacted product team regarding this and will keep you updated.

**Comment by nrkapoor** [comment]
> Seeing that the PR was closed adding my question on the need for an Enum to here:
> 
> > It might not be the best place for this discussion but I feel using an Enum here for the list of genders makes us less inclusive. Example article here https://www.itspronouncedmetrosexual.com/2012/06/how-can-i-make-the-gender-question-on-an-application-form-more-inclusive/
> 
> > I would generally consider best practice (if you even have to ask) to include a freeform entry. Switching to Enum would not allow for this. But still maybe a good discussion to have before needing to do gender_v3.

@fooman Thanks for bringing this to our attention. We have approved the change to make the gender field freeform.

**Comment by lenaorobei** [comment]
Closing this issue due to requirement changes. Created internal ticket for changing `gender` to the freeform field.
