### ISSUE TITLE
[Customer] Separate mutations for customer password and email change

### ISSUE THREAD

**Issue by paliarush** [magento/graphql-ce#917]
**Acceptance criteria:**
See design document https://github.com/magento/architecture/blob/master/design-documents/graph-ql/coverage/customer-email-password-update.md

**Comment by danielrenaud** [comment]
@paliarush please add to AC that `CustomerInput.email` should be marked as required (!) in schema. It cannot currently be marked required since createCustomer and updateCustomer mutations share this input, and it is not required for updateCustomer.

**Comment by lenaorobei** [comment]
Closing this issue. Proper approach for updating customer will be implemented using storefront API.
