### ISSUE TITLE
[Customer] Deprecate customer address custom attributes

### ISSUE THREAD

**Issue by paliarush** [magento/graphql-ce#918]
In GraphQL schema custom attributes should not be put into `custom_attributes` container. 

**Acceptance criteria:**
 - Deprecate `custom_attributes` in `CustomerAddress`
 - Deprecate `custom_attributes` in `CustomAddressInput` via comments (since directives are not supported for input type fields)

**Comment by texboy** [comment]
@magento I am working on it #mm19br

**Comment by lenaorobei** [comment]
https://github.com/magento/graphql-ce/pull/932
