### ISSUE TITLE
Replace qty fields with quantity

### ISSUE THREAD

**Issue by buskamuza** [magento/graphql-ce#921]
### Summary (*)

For consistency `quantity` should be used instead of `qty` everywhere in GraphQL schema.
AC:
* `qty` is deprecated in the following places:
   * https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/CatalogGraphQl/etc/schema.graphqls#L63
   * https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/GroupedProductGraphQl/etc/schema.graphqls#L9
   * https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/WishlistGraphQl/etc/schema.graphqls#L18
* changes covered by api-function tests.

See related task for static test implementation https://github.com/magento/graphql-ce/issues/925

**Comment by soniaandrianow** [comment]
#mm19pl

**Comment by jonfres** [comment]
@magento I'm working on it
