### ISSUE TITLE
Move GraphQL schema files to graphql area

### ISSUE THREAD

**Issue by buskamuza** [magento/graphql-ce#922]
GraphQL schema files make sense only in `graphql` area of Magento application.

AC:
* all `schema.graphqls` files are moved under `graphql` area folder
* validate that application behaves as expected in case a module (for example, an extension) that extends core GraphQL schema is still located in `global` area
* Ensure GraphQl style sniffs work properly after the change https://github.com/magento/magento-coding-standard/pull/141

This change should not introduce any breaking changes as files from `global` and `graphql` areas should be collected and merged during a GraphQL request. Extensions and customizations that use old convention and have GraphQL schema files located in `global` area should continue working as before.

**Comment by antonkril** [comment]
Don't think we should do it now:
- BC violation
- in an instance that only serves Graphql and only has Graphql modules installed, there is no benefit of Graphql area

**Comment by Vinai** [comment]
This would be a big BC break providing very little benefit from my point of view. I agree with @antonkril that they should remain where they are.

**Comment by okorshenko** [comment]
Closing for now. Once we will have agreement from all parties, we can reopen this ticket.

**Comment by buskamuza** [comment]
> in an instance that only serves Graphql and only has Graphql modules installed, there is no benefit of Graphql area

@antonkril , we already have `graphql` area.

**Comment by buskamuza** [comment]
> This would be a big BC break providing very little benefit from my point of view.

I agree, the benefit is insignificant and if it's going to break somebody it's not worth it.
Which scenario will be broken if we move the files?

**Comment by Vinai** [comment]
Any existing module that has `schema.graphqls` files in `etc/` would no longer work.
Modules that aim to support multiple Magento versions would have to duplicate the files in `etc/` and `etc/graphql` which would be an increase in maintenance effort and could likely lead to bugs.

**Comment by buskamuza** [comment]
@Vinai , why? I don't propose to modify behavior of the application. Both `etc` and `etc/graphql` should be supported as schema location.
The only case when I see something can be broken is if somebody tries to load schema in non-graphql area, which I don't see as a valid use case. I can update the description if this clarification makes more sense. Or do you think somebody will be broken anyways?

**Comment by buskamuza** [comment]
I described it as:
> Extensions and customizations that use old convention and have GraphQL schema files located in global area should continue working as before.
