### ISSUE TITLE
Link to GraphQL-specific Documentation

### ISSUE THREAD

**Issue by supernova-at** [magento/graphql-ce#924]
Magento's GraphQL project has good documentation here: https://devdocs.magento.com/guides/v2.3/graphql/index.html.

Unfortunately, the main `README` in this project doesn't mention this documentation anywhere.

Developers visiting this repository are very likely looking for documentation and this should be made as easy as possible. Please link to the existing GraphQL documentation at or near the top of `README.md`.

**Comment by kandarp26** [comment]
Its already added in README file 

![image](https://user-images.githubusercontent.com/6490792/65703504-8019a980-e0a2-11e9-8876-88b967d61aa5.png)
