### ISSUE TITLE
Support GZIP

### ISSUE THREAD

**Issue by supernova-at** [magento/graphql-ce#929]
JSON + GZIP is one of GraphQL's [recommended best practices](https://graphql.org/learn/best-practices/#json-with-gzip):

> because it is mostly text, it (JSON) compresses exceptionally well with GZIP

Gzipping responses from the backend will reduce the number of bytes transferred over the wire back to the client.

Note that PWA Studio is already sending the `Accept-Encoding: gzip` header with its requests, so we can see immediate results when GZIP is enabled.

**Comment by danslo** [comment]
@supernova-at Could you elaborate on what you mean by "supporting gzip". This already works on the web-server level (nginx/apache). Are we missing something in Magento?

**Comment by nrkapoor** [comment]
@danslo - Correct. This issue must be closed.
