### ISSUE TITLE
Implement support for variables in query

### ISSUE THREAD

**Issue by PiotrSzlagura** [magento/graphql-ce#93]
### Preconditions

1. Repository version: 2.3-develop-plus-pr13-and-pr48
2. PHP: 7.1.18
3. Server: nginx, version: 1.12.2

### Steps to reproduce

1. Create empty Magento instance
2. Install sample data from repo
3. Using graphql client/plugin of your choice (tested on many of them, always with the same result) run query:
```graphql
query GetProductsQuery($page: Int, $filterInput: ProductFilterInput){
  products(
    pageSize: 10
    currentPage: $page
    filter: $filterInput
    sort: {}
  ) {
    items {
    	name
    }
  }
}
```
with variables:
```json
{
  "page": 1,
  "filterInput": {
    "price": {
    	"gt": "10"
    }
  }
}
```

### Expected result

1. Query should return filtered products list, since `ProductFilterInput` is an input type, according to scheme

### Actual result

1. Received following error:
```
Variable "$filterInput" cannot be non-input type "ProductFilterInput".
Variable "$filterInput" of type "ProductFilterInput" used in position expecting type "ProductFilterInput".
```

I've tested this approach on clean GraphQL installation and it worked without any problem.

EDIT:
After hours of debugging and testing, it turned out that this isn't even implemented. Any type given is mapped as OutputType, which finally breaks the query, as output types can't be used as query parameters. I made a workaround that works for my case for now, but it would be awesome if it was included in the core. I could share my solution with you but it's rather ugly and not universal so I doubt it could be any use for you.

**Comment by paliarush** [comment]
@PiotrSzlagura Feel free to share your solution via PR, then we can work on it together and eventually merge to the mainline.

**Comment by paliarush** [comment]
Verified the issue:
- Scalar types are supported
- Object input types are not supported. Errors  are thrown as described by @PiotrSzlagura
