### ISSUE TITLE
Include id field on objects

### ISSUE THREAD

**Issue by supernova-at** [magento/graphql-ce#930]
### Description (*)

Add an `id` field to all object types that don't currently have it.

### Expected behavior (*)

Each individual record would have an `id` that is unique within that `type`.

### Benefits / Additional Information

PWA Studio's cache would greatly benefit from an `id` field.

PWA Studio's cache combines the `id` field with the object's `__typename` to create a unique id for the entry in the cache. This allows PWA Studio to match objects in the cache across queries, potentially greatly reducing the number of requests to the server.

If this field is not included, PWA Studio has to manually maintain functions for objects to give them unique ids so that we can match data across queries. The more we miss the cache the more unnecessary requests we make to the GraphQL API.

**Comment by DrewML** [comment]
Adding some more context here: this isn't too unusual of a request/requirement. [Relay requires a stable ID field](https://facebook.github.io/relay/graphql/objectidentification.htm)

**Comment by YevSent** [comment]
I think we need moving to UUID implementation instead of exposing entity id to a storefront.

**Comment by supernova-at** [comment]
I wanted to add that an alternate solution might be to expose an "external id".

Since GraphQL clients can [alias](https://graphql.org/learn/queries/#aliases) fields, we can simply rename this `externalID` field to `id` or `_id` or whatever our client-side cache needs.

The main idea in this issue is to have GraphQL be the authority on what makes each entity unique. Otherwise each client has to code that up themselves, and that will be very prone to errors.
