### ISSUE TITLE
Product dropdown Custom attribute not working with layer navigation 2.3

### ISSUE THREAD

**Issue by hitumca** [magento/graphql-ce#931]
### Preconditions (*)

1. Magento 2.3 
2.

### Steps to reproduce (*)

1. Add new Brand dropdown product attribute with  configuration filter option yes , product list page yes, search page yes
2. Add brand option with like Apple , Samsung, Mi, Sony
3. create one configurable product and select this brand of product.

### Expected result (*)

1. This attribute should be listed as filters in category product list layer navigation .
2.

### Actual result (*)

1.Currently only category and price filters available as layer navigation 
2.

**Comment by nrkapoor** [comment]
@hitumca - we have recently merged significant updates to layered navigation in the dev branch. These changes will be official in 2.3.4. Please test the latest changes and let us know if it works for you.
