### ISSUE TITLE
Make category query compatible with staging

### ISSUE THREAD

**Issue by paliarush** [magento/graphql-ce#96]
### Preconditions

1. Magento Commerce is installed (not just open source)
2. At least one category in the system has a scheduled update

### Steps to reproduce

1. Create a new category
2. Request this category by ID via GraphQL API:
```
{
  category(id: 4) {
    name
    products(sort: {sku: ASC}) {
      total_count
      items {
        sku
      }
    }
  }
}
```

### Expected result

1. Requested category info should be returned in the result

### Actual result

1. Category in the response is `null`

### Additional info
- Possible fix is to replace `getLinkField()` with `getIdentifierField()` [here](https://github.com/magento/magento2/blob/8e2dfd61876d46df70e019c18a4d29995ce73bec/app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/CategoryTree.php#L103).
- Existing tests should be adjusted. At least this one `\Magento\GraphQl\Catalog\CategoryTest::testAnchorCategory`

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/99
