### ISSUE TITLE
Clarification request on technical aspect of querying db

### ISSUE THREAD

**Issue by leonvisscher** [magento/graphql-ce#97]
### This issue is a

Clarification request

### Expected result

Is this project the same that is being implemented in [the Magento 2.3-develop branch](https://github.com/magento/magento2/tree/2.3-develop)? When is this repo synced with the magento 2.3-develop branch, or is it the same?

I would also like some clarification, and maybe it is a suggestion for the docs, on how the technical process works of querying to the Magento GraphQL API. What is the flow of an incoming query, to response. In what way is the database issued? Is it exactly the same as normal Magento and Rest but with a graphql wrapper around it?

Thanks

**Comment by misha-kotov** [comment]
In general, we have some architectural diagrams for our web APIs (including GraphQL) shown here: https://devdocs.magento.com/guides/v2.2/coding-standards/technical-vision/webapi.html

Note this is a vision and may not correspond to current reality. As of present day, the default resolvers for GraphQL queries use resource model collections to retrieve data; however anyone can customize resolvers to retrieve data in other ways. Hope that helps. 

cc: @paliarush

**Comment by paliarush** [comment]
@leon0v thanks for your question.

This project is a mirror of https://github.com/magento/magento2/tree/2.3-develop.
When you create a PR to `magento/graphql-ce` project, it is never merged directly via `merge` button. Instead, we create internal PR and merge changes to `magento/magento2`, then the changes are propagated via fast-forward merge to `magento/graphql-ce`.

Request flow:
1. Request hits [\Magento\GraphQl\Controller\GraphQl::dispatch](https://github.com/magento/magento2/blob/ca207a65f52548f682f8fbce1eb7695e914d1019/app/code/Magento/GraphQl/Controller/GraphQl.php#L96)
1. Webonyx library is initialized with Magento GraphQL Schema
1. Request is processed by Webonyx library and corresponding resolver is invoked
1. Resolver performs necessary operations (e.g. query or mutation), here request to DB may be executed
1. Resolver response is wrapped in special `\Magento\Framework\GraphQl\Query\Resolver\Value` wrapper and returned back to Webonyx framework
1. Webonyx framework invokes all necessary resolvers and eventually constructs a response, which is returned to Front controller
2. Front controller renders the response

**Comment by paliarush** [comment]
@keharper can we improve our docs to eliminate questions related to request processing flow in the future

**Comment by leonvisscher** [comment]
@paliarush Thanks for the response :)
