### ISSUE TITLE
Cannot return several errors for one GraphQL request

### ISSUE THREAD

**Issue by kisroman** [magento/graphql-ce#970]
Now there is no ability to throw two errors, we can only implode it in one string(as in https://github.com/magento/graphql-ce/issues/961 in method getAddressErrors()). 

If you create exception GraphQlInputException it has method `addError()`, so you can add additional errors, but it doesn't work.See screenshot, I added two errors with method `addError()`, but it returns only one.

**Actual result:**
Only one last error is returned.
<img width="431" alt="Screen Shot 2019-09-27 at 13 42 29" src="https://user-images.githubusercontent.com/39631677/65763824-e519e180-e12c-11e9-8faf-4761b7abd676.png">

**Expected result:**
``` json
{
  "errors": [
    {
      "message": "First error.",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    },
    {
      "message": "Second error.",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

**Comment by lenaorobei** [comment]
See related webonyx discussion  https://github.com/webonyx/graphql-php/issues/207

**Comment by TomashKhamlai** [comment]
Related topics: #416, #625,

**Comment by lenaorobei** [comment]
AC: 
- all `todo` with reference to this issue are fixed.
