### ISSUE TITLE
[Test coverage] Cover exceptions in AssignShippingAddressToCart, AssignBillingAddressToCart

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#977]
### Description:

Cover exceptions with api-functional tests:
https://github.com/magento/graphql-ce/blob/e02dc94e04228901706936c2cac778679d5dc346/app/code/Magento/QuoteGraphQl/Model/Cart/AssignShippingAddressToCart.php#L54
https://github.com/magento/graphql-ce/blob/e02dc94e04228901706936c2cac778679d5dc346/app/code/Magento/QuoteGraphQl/Model/Cart/AssignBillingAddressToCart.php#L54
https://github.com/magento/graphql-ce/blob/e02dc94e04228901706936c2cac778679d5dc346/app/code/Magento/QuoteGraphQl/Model/Cart/AssignBillingAddressToCart.php#L56

### TestCases:
```
\Magento\GraphQl\Customer\Quote\Customer\SetShippingAddressOnCartTest
 - testWithInvalidShippingAddressesInput
```
```
 \Magento\GraphQl\Customer\Quote\Customer\SetBillingAddressOnCartTest
 - testWithInvalidBillingAddressInput
 - testSetNotExistedBillingAddressId
```

### Examples:
[Magento\GraphQl\Customer](https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Customer)
[Magento\GraphQl\Quote\Customer](https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer)

### Guide:
[Graphql Functional Testing](https://devdocs.magento.com/guides/v2.3/graphql/functional-testing.html)

**Comment by atwixfirster** [comment]
> https://github.com/magento/graphql-ce/blob/e02dc94e04228901706936c2cac778679d5dc346/app/code/Magento/QuoteGraphQl/Model/Cart/AssignShippingAddressToCart.php#L54

**done**

> https://github.com/magento/graphql-ce/blob/e02dc94e04228901706936c2cac778679d5dc346/app/code/Magento/QuoteGraphQl/Model/Cart/AssignBillingAddressToCart.php#L54

Already covered in `dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/SetBillingAddressOnCartTest.php`::`testSetNotExistedBillingAddressFromAddressBook()`

> https://github.com/magento/graphql-ce/blob/e02dc94e04228901706936c2cac778679d5dc346/app/code/Magento/QuoteGraphQl/Model/Cart/AssignBillingAddressToCart.php#L56

**done**
