### ISSUE TITLE
Product filter query doesn't return all hits

### ISSUE THREAD

**Issue by leonvisscher** [magento/graphql-ce#98]
### Preconditions

1. Magento 2.3-develop branch install with sample data

### Steps to reproduce

Perform GraphQL query:
```
{
  products(
    currentPage: 1
    filter:
    {
      name: {like: "%"},
    },
    pageSize: 1
  ) {
    items {
      name
      price {
        regularPrice {
          amount {
            value
            currency
          }
        }
      }
    }
    total_count
  }
}
```
### Expected result

1.To my understanding with this filter, all (2046) products should be returned:
![image](https://user-images.githubusercontent.com/17271164/42078916-764e3928-7b7e-11e8-8244-5d59ed198d31.png)

### Actual result

1. Response:

```
{
  "data": {
    "products": {
      "items": [
        {
          "name": "Joust Duffle Bag",
          "price": {
            "regularPrice": {
              "amount": {
                "value": 34,
                "currency": "USD"
              }
            }
          }
        }
      ],
      "total_count": 187
    }
  }
}
```

Notice that 187 products are returned. Instead of 2046.

**Comment by leonvisscher** [comment]
The issue described expected behavior because the API doesn't return items where the visibility is set to "Not Visible Individually" by default.

**Comment by facundocapua** [comment]
Hi @leon0v,

You are getting just one item due to the `pageSize`, as you put in the query:
```javascript
products(
    currentPage: 1
    filter:
    {
      name: {like: "%"},
    },
    pageSize: 1
...
```

If you want to get more items you should increase that value (take into considerations that big collections might affect performance), also consider that if you don't send any `pageSize` it has a default value of 10.

Hope that helps.

Best Regards

**Comment by leonvisscher** [comment]
Hi @facundocapua thanks for replying. The issue was already resolved. I was aware of the fact that the request only returned 1 product, but the "total_count" field stated there were 187 matches in stead of all 2046. However, this is expected behavior as stated in [this response](https://github.com/magento/graphql-ce/issues/98#issuecomment-401285273).

Thanks for replying anyway :)

Kind regards

**Comment by keharper** [comment]
@leon0v  Since this query returns unexpected results, is this a documentation issue? If yes, do you know of any other settings that would cause unexpected results?
